// Code generated by the generate package DO NOT EDIT


package Tree

import "reflect"
import "slices"
import "graphics.gd/internal/pointers"
import "graphics.gd/internal/callframe"
import "graphics.gd/internal/gdextension"
import "graphics.gd/internal/gdreference"
import "graphics.gd/internal/noescape"
import gd "graphics.gd/internal"
import "graphics.gd/internal/gdclass"
import "graphics.gd/internal/ie"
import "graphics.gd/variant"
import "graphics.gd/variant/Angle"
import "graphics.gd/variant/Euler"
import "graphics.gd/variant/Signal"
import "graphics.gd/classdb/CanvasItem"
import "graphics.gd/classdb/Control"
import "graphics.gd/classdb/GUI"
import "graphics.gd/classdb/InputEvent"
import "graphics.gd/classdb/Node"
import "graphics.gd/classdb/TreeItem"
import "graphics.gd/variant/Array"
import "graphics.gd/variant/Callable"
import "graphics.gd/variant/Dictionary"
import "graphics.gd/variant/Error"
import "graphics.gd/variant/Float"
import "graphics.gd/variant/Object"
import "graphics.gd/variant/Packed"
import "graphics.gd/variant/Path"
import "graphics.gd/variant/RID"
import "graphics.gd/variant/Rect2"
import "graphics.gd/variant/RefCounted"
import "graphics.gd/variant/String"
import "graphics.gd/variant/Vector2"

var _ Object.ID
type _ gdclass.Node
var _ gd.String
var _ RefCounted.Instance
var _ reflect.Type
var _ callframe.Frame
var _ = pointers.Cycle
var _ = Array.Nil
var _ variant.Any
var _ Callable.Function
var _ Dictionary.Any
var _ RID.Any
var _ noescape.Variant
var _ String.Readable
var _ Path.ToNode
var _ Packed.Bytes
var _ Error.Code
var _ Float.X
var _ Signal.Any
var _ Angle.Radians
var _ Euler.Radians
var _ gdextension.Object
var _ = slices.Delete[[]struct{}, struct{}]

/*
ID is a typed object ID (reference) to an instance of this class, use it to store references to objects with
unknown lifetimes, as an ID will not panic on use if the underlying object has been destroyed.
*/
type ID Object.ID
func (id ID) Instance() (Instance, bool) { return Object.As[Instance](Object.ID(id).Instance()) }
/*
Extension can be embedded in a new struct to create a Go extension of this class.

T must be a type that is embedding this [Extension] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Extension[T gdclass.Interface] struct { gdclass.Extension[T, Instance] }
/*
Singleton can be embedded in a new struct to create a Go singleton extension of the class.

It will become available as a global inside scripts and any any other Go Extension types will
have any *T typed fields filled in to point at this singleton once they have been instantiated.

T must be a type that is embedding this [Singleton] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Singleton[T gdclass.Interface] = Extension[T]
// Instance of the class with convieniently typed arguments and results.
type Instance [1]gdclass.Tree
var otype gdextension.ObjectType
var sname gdextension.StringName
var methods struct {
	clear gdextension.MethodForClass `hash:"3218959716"`
	create_item gdextension.MethodForClass `hash:"528467046"`
	get_root gdextension.MethodForClass `hash:"1514277247"`
	set_column_custom_minimum_width gdextension.MethodForClass `hash:"3937882851"`
	set_column_expand gdextension.MethodForClass `hash:"300928843"`
	set_column_expand_ratio gdextension.MethodForClass `hash:"3937882851"`
	set_column_clip_content gdextension.MethodForClass `hash:"300928843"`
	is_column_expanding gdextension.MethodForClass `hash:"1116898809"`
	is_column_clipping_content gdextension.MethodForClass `hash:"1116898809"`
	get_column_expand_ratio gdextension.MethodForClass `hash:"923996154"`
	get_column_width gdextension.MethodForClass `hash:"923996154"`
	set_hide_root gdextension.MethodForClass `hash:"2586408642"`
	is_root_hidden gdextension.MethodForClass `hash:"36873697"`
	get_next_selected gdextension.MethodForClass `hash:"873446299"`
	get_selected gdextension.MethodForClass `hash:"1514277247"`
	set_selected gdextension.MethodForClass `hash:"2662547442"`
	get_selected_column gdextension.MethodForClass `hash:"3905245786"`
	get_pressed_button gdextension.MethodForClass `hash:"3905245786"`
	set_select_mode gdextension.MethodForClass `hash:"3223887270"`
	get_select_mode gdextension.MethodForClass `hash:"100748571"`
	deselect_all gdextension.MethodForClass `hash:"3218959716"`
	set_columns gdextension.MethodForClass `hash:"1286410249"`
	get_columns gdextension.MethodForClass `hash:"3905245786"`
	get_edited gdextension.MethodForClass `hash:"1514277247"`
	get_edited_column gdextension.MethodForClass `hash:"3905245786"`
	edit_selected gdextension.MethodForClass `hash:"2595650253"`
	get_custom_popup_rect gdextension.MethodForClass `hash:"1639390495"`
	get_item_area_rect gdextension.MethodForClass `hash:"47968679"`
	get_item_at_position gdextension.MethodForClass `hash:"4193340126"`
	get_column_at_position gdextension.MethodForClass `hash:"3820158470"`
	get_drop_section_at_position gdextension.MethodForClass `hash:"3820158470"`
	get_button_id_at_position gdextension.MethodForClass `hash:"3820158470"`
	ensure_cursor_is_visible gdextension.MethodForClass `hash:"3218959716"`
	set_column_titles_visible gdextension.MethodForClass `hash:"2586408642"`
	are_column_titles_visible gdextension.MethodForClass `hash:"36873697"`
	set_column_title gdextension.MethodForClass `hash:"501894301"`
	get_column_title gdextension.MethodForClass `hash:"844755477"`
	set_column_title_tooltip_text gdextension.MethodForClass `hash:"501894301"`
	get_column_title_tooltip_text gdextension.MethodForClass `hash:"844755477"`
	set_column_title_alignment gdextension.MethodForClass `hash:"3276431499"`
	get_column_title_alignment gdextension.MethodForClass `hash:"4171562184"`
	set_column_title_direction gdextension.MethodForClass `hash:"1707680378"`
	get_column_title_direction gdextension.MethodForClass `hash:"4235602388"`
	set_column_title_language gdextension.MethodForClass `hash:"501894301"`
	get_column_title_language gdextension.MethodForClass `hash:"844755477"`
	get_scroll gdextension.MethodForClass `hash:"3341600327"`
	scroll_to_item gdextension.MethodForClass `hash:"1314737213"`
	set_h_scroll_enabled gdextension.MethodForClass `hash:"2586408642"`
	is_h_scroll_enabled gdextension.MethodForClass `hash:"36873697"`
	set_v_scroll_enabled gdextension.MethodForClass `hash:"2586408642"`
	is_v_scroll_enabled gdextension.MethodForClass `hash:"36873697"`
	set_scroll_hint_mode gdextension.MethodForClass `hash:"415911924"`
	get_scroll_hint_mode gdextension.MethodForClass `hash:"553087187"`
	set_tile_scroll_hint gdextension.MethodForClass `hash:"2586408642"`
	is_scroll_hint_tiled gdextension.MethodForClass `hash:"2240911060"`
	set_hide_folding gdextension.MethodForClass `hash:"2586408642"`
	is_folding_hidden gdextension.MethodForClass `hash:"36873697"`
	set_enable_recursive_folding gdextension.MethodForClass `hash:"2586408642"`
	is_recursive_folding_enabled gdextension.MethodForClass `hash:"36873697"`
	set_enable_drag_unfolding gdextension.MethodForClass `hash:"2586408642"`
	is_drag_unfolding_enabled gdextension.MethodForClass `hash:"36873697"`
	set_drop_mode_flags gdextension.MethodForClass `hash:"1286410249"`
	get_drop_mode_flags gdextension.MethodForClass `hash:"3905245786"`
	set_allow_rmb_select gdextension.MethodForClass `hash:"2586408642"`
	get_allow_rmb_select gdextension.MethodForClass `hash:"36873697"`
	set_allow_reselect gdextension.MethodForClass `hash:"2586408642"`
	get_allow_reselect gdextension.MethodForClass `hash:"36873697"`
	set_allow_search gdextension.MethodForClass `hash:"2586408642"`
	get_allow_search gdextension.MethodForClass `hash:"36873697"`
	set_auto_tooltip gdextension.MethodForClass `hash:"2586408642"`
	is_auto_tooltip_enabled gdextension.MethodForClass `hash:"36873697"`
}
func init() {
	gd.Links = append(gd.Links, func() {
		sname = gdextension.Host.Strings.Intern.UTF8("Tree")
		otype = gdextension.Host.Objects.Type(sname)
		gd.LinkMethods(sname, &methods, false)
		})
	gd.RegisterCleanup(func() {
		noescape.Free(gdextension.TypeStringName, &sname)
	})
}
func (self Instance) ID() ID { return ID(Object.Instance(self.AsObject()).ID()) }
// MoreArgs is a container for [Instance] functions with additional 'optional' arguments.
type MoreArgs [1]gdclass.Tree
type Expanded = MoreArgs
// MoreArgs enables certain functions to be called with additional 'optional' arguments.
func (self Instance) MoreArgs() MoreArgs { return MoreArgs(self) }
// Nil is a nil/null instance of the class. Equivalent to the zero value.
var Nil Instance
type Any interface {
	gd.IsClass
	AsTree() Instance
}
func (self Instance) Clear() { //gd:Tree.clear
	Advanced(self).Clear()
}
func (self Instance) CreateItem() TreeItem.Instance { //gd:Tree.create_item
	return TreeItem.Instance(Advanced(self).CreateItem([1]TreeItem.Instance{}[0], int64(-1)))
}
func (self MoreArgs) CreateItem(parent TreeItem.Instance, index int) TreeItem.Instance { //gd:Tree.create_item
	return TreeItem.Instance(Advanced(self).CreateItem(parent, int64(index)))
}
func (self Instance) GetRoot() TreeItem.Instance { //gd:Tree.get_root
	return TreeItem.Instance(Advanced(self).GetRoot())
}
func (self Instance) SetColumnCustomMinimumWidth(column int, min_width int)  Instance { //gd:Tree.set_column_custom_minimum_width
	Advanced(self).SetColumnCustomMinimumWidth(int64(column), int64(min_width))
	return self
}
func (self Instance) SetColumnExpand(column int, expand bool)  Instance { //gd:Tree.set_column_expand
	Advanced(self).SetColumnExpand(int64(column), expand)
	return self
}
func (self Instance) SetColumnExpandRatio(column int, ratio int)  Instance { //gd:Tree.set_column_expand_ratio
	Advanced(self).SetColumnExpandRatio(int64(column), int64(ratio))
	return self
}
func (self Instance) SetColumnClipContent(column int, enable bool)  Instance { //gd:Tree.set_column_clip_content
	Advanced(self).SetColumnClipContent(int64(column), enable)
	return self
}
func (self Instance) IsColumnExpanding(column int) bool { //gd:Tree.is_column_expanding
	return bool(Advanced(self).IsColumnExpanding(int64(column)))
}
func (self Instance) IsColumnClippingContent(column int) bool { //gd:Tree.is_column_clipping_content
	return bool(Advanced(self).IsColumnClippingContent(int64(column)))
}
func (self Instance) GetColumnExpandRatio(column int) int { //gd:Tree.get_column_expand_ratio
	return int(int(Advanced(self).GetColumnExpandRatio(int64(column))))
}
func (self Instance) GetColumnWidth(column int) int { //gd:Tree.get_column_width
	return int(int(Advanced(self).GetColumnWidth(int64(column))))
}
func (self Instance) GetNextSelected(from TreeItem.Instance) TreeItem.Instance { //gd:Tree.get_next_selected
	return TreeItem.Instance(Advanced(self).GetNextSelected(from))
}
func (self Instance) GetSelected() TreeItem.Instance { //gd:Tree.get_selected
	return TreeItem.Instance(Advanced(self).GetSelected())
}
func (self Instance) SetSelected(item TreeItem.Instance, column int)  Instance { //gd:Tree.set_selected
	Advanced(self).SetSelected(item, int64(column))
	return self
}
func (self Instance) GetSelectedColumn() int { //gd:Tree.get_selected_column
	return int(int(Advanced(self).GetSelectedColumn()))
}
func (self Instance) GetPressedButton() int { //gd:Tree.get_pressed_button
	return int(int(Advanced(self).GetPressedButton()))
}
func (self Instance) DeselectAll() { //gd:Tree.deselect_all
	Advanced(self).DeselectAll()
}
func (self Instance) GetEdited() TreeItem.Instance { //gd:Tree.get_edited
	return TreeItem.Instance(Advanced(self).GetEdited())
}
func (self Instance) GetEditedColumn() int { //gd:Tree.get_edited_column
	return int(int(Advanced(self).GetEditedColumn()))
}
func (self Instance) EditSelected() bool { //gd:Tree.edit_selected
	return bool(Advanced(self).EditSelected(false))
}
func (self MoreArgs) EditSelected(force_edit bool) bool { //gd:Tree.edit_selected
	return bool(Advanced(self).EditSelected(force_edit))
}
func (self Instance) GetCustomPopupRect() Rect2.PositionSize { //gd:Tree.get_custom_popup_rect
	return Rect2.PositionSize(Advanced(self).GetCustomPopupRect())
}
func (self Instance) GetItemAreaRect(item TreeItem.Instance) Rect2.PositionSize { //gd:Tree.get_item_area_rect
	return Rect2.PositionSize(Advanced(self).GetItemAreaRect(item, int64(-1), int64(-1)))
}
func (self MoreArgs) GetItemAreaRect(item TreeItem.Instance, column int, button_index int) Rect2.PositionSize { //gd:Tree.get_item_area_rect
	return Rect2.PositionSize(Advanced(self).GetItemAreaRect(item, int64(column), int64(button_index)))
}
func (self Instance) GetItemAtPosition(position Vector2.XY) TreeItem.Instance { //gd:Tree.get_item_at_position
	return TreeItem.Instance(Advanced(self).GetItemAtPosition(Vector2.XY(position)))
}
func (self Instance) GetColumnAtPosition(position Vector2.XY) int { //gd:Tree.get_column_at_position
	return int(int(Advanced(self).GetColumnAtPosition(Vector2.XY(position))))
}
func (self Instance) GetDropSectionAtPosition(position Vector2.XY) int { //gd:Tree.get_drop_section_at_position
	return int(int(Advanced(self).GetDropSectionAtPosition(Vector2.XY(position))))
}
func (self Instance) GetButtonIdAtPosition(position Vector2.XY) int { //gd:Tree.get_button_id_at_position
	return int(int(Advanced(self).GetButtonIdAtPosition(Vector2.XY(position))))
}
func (self Instance) EnsureCursorIsVisible() { //gd:Tree.ensure_cursor_is_visible
	Advanced(self).EnsureCursorIsVisible()
}
func (self Instance) SetColumnTitle(column int, title string)  Instance { //gd:Tree.set_column_title
	Advanced(self).SetColumnTitle(int64(column), String.From(title))
	return self
}
func (self Instance) GetColumnTitle(column int) string { //gd:Tree.get_column_title
	return string(Advanced(self).GetColumnTitle(int64(column)).String())
}
func (self Instance) SetColumnTitleTooltipText(column int, tooltip_text string)  Instance { //gd:Tree.set_column_title_tooltip_text
	Advanced(self).SetColumnTitleTooltipText(int64(column), String.From(tooltip_text))
	return self
}
func (self Instance) GetColumnTitleTooltipText(column int) string { //gd:Tree.get_column_title_tooltip_text
	return string(Advanced(self).GetColumnTitleTooltipText(int64(column)).String())
}
func (self Instance) SetColumnTitleAlignment(column int, title_alignment GUI.HorizontalAlignment)  Instance { //gd:Tree.set_column_title_alignment
	Advanced(self).SetColumnTitleAlignment(int64(column), title_alignment)
	return self
}
func (self Instance) GetColumnTitleAlignment(column int) GUI.HorizontalAlignment { //gd:Tree.get_column_title_alignment
	return GUI.HorizontalAlignment(Advanced(self).GetColumnTitleAlignment(int64(column)))
}
func (self Instance) SetColumnTitleDirection(column int, direction Control.TextDirection)  Instance { //gd:Tree.set_column_title_direction
	Advanced(self).SetColumnTitleDirection(int64(column), direction)
	return self
}
func (self Instance) GetColumnTitleDirection(column int) Control.TextDirection { //gd:Tree.get_column_title_direction
	return Control.TextDirection(Advanced(self).GetColumnTitleDirection(int64(column)))
}
func (self Instance) SetColumnTitleLanguage(column int, language string)  Instance { //gd:Tree.set_column_title_language
	Advanced(self).SetColumnTitleLanguage(int64(column), String.From(language))
	return self
}
func (self Instance) GetColumnTitleLanguage(column int) string { //gd:Tree.get_column_title_language
	return string(Advanced(self).GetColumnTitleLanguage(int64(column)).String())
}
func (self Instance) GetScroll() Vector2.XY { //gd:Tree.get_scroll
	return Vector2.XY(Advanced(self).GetScroll())
}
func (self Instance) ScrollToItem(item TreeItem.Instance) { //gd:Tree.scroll_to_item
	Advanced(self).ScrollToItem(item, false)
}
func (self MoreArgs) ScrollToItem(item TreeItem.Instance, center_on_item bool) { //gd:Tree.scroll_to_item
	Advanced(self).ScrollToItem(item, center_on_item)
}
func Get(peer TreeItem.Instance) Instance { //gd:TreeItem.get_tree
	return Instance(TreeItem.Advanced(peer).GetTree())
}
// Advanced exposes a 1:1 low-level instance of the class, undocumented, for those who know what they are doing.
type Advanced = class
type class [1]gdclass.Tree
func (o class) AsObject() [1]gdreference.Object { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (self *class) SetObject(obj [1]gdreference.Object) bool {
	if gdextension.Host.Objects.Cast(gdreference.GetObject(obj[0]), otype) != 0 {
		self[0] = gdclass.NewTree(obj[0])
		return true
	}
	return false
}
func (self *Instance) SetObject(obj [1]gdreference.Object) bool {
	if gdextension.Host.Objects.Cast(gdreference.GetObject(obj[0]), otype) != 0 {
		self[0] = gdclass.NewTree(obj[0])
		return true
	}
	return false
}
func (o Instance) AsObject() [1]gdreference.Object { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (o *Extension[T]) AsObject() [1]gdreference.Object { return o.Super().AsObject() }
func New() Instance {
if !gd.Linked {
		var placeholder = Instance([1]gdclass.Tree{gdclass.NewTree(gdreference.NewObject())})
		gd.StartupFunctions = append(gd.StartupFunctions, func() {
			if gd.Linked {
				raw, _ := gdreference.EndObject(New().AsObject()[0])
				gdreference.SetObject(gdclass.GetTree(placeholder[0])[0], raw)
				gd.RegisterCleanup(func() {
					if raw := gdreference.GetObject(placeholder.AsObject()[0]); raw != 0 {
						gdextension.Host.Objects.Unsafe.Free(raw)
					}
				})
			}
		})
		return placeholder
	}
	casted := Instance([1]gdclass.Tree{gdclass.NewTree(gdreference.OwnObject(gdextension.Host.Objects.Make(sname), gd.Free))})
	gd.ObjectNotification(casted.AsObject()[0], 0, false)
	return casted
}

func (self Instance) Columns() int { //gd:Tree.columns
		return int(int(class(self).GetColumns()))
}

// SetColumns sets the property returned by [GetColumns]. Returns the instance, so that property settings can be chained.
func (self Instance) SetColumns(value int) Instance { //gd:Tree.columns
	class(self).SetColumns(int64(value))
	return self
}

func (self Instance) ColumnTitlesVisible() bool { //gd:Tree.column_titles_visible
		return bool(class(self).AreColumnTitlesVisible())
}

// SetColumnTitlesVisible sets the property returned by [AreColumnTitlesVisible]. Returns the instance, so that property settings can be chained.
func (self Instance) SetColumnTitlesVisible(value bool) Instance { //gd:Tree.column_titles_visible
	class(self).SetColumnTitlesVisible(value)
	return self
}

func (self Instance) AllowReselect() bool { //gd:Tree.allow_reselect
		return bool(class(self).GetAllowReselect())
}

// SetAllowReselect sets the property returned by [GetAllowReselect]. Returns the instance, so that property settings can be chained.
func (self Instance) SetAllowReselect(value bool) Instance { //gd:Tree.allow_reselect
	class(self).SetAllowReselect(value)
	return self
}

func (self Instance) AllowRmbSelect() bool { //gd:Tree.allow_rmb_select
		return bool(class(self).GetAllowRmbSelect())
}

// SetAllowRmbSelect sets the property returned by [GetAllowRmbSelect]. Returns the instance, so that property settings can be chained.
func (self Instance) SetAllowRmbSelect(value bool) Instance { //gd:Tree.allow_rmb_select
	class(self).SetAllowRmbSelect(value)
	return self
}

func (self Instance) AllowSearch() bool { //gd:Tree.allow_search
		return bool(class(self).GetAllowSearch())
}

// SetAllowSearch sets the property returned by [GetAllowSearch]. Returns the instance, so that property settings can be chained.
func (self Instance) SetAllowSearch(value bool) Instance { //gd:Tree.allow_search
	class(self).SetAllowSearch(value)
	return self
}

func (self Instance) HideFolding() bool { //gd:Tree.hide_folding
		return bool(class(self).IsFoldingHidden())
}

// SetHideFolding sets the property returned by [IsFoldingHidden]. Returns the instance, so that property settings can be chained.
func (self Instance) SetHideFolding(value bool) Instance { //gd:Tree.hide_folding
	class(self).SetHideFolding(value)
	return self
}

func (self Instance) EnableRecursiveFolding() bool { //gd:Tree.enable_recursive_folding
		return bool(class(self).IsRecursiveFoldingEnabled())
}

// SetEnableRecursiveFolding sets the property returned by [IsRecursiveFoldingEnabled]. Returns the instance, so that property settings can be chained.
func (self Instance) SetEnableRecursiveFolding(value bool) Instance { //gd:Tree.enable_recursive_folding
	class(self).SetEnableRecursiveFolding(value)
	return self
}

func (self Instance) EnableDragUnfolding() bool { //gd:Tree.enable_drag_unfolding
		return bool(class(self).IsDragUnfoldingEnabled())
}

// SetEnableDragUnfolding sets the property returned by [IsDragUnfoldingEnabled]. Returns the instance, so that property settings can be chained.
func (self Instance) SetEnableDragUnfolding(value bool) Instance { //gd:Tree.enable_drag_unfolding
	class(self).SetEnableDragUnfolding(value)
	return self
}

func (self Instance) HideRoot() bool { //gd:Tree.hide_root
		return bool(class(self).IsRootHidden())
}

// SetHideRoot sets the property returned by [IsRootHidden]. Returns the instance, so that property settings can be chained.
func (self Instance) SetHideRoot(value bool) Instance { //gd:Tree.hide_root
	class(self).SetHideRoot(value)
	return self
}

func (self Instance) DropModeFlags() int { //gd:Tree.drop_mode_flags
		return int(int(class(self).GetDropModeFlags()))
}

// SetDropModeFlags sets the property returned by [GetDropModeFlags]. Returns the instance, so that property settings can be chained.
func (self Instance) SetDropModeFlags(value int) Instance { //gd:Tree.drop_mode_flags
	class(self).SetDropModeFlags(int64(value))
	return self
}

func (self Instance) SelectMode() SelectMode { //gd:Tree.select_mode
		return SelectMode(class(self).GetSelectMode())
}

// SetSelectMode sets the property returned by [GetSelectMode]. Returns the instance, so that property settings can be chained.
func (self Instance) SetSelectMode(value SelectMode) Instance { //gd:Tree.select_mode
	class(self).SetSelectMode(value)
	return self
}

func (self Instance) AutoTooltip() bool { //gd:Tree.auto_tooltip
		return bool(class(self).IsAutoTooltipEnabled())
}

// SetAutoTooltip sets the property returned by [IsAutoTooltipEnabled]. Returns the instance, so that property settings can be chained.
func (self Instance) SetAutoTooltip(value bool) Instance { //gd:Tree.auto_tooltip
	class(self).SetAutoTooltip(value)
	return self
}

func (self Instance) ScrollHorizontalEnabled() bool { //gd:Tree.scroll_horizontal_enabled
		return bool(class(self).IsHScrollEnabled())
}

// SetScrollHorizontalEnabled sets the property returned by [IsHScrollEnabled]. Returns the instance, so that property settings can be chained.
func (self Instance) SetScrollHorizontalEnabled(value bool) Instance { //gd:Tree.scroll_horizontal_enabled
	class(self).SetHScrollEnabled(value)
	return self
}

func (self Instance) ScrollVerticalEnabled() bool { //gd:Tree.scroll_vertical_enabled
		return bool(class(self).IsVScrollEnabled())
}

// SetScrollVerticalEnabled sets the property returned by [IsVScrollEnabled]. Returns the instance, so that property settings can be chained.
func (self Instance) SetScrollVerticalEnabled(value bool) Instance { //gd:Tree.scroll_vertical_enabled
	class(self).SetVScrollEnabled(value)
	return self
}

func (self Instance) ScrollHintMode() ScrollHintMode { //gd:Tree.scroll_hint_mode
		return ScrollHintMode(class(self).GetScrollHintMode())
}

// SetScrollHintMode sets the property returned by [GetScrollHintMode]. Returns the instance, so that property settings can be chained.
func (self Instance) SetScrollHintMode(value ScrollHintMode) Instance { //gd:Tree.scroll_hint_mode
	class(self).SetScrollHintMode(value)
	return self
}

func (self Instance) TileScrollHint() bool { //gd:Tree.tile_scroll_hint
		return bool(class(self).IsScrollHintTiled())
}

// SetTileScrollHint sets the property returned by [IsScrollHintTiled]. Returns the instance, so that property settings can be chained.
func (self Instance) SetTileScrollHint(value bool) Instance { //gd:Tree.tile_scroll_hint
	class(self).SetTileScrollHint(value)
	return self
}

func (self class) Clear()  { //gd:Tree.clear
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.clear, 0, &struct{}{})
}
func (self class) CreateItem(parent [1]gdclass.TreeItem, index int64) [1]gdclass.TreeItem { //gd:Tree.create_item
	var r_ret = noescape.Call[gdextension.Object]( gd.ObjectChecked(self.AsObject()), methods.create_item, gdextension.SizeObject|(gdextension.SizeObject<<4)|(gdextension.SizeInt<<8), &struct{parent gdextension.Object; index int64}{	gdextension.Object(gdreference.GetObject(gdclass.GetTreeItem(parent[0])[0])), index})
	var ret = [1]gdclass.TreeItem{gdclass.NewTreeItem(gdreference.LetObject(r_ret))}
	return ret
}
func (self class) GetRoot() [1]gdclass.TreeItem { //gd:Tree.get_root
	var r_ret = noescape.Call[gdextension.Object]( gd.ObjectChecked(self.AsObject()), methods.get_root, gdextension.SizeObject, &struct{}{})
	var ret = [1]gdclass.TreeItem{gdclass.NewTreeItem(gdreference.LetObject(r_ret))}
	return ret
}
func (self class) SetColumnCustomMinimumWidth(column int64, min_width int64)  { //gd:Tree.set_column_custom_minimum_width
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_column_custom_minimum_width, 0|(gdextension.SizeInt<<4)|(gdextension.SizeInt<<8), &struct{column int64; min_width int64}{column, min_width})
}
func (self class) SetColumnExpand(column int64, expand bool)  { //gd:Tree.set_column_expand
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_column_expand, 0|(gdextension.SizeInt<<4)|(gdextension.SizeBool<<8), &struct{column int64; expand bool}{column, expand})
}
func (self class) SetColumnExpandRatio(column int64, ratio int64)  { //gd:Tree.set_column_expand_ratio
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_column_expand_ratio, 0|(gdextension.SizeInt<<4)|(gdextension.SizeInt<<8), &struct{column int64; ratio int64}{column, ratio})
}
func (self class) SetColumnClipContent(column int64, enable bool)  { //gd:Tree.set_column_clip_content
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_column_clip_content, 0|(gdextension.SizeInt<<4)|(gdextension.SizeBool<<8), &struct{column int64; enable bool}{column, enable})
}
func (self class) IsColumnExpanding(column int64) bool { //gd:Tree.is_column_expanding
	var r_ret = noescape.Call[bool]( gd.ObjectChecked(self.AsObject()), methods.is_column_expanding, gdextension.SizeBool|(gdextension.SizeInt<<4), &struct{column int64}{column})
	var ret = r_ret
	return ret
}
func (self class) IsColumnClippingContent(column int64) bool { //gd:Tree.is_column_clipping_content
	var r_ret = noescape.Call[bool]( gd.ObjectChecked(self.AsObject()), methods.is_column_clipping_content, gdextension.SizeBool|(gdextension.SizeInt<<4), &struct{column int64}{column})
	var ret = r_ret
	return ret
}
func (self class) GetColumnExpandRatio(column int64) int64 { //gd:Tree.get_column_expand_ratio
	var r_ret = noescape.Call[int64]( gd.ObjectChecked(self.AsObject()), methods.get_column_expand_ratio, gdextension.SizeInt|(gdextension.SizeInt<<4), &struct{column int64}{column})
	var ret = r_ret
	return ret
}
func (self class) GetColumnWidth(column int64) int64 { //gd:Tree.get_column_width
	var r_ret = noescape.Call[int64]( gd.ObjectChecked(self.AsObject()), methods.get_column_width, gdextension.SizeInt|(gdextension.SizeInt<<4), &struct{column int64}{column})
	var ret = r_ret
	return ret
}
func (self class) SetHideRoot(enable bool)  { //gd:Tree.set_hide_root
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_hide_root, 0|(gdextension.SizeBool<<4), &struct{enable bool}{enable})
}
func (self class) IsRootHidden() bool { //gd:Tree.is_root_hidden
	var r_ret = noescape.Call[bool]( gd.ObjectChecked(self.AsObject()), methods.is_root_hidden, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) GetNextSelected(from [1]gdclass.TreeItem) [1]gdclass.TreeItem { //gd:Tree.get_next_selected
	var r_ret = noescape.Call[gdextension.Object]( gd.ObjectChecked(self.AsObject()), methods.get_next_selected, gdextension.SizeObject|(gdextension.SizeObject<<4), &struct{from gdextension.Object}{	gdextension.Object(gdreference.GetObject(gdclass.GetTreeItem(from[0])[0]))})
	var ret = [1]gdclass.TreeItem{gdclass.NewTreeItem(gdreference.LetObject(r_ret))}
	return ret
}
func (self class) GetSelected() [1]gdclass.TreeItem { //gd:Tree.get_selected
	var r_ret = noescape.Call[gdextension.Object]( gd.ObjectChecked(self.AsObject()), methods.get_selected, gdextension.SizeObject, &struct{}{})
	var ret = [1]gdclass.TreeItem{gdclass.NewTreeItem(gdreference.LetObject(r_ret))}
	return ret
}
func (self class) SetSelected(item [1]gdclass.TreeItem, column int64)  { //gd:Tree.set_selected
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_selected, 0|(gdextension.SizeObject<<4)|(gdextension.SizeInt<<8), &struct{item gdextension.Object; column int64}{	gdextension.Object(gdreference.GetObject(gdclass.GetTreeItem(item[0])[0])), column})
}
func (self class) GetSelectedColumn() int64 { //gd:Tree.get_selected_column
	var r_ret = noescape.Call[int64]( gd.ObjectChecked(self.AsObject()), methods.get_selected_column, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) GetPressedButton() int64 { //gd:Tree.get_pressed_button
	var r_ret = noescape.Call[int64]( gd.ObjectChecked(self.AsObject()), methods.get_pressed_button, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetSelectMode(mode SelectMode)  { //gd:Tree.set_select_mode
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_select_mode, 0|(gdextension.SizeInt<<4), &struct{mode SelectMode}{mode})
}
func (self class) GetSelectMode() SelectMode { //gd:Tree.get_select_mode
	var r_ret = noescape.Call[SelectMode]( gd.ObjectChecked(self.AsObject()), methods.get_select_mode, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) DeselectAll()  { //gd:Tree.deselect_all
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.deselect_all, 0, &struct{}{})
}
func (self class) SetColumns(amount int64)  { //gd:Tree.set_columns
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_columns, 0|(gdextension.SizeInt<<4), &struct{amount int64}{amount})
}
func (self class) GetColumns() int64 { //gd:Tree.get_columns
	var r_ret = noescape.Call[int64]( gd.ObjectChecked(self.AsObject()), methods.get_columns, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) GetEdited() [1]gdclass.TreeItem { //gd:Tree.get_edited
	var r_ret = noescape.Call[gdextension.Object]( gd.ObjectChecked(self.AsObject()), methods.get_edited, gdextension.SizeObject, &struct{}{})
	var ret = [1]gdclass.TreeItem{gdclass.NewTreeItem(gdreference.LetObject(r_ret))}
	return ret
}
func (self class) GetEditedColumn() int64 { //gd:Tree.get_edited_column
	var r_ret = noescape.Call[int64]( gd.ObjectChecked(self.AsObject()), methods.get_edited_column, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) EditSelected(force_edit bool) bool { //gd:Tree.edit_selected
	var r_ret = noescape.Call[bool]( gd.ObjectChecked(self.AsObject()), methods.edit_selected, gdextension.SizeBool|(gdextension.SizeBool<<4), &struct{force_edit bool}{force_edit})
	var ret = r_ret
	return ret
}
func (self class) GetCustomPopupRect() Rect2.PositionSize { //gd:Tree.get_custom_popup_rect
	var r_ret = noescape.Call[Rect2.PositionSize]( gd.ObjectChecked(self.AsObject()), methods.get_custom_popup_rect, gdextension.SizeRect2, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) GetItemAreaRect(item [1]gdclass.TreeItem, column int64, button_index int64) Rect2.PositionSize { //gd:Tree.get_item_area_rect
	var r_ret = noescape.Call[Rect2.PositionSize]( gd.ObjectChecked(self.AsObject()), methods.get_item_area_rect, gdextension.SizeRect2|(gdextension.SizeObject<<4)|(gdextension.SizeInt<<8)|(gdextension.SizeInt<<12), &struct{item gdextension.Object; column int64; button_index int64}{	gdextension.Object(gdreference.GetObject(gdclass.GetTreeItem(item[0])[0])), column, button_index})
	var ret = r_ret
	return ret
}
func (self class) GetItemAtPosition(position Vector2.XY) [1]gdclass.TreeItem { //gd:Tree.get_item_at_position
	var r_ret = noescape.Call[gdextension.Object]( gd.ObjectChecked(self.AsObject()), methods.get_item_at_position, gdextension.SizeObject|(gdextension.SizeVector2<<4), &struct{position Vector2.XY}{position})
	var ret = [1]gdclass.TreeItem{gdclass.NewTreeItem(gdreference.LetObject(r_ret))}
	return ret
}
func (self class) GetColumnAtPosition(position Vector2.XY) int64 { //gd:Tree.get_column_at_position
	var r_ret = noescape.Call[int64]( gd.ObjectChecked(self.AsObject()), methods.get_column_at_position, gdextension.SizeInt|(gdextension.SizeVector2<<4), &struct{position Vector2.XY}{position})
	var ret = r_ret
	return ret
}
func (self class) GetDropSectionAtPosition(position Vector2.XY) int64 { //gd:Tree.get_drop_section_at_position
	var r_ret = noescape.Call[int64]( gd.ObjectChecked(self.AsObject()), methods.get_drop_section_at_position, gdextension.SizeInt|(gdextension.SizeVector2<<4), &struct{position Vector2.XY}{position})
	var ret = r_ret
	return ret
}
func (self class) GetButtonIdAtPosition(position Vector2.XY) int64 { //gd:Tree.get_button_id_at_position
	var r_ret = noescape.Call[int64]( gd.ObjectChecked(self.AsObject()), methods.get_button_id_at_position, gdextension.SizeInt|(gdextension.SizeVector2<<4), &struct{position Vector2.XY}{position})
	var ret = r_ret
	return ret
}
func (self class) EnsureCursorIsVisible()  { //gd:Tree.ensure_cursor_is_visible
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.ensure_cursor_is_visible, 0, &struct{}{})
}
func (self class) SetColumnTitlesVisible(visible bool)  { //gd:Tree.set_column_titles_visible
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_column_titles_visible, 0|(gdextension.SizeBool<<4), &struct{visible bool}{visible})
}
func (self class) AreColumnTitlesVisible() bool { //gd:Tree.are_column_titles_visible
	var r_ret = noescape.Call[bool]( gd.ObjectChecked(self.AsObject()), methods.are_column_titles_visible, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetColumnTitle(column int64, title String.Readable)  { //gd:Tree.set_column_title
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_column_title, 0|(gdextension.SizeInt<<4)|(gdextension.SizeString<<8), &struct{column int64; title gdextension.String}{column, pointers.Get(gd.InternalString(title))})
}
func (self class) GetColumnTitle(column int64) String.Readable { //gd:Tree.get_column_title
	var r_ret = noescape.Call[gdextension.String]( gd.ObjectChecked(self.AsObject()), methods.get_column_title, gdextension.SizeString|(gdextension.SizeInt<<4), &struct{column int64}{column})
	var ret = String.Via(gd.StringProxy{}, pointers.Pack(pointers.New[gd.String](r_ret)))
	return ret
}
func (self class) SetColumnTitleTooltipText(column int64, tooltip_text String.Readable)  { //gd:Tree.set_column_title_tooltip_text
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_column_title_tooltip_text, 0|(gdextension.SizeInt<<4)|(gdextension.SizeString<<8), &struct{column int64; tooltip_text gdextension.String}{column, pointers.Get(gd.InternalString(tooltip_text))})
}
func (self class) GetColumnTitleTooltipText(column int64) String.Readable { //gd:Tree.get_column_title_tooltip_text
	var r_ret = noescape.Call[gdextension.String]( gd.ObjectChecked(self.AsObject()), methods.get_column_title_tooltip_text, gdextension.SizeString|(gdextension.SizeInt<<4), &struct{column int64}{column})
	var ret = String.Via(gd.StringProxy{}, pointers.Pack(pointers.New[gd.String](r_ret)))
	return ret
}
func (self class) SetColumnTitleAlignment(column int64, title_alignment GUI.HorizontalAlignment)  { //gd:Tree.set_column_title_alignment
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_column_title_alignment, 0|(gdextension.SizeInt<<4)|(gdextension.SizeInt<<8), &struct{column int64; title_alignment GUI.HorizontalAlignment}{column, title_alignment})
}
func (self class) GetColumnTitleAlignment(column int64) GUI.HorizontalAlignment { //gd:Tree.get_column_title_alignment
	var r_ret = noescape.Call[GUI.HorizontalAlignment]( gd.ObjectChecked(self.AsObject()), methods.get_column_title_alignment, gdextension.SizeInt|(gdextension.SizeInt<<4), &struct{column int64}{column})
	var ret = r_ret
	return ret
}
func (self class) SetColumnTitleDirection(column int64, direction Control.TextDirection)  { //gd:Tree.set_column_title_direction
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_column_title_direction, 0|(gdextension.SizeInt<<4)|(gdextension.SizeInt<<8), &struct{column int64; direction Control.TextDirection}{column, direction})
}
func (self class) GetColumnTitleDirection(column int64) Control.TextDirection { //gd:Tree.get_column_title_direction
	var r_ret = noescape.Call[Control.TextDirection]( gd.ObjectChecked(self.AsObject()), methods.get_column_title_direction, gdextension.SizeInt|(gdextension.SizeInt<<4), &struct{column int64}{column})
	var ret = r_ret
	return ret
}
func (self class) SetColumnTitleLanguage(column int64, language String.Readable)  { //gd:Tree.set_column_title_language
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_column_title_language, 0|(gdextension.SizeInt<<4)|(gdextension.SizeString<<8), &struct{column int64; language gdextension.String}{column, pointers.Get(gd.InternalString(language))})
}
func (self class) GetColumnTitleLanguage(column int64) String.Readable { //gd:Tree.get_column_title_language
	var r_ret = noescape.Call[gdextension.String]( gd.ObjectChecked(self.AsObject()), methods.get_column_title_language, gdextension.SizeString|(gdextension.SizeInt<<4), &struct{column int64}{column})
	var ret = String.Via(gd.StringProxy{}, pointers.Pack(pointers.New[gd.String](r_ret)))
	return ret
}
func (self class) GetScroll() Vector2.XY { //gd:Tree.get_scroll
	var r_ret = noescape.Call[Vector2.XY]( gd.ObjectChecked(self.AsObject()), methods.get_scroll, gdextension.SizeVector2, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) ScrollToItem(item [1]gdclass.TreeItem, center_on_item bool)  { //gd:Tree.scroll_to_item
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.scroll_to_item, 0|(gdextension.SizeObject<<4)|(gdextension.SizeBool<<8), &struct{item gdextension.Object; center_on_item bool}{	gdextension.Object(gdreference.GetObject(gdclass.GetTreeItem(item[0])[0])), center_on_item})
}
func (self class) SetHScrollEnabled(h_scroll bool)  { //gd:Tree.set_h_scroll_enabled
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_h_scroll_enabled, 0|(gdextension.SizeBool<<4), &struct{h_scroll bool}{h_scroll})
}
func (self class) IsHScrollEnabled() bool { //gd:Tree.is_h_scroll_enabled
	var r_ret = noescape.Call[bool]( gd.ObjectChecked(self.AsObject()), methods.is_h_scroll_enabled, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetVScrollEnabled(h_scroll bool)  { //gd:Tree.set_v_scroll_enabled
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_v_scroll_enabled, 0|(gdextension.SizeBool<<4), &struct{h_scroll bool}{h_scroll})
}
func (self class) IsVScrollEnabled() bool { //gd:Tree.is_v_scroll_enabled
	var r_ret = noescape.Call[bool]( gd.ObjectChecked(self.AsObject()), methods.is_v_scroll_enabled, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetScrollHintMode(scroll_hint_mode ScrollHintMode)  { //gd:Tree.set_scroll_hint_mode
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_scroll_hint_mode, 0|(gdextension.SizeInt<<4), &struct{scroll_hint_mode ScrollHintMode}{scroll_hint_mode})
}
func (self class) GetScrollHintMode() ScrollHintMode { //gd:Tree.get_scroll_hint_mode
	var r_ret = noescape.Call[ScrollHintMode]( gd.ObjectChecked(self.AsObject()), methods.get_scroll_hint_mode, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetTileScrollHint(tile_scroll_hint bool)  { //gd:Tree.set_tile_scroll_hint
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_tile_scroll_hint, 0|(gdextension.SizeBool<<4), &struct{tile_scroll_hint bool}{tile_scroll_hint})
}
func (self class) IsScrollHintTiled() bool { //gd:Tree.is_scroll_hint_tiled
	var r_ret = noescape.Call[bool]( gd.ObjectChecked(self.AsObject()), methods.is_scroll_hint_tiled, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetHideFolding(hide bool)  { //gd:Tree.set_hide_folding
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_hide_folding, 0|(gdextension.SizeBool<<4), &struct{hide bool}{hide})
}
func (self class) IsFoldingHidden() bool { //gd:Tree.is_folding_hidden
	var r_ret = noescape.Call[bool]( gd.ObjectChecked(self.AsObject()), methods.is_folding_hidden, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetEnableRecursiveFolding(enable bool)  { //gd:Tree.set_enable_recursive_folding
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_enable_recursive_folding, 0|(gdextension.SizeBool<<4), &struct{enable bool}{enable})
}
func (self class) IsRecursiveFoldingEnabled() bool { //gd:Tree.is_recursive_folding_enabled
	var r_ret = noescape.Call[bool]( gd.ObjectChecked(self.AsObject()), methods.is_recursive_folding_enabled, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetEnableDragUnfolding(enable bool)  { //gd:Tree.set_enable_drag_unfolding
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_enable_drag_unfolding, 0|(gdextension.SizeBool<<4), &struct{enable bool}{enable})
}
func (self class) IsDragUnfoldingEnabled() bool { //gd:Tree.is_drag_unfolding_enabled
	var r_ret = noescape.Call[bool]( gd.ObjectChecked(self.AsObject()), methods.is_drag_unfolding_enabled, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetDropModeFlags(flags int64)  { //gd:Tree.set_drop_mode_flags
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_drop_mode_flags, 0|(gdextension.SizeInt<<4), &struct{flags int64}{flags})
}
func (self class) GetDropModeFlags() int64 { //gd:Tree.get_drop_mode_flags
	var r_ret = noescape.Call[int64]( gd.ObjectChecked(self.AsObject()), methods.get_drop_mode_flags, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetAllowRmbSelect(allow bool)  { //gd:Tree.set_allow_rmb_select
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_allow_rmb_select, 0|(gdextension.SizeBool<<4), &struct{allow bool}{allow})
}
func (self class) GetAllowRmbSelect() bool { //gd:Tree.get_allow_rmb_select
	var r_ret = noescape.Call[bool]( gd.ObjectChecked(self.AsObject()), methods.get_allow_rmb_select, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetAllowReselect(allow bool)  { //gd:Tree.set_allow_reselect
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_allow_reselect, 0|(gdextension.SizeBool<<4), &struct{allow bool}{allow})
}
func (self class) GetAllowReselect() bool { //gd:Tree.get_allow_reselect
	var r_ret = noescape.Call[bool]( gd.ObjectChecked(self.AsObject()), methods.get_allow_reselect, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetAllowSearch(allow bool)  { //gd:Tree.set_allow_search
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_allow_search, 0|(gdextension.SizeBool<<4), &struct{allow bool}{allow})
}
func (self class) GetAllowSearch() bool { //gd:Tree.get_allow_search
	var r_ret = noescape.Call[bool]( gd.ObjectChecked(self.AsObject()), methods.get_allow_search, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetAutoTooltip(enable bool)  { //gd:Tree.set_auto_tooltip
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_auto_tooltip, 0|(gdextension.SizeBool<<4), &struct{enable bool}{enable})
}
func (self class) IsAutoTooltipEnabled() bool { //gd:Tree.is_auto_tooltip_enabled
	var r_ret = noescape.Call[bool]( gd.ObjectChecked(self.AsObject()), methods.is_auto_tooltip_enabled, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self Instance) OnItemSelected(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("item_selected"), gd.NewCallable(cb), int64(flags_together))
	return self
}



func (self class) ItemSelected() Signal.Any {
return Signal.Via(gd.SignalProxy{}, pointers.Pack(gd.NewSignalOf(self.AsObject(), gd.NewStringName(`item_selected`))))}

func (self Instance) OnCellSelected(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("cell_selected"), gd.NewCallable(cb), int64(flags_together))
	return self
}



func (self class) CellSelected() Signal.Any {
return Signal.Via(gd.SignalProxy{}, pointers.Pack(gd.NewSignalOf(self.AsObject(), gd.NewStringName(`cell_selected`))))}

func (self Instance) OnMultiSelected(cb func(item TreeItem.Instance, column int, selected bool), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("multi_selected"), gd.NewCallable(cb), int64(flags_together))
	return self
}



func (self class) MultiSelected() Signal.Any {
return Signal.Via(gd.SignalProxy{}, pointers.Pack(gd.NewSignalOf(self.AsObject(), gd.NewStringName(`multi_selected`))))}

func (self Instance) OnItemMouseSelected(cb func(mouse_position Vector2.XY, mouse_button_index int), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("item_mouse_selected"), gd.NewCallable(cb), int64(flags_together))
	return self
}



func (self class) ItemMouseSelected() Signal.Any {
return Signal.Via(gd.SignalProxy{}, pointers.Pack(gd.NewSignalOf(self.AsObject(), gd.NewStringName(`item_mouse_selected`))))}

func (self Instance) OnEmptyClicked(cb func(click_position Vector2.XY, mouse_button_index int), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("empty_clicked"), gd.NewCallable(cb), int64(flags_together))
	return self
}



func (self class) EmptyClicked() Signal.Any {
return Signal.Via(gd.SignalProxy{}, pointers.Pack(gd.NewSignalOf(self.AsObject(), gd.NewStringName(`empty_clicked`))))}

func (self Instance) OnItemEdited(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("item_edited"), gd.NewCallable(cb), int64(flags_together))
	return self
}



func (self class) ItemEdited() Signal.Any {
return Signal.Via(gd.SignalProxy{}, pointers.Pack(gd.NewSignalOf(self.AsObject(), gd.NewStringName(`item_edited`))))}

func (self Instance) OnCustomItemClicked(cb func(mouse_button_index int), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("custom_item_clicked"), gd.NewCallable(cb), int64(flags_together))
	return self
}



func (self class) CustomItemClicked() Signal.Any {
return Signal.Via(gd.SignalProxy{}, pointers.Pack(gd.NewSignalOf(self.AsObject(), gd.NewStringName(`custom_item_clicked`))))}

func (self Instance) OnItemIconDoubleClicked(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("item_icon_double_clicked"), gd.NewCallable(cb), int64(flags_together))
	return self
}



func (self class) ItemIconDoubleClicked() Signal.Any {
return Signal.Via(gd.SignalProxy{}, pointers.Pack(gd.NewSignalOf(self.AsObject(), gd.NewStringName(`item_icon_double_clicked`))))}

func (self Instance) OnItemCollapsed(cb func(item TreeItem.Instance), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("item_collapsed"), gd.NewCallable(cb), int64(flags_together))
	return self
}



func (self class) ItemCollapsed() Signal.Any {
return Signal.Via(gd.SignalProxy{}, pointers.Pack(gd.NewSignalOf(self.AsObject(), gd.NewStringName(`item_collapsed`))))}

func (self Instance) OnCheckPropagatedToItem(cb func(item TreeItem.Instance, column int), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("check_propagated_to_item"), gd.NewCallable(cb), int64(flags_together))
	return self
}



func (self class) CheckPropagatedToItem() Signal.Any {
return Signal.Via(gd.SignalProxy{}, pointers.Pack(gd.NewSignalOf(self.AsObject(), gd.NewStringName(`check_propagated_to_item`))))}

func (self Instance) OnButtonClicked(cb func(item TreeItem.Instance, column int, id int, mouse_button_index int), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("button_clicked"), gd.NewCallable(cb), int64(flags_together))
	return self
}



func (self class) ButtonClicked() Signal.Any {
return Signal.Via(gd.SignalProxy{}, pointers.Pack(gd.NewSignalOf(self.AsObject(), gd.NewStringName(`button_clicked`))))}

func (self Instance) OnCustomPopupEdited(cb func(arrow_clicked bool), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("custom_popup_edited"), gd.NewCallable(cb), int64(flags_together))
	return self
}



func (self class) CustomPopupEdited() Signal.Any {
return Signal.Via(gd.SignalProxy{}, pointers.Pack(gd.NewSignalOf(self.AsObject(), gd.NewStringName(`custom_popup_edited`))))}

func (self Instance) OnItemActivated(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("item_activated"), gd.NewCallable(cb), int64(flags_together))
	return self
}



func (self class) ItemActivated() Signal.Any {
return Signal.Via(gd.SignalProxy{}, pointers.Pack(gd.NewSignalOf(self.AsObject(), gd.NewStringName(`item_activated`))))}

func (self Instance) OnColumnTitleClicked(cb func(column int, mouse_button_index int), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("column_title_clicked"), gd.NewCallable(cb), int64(flags_together))
	return self
}



func (self class) ColumnTitleClicked() Signal.Any {
return Signal.Via(gd.SignalProxy{}, pointers.Pack(gd.NewSignalOf(self.AsObject(), gd.NewStringName(`column_title_clicked`))))}

func (self Instance) OnNothingSelected(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("nothing_selected"), gd.NewCallable(cb), int64(flags_together))
	return self
}



func (self class) NothingSelected() Signal.Any {
return Signal.Via(gd.SignalProxy{}, pointers.Pack(gd.NewSignalOf(self.AsObject(), gd.NewStringName(`nothing_selected`))))}

func (o class) AsTree() Advanced { return Advanced(o) }
func (o Instance) AsTree() Instance { return o }
func (o *Extension[T]) AsTree() Instance { return o.Super() }
func (o class) AsControl() Control.Advanced { return *(*Control.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsControl() Control.Instance { return o.Super().AsControl() }
func (o Instance) AsControl() Control.Instance { return *(*Control.Instance)(ie.As(&o)) }
func (o class) AsCanvasItem() CanvasItem.Advanced { return *(*CanvasItem.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsCanvasItem() CanvasItem.Instance { return o.Super().AsCanvasItem() }
func (o Instance) AsCanvasItem() CanvasItem.Instance { return *(*CanvasItem.Instance)(ie.As(&o)) }
func (o class) AsNode() Node.Advanced { return *(*Node.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsNode() Node.Instance { return o.Super().AsNode() }
func (o Instance) AsNode() Node.Instance { return *(*Node.Instance)(ie.As(&o)) }

// OnResized is promoted from [Control.Instance.OnResized].
func (self Instance) OnResized(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("resized"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnGuiInput is promoted from [Control.Instance.OnGuiInput].
func (self Instance) OnGuiInput(cb func(event InputEvent.Instance), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("gui_input"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnMouseEntered is promoted from [Control.Instance.OnMouseEntered].
func (self Instance) OnMouseEntered(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("mouse_entered"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnMouseExited is promoted from [Control.Instance.OnMouseExited].
func (self Instance) OnMouseExited(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("mouse_exited"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnFocusEntered is promoted from [Control.Instance.OnFocusEntered].
func (self Instance) OnFocusEntered(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("focus_entered"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnFocusExited is promoted from [Control.Instance.OnFocusExited].
func (self Instance) OnFocusExited(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("focus_exited"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnSizeFlagsChanged is promoted from [Control.Instance.OnSizeFlagsChanged].
func (self Instance) OnSizeFlagsChanged(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("size_flags_changed"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnMinimumSizeChanged is promoted from [Control.Instance.OnMinimumSizeChanged].
func (self Instance) OnMinimumSizeChanged(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("minimum_size_changed"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnThemeChanged is promoted from [Control.Instance.OnThemeChanged].
func (self Instance) OnThemeChanged(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("theme_changed"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnDraw is promoted from [CanvasItem.Instance.OnDraw].
func (self Instance) OnDraw(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("draw"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnVisibilityChanged is promoted from [CanvasItem.Instance.OnVisibilityChanged].
func (self Instance) OnVisibilityChanged(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("visibility_changed"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnHidden is promoted from [CanvasItem.Instance.OnHidden].
func (self Instance) OnHidden(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("hidden"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnItemRectChanged is promoted from [CanvasItem.Instance.OnItemRectChanged].
func (self Instance) OnItemRectChanged(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("item_rect_changed"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnReady is promoted from [Node.Instance.OnReady].
func (self Instance) OnReady(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("ready"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnRenamed is promoted from [Node.Instance.OnRenamed].
func (self Instance) OnRenamed(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("renamed"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnTreeEntered is promoted from [Node.Instance.OnTreeEntered].
func (self Instance) OnTreeEntered(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("tree_entered"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnTreeExiting is promoted from [Node.Instance.OnTreeExiting].
func (self Instance) OnTreeExiting(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("tree_exiting"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnTreeExited is promoted from [Node.Instance.OnTreeExited].
func (self Instance) OnTreeExited(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("tree_exited"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnChildEnteredTree is promoted from [Node.Instance.OnChildEnteredTree].
func (self Instance) OnChildEnteredTree(cb func(node Node.Instance), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("child_entered_tree"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnChildExitingTree is promoted from [Node.Instance.OnChildExitingTree].
func (self Instance) OnChildExitingTree(cb func(node Node.Instance), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("child_exiting_tree"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnChildOrderChanged is promoted from [Node.Instance.OnChildOrderChanged].
func (self Instance) OnChildOrderChanged(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("child_order_changed"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnReplacingBy is promoted from [Node.Instance.OnReplacingBy].
func (self Instance) OnReplacingBy(cb func(node Node.Instance), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("replacing_by"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnEditorDescriptionChanged is promoted from [Node.Instance.OnEditorDescriptionChanged].
func (self Instance) OnEditorDescriptionChanged(cb func(node Node.Instance), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("editor_description_changed"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnEditorStateChanged is promoted from [Node.Instance.OnEditorStateChanged].
func (self Instance) OnEditorStateChanged(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("editor_state_changed"), gd.NewCallable(cb), int64(flags_together))
	return self
}

func (self class) Virtual(name string) reflect.Value {
	switch name {
	default: return gd.VirtualByName(Control.Advanced(self.AsControl()), name)
	}
}

func (self Instance) Virtual(name string) reflect.Value {
	switch name {
	default: return gd.VirtualByName(Control.Instance(self.AsControl()), name)
	}
}
func init() {gdclass.Register("Tree", func(ptr gdreference.Object) any { return Instance{gdclass.NewTree(ptr)} })}
type SelectMode int64//gd:Tree.SelectMode

const (
	SelectSingle SelectMode = 0
	SelectRow SelectMode = 1
	SelectMulti SelectMode = 2
)
type DropModeFlags int64//gd:Tree.DropModeFlags

const (
	DropModeDisabled DropModeFlags = 0
	DropModeOnItem DropModeFlags = 1
	DropModeInbetween DropModeFlags = 2
)
type ScrollHintMode int64//gd:Tree.ScrollHintMode

const (
	ScrollHintModeDisabled ScrollHintMode = 0
	ScrollHintModeBoth ScrollHintMode = 1
	ScrollHintModeTop ScrollHintMode = 2
	ScrollHintModeBottom ScrollHintMode = 3
)
