// Code generated by the generate package DO NOT EDIT


package PhysicalBone3D

import "reflect"
import "slices"
import "graphics.gd/internal/pointers"
import "graphics.gd/internal/callframe"
import "graphics.gd/internal/gdextension"
import "graphics.gd/internal/gdreference"
import "graphics.gd/internal/noescape"
import gd "graphics.gd/internal"
import "graphics.gd/internal/gdclass"
import "graphics.gd/internal/ie"
import "graphics.gd/variant"
import "graphics.gd/variant/Angle"
import "graphics.gd/variant/Euler"
import "graphics.gd/variant/Signal"
import "graphics.gd/classdb/CollisionObject3D"
import "graphics.gd/classdb/InputEvent"
import "graphics.gd/classdb/Node"
import "graphics.gd/classdb/Node3D"
import "graphics.gd/classdb/PhysicsBody3D"
import "graphics.gd/classdb/PhysicsDirectBodyState3D"
import "graphics.gd/variant/Array"
import "graphics.gd/variant/Callable"
import "graphics.gd/variant/Dictionary"
import "graphics.gd/variant/Error"
import "graphics.gd/variant/Float"
import "graphics.gd/variant/Object"
import "graphics.gd/variant/Packed"
import "graphics.gd/variant/Path"
import "graphics.gd/variant/RID"
import "graphics.gd/variant/RefCounted"
import "graphics.gd/variant/String"
import "graphics.gd/variant/Transform3D"
import "graphics.gd/variant/Vector3"

var _ Object.ID
type _ gdclass.Node
var _ gd.String
var _ RefCounted.Instance
var _ reflect.Type
var _ callframe.Frame
var _ = pointers.Cycle
var _ = Array.Nil
var _ variant.Any
var _ Callable.Function
var _ Dictionary.Any
var _ RID.Any
var _ noescape.Variant
var _ String.Readable
var _ Path.ToNode
var _ Packed.Bytes
var _ Error.Code
var _ Float.X
var _ Signal.Any
var _ Angle.Radians
var _ Euler.Radians
var _ gdextension.Object
var _ = slices.Delete[[]struct{}, struct{}]

/*
ID is a typed object ID (reference) to an instance of this class, use it to store references to objects with
unknown lifetimes, as an ID will not panic on use if the underlying object has been destroyed.
*/
type ID Object.ID
func (id ID) Instance() (Instance, bool) { return Object.As[Instance](Object.ID(id).Instance()) }
/*
Extension can be embedded in a new struct to create a Go extension of this class.

T must be a type that is embedding this [Extension] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
See [Interface] for methods that can be overridden by T.
*/
type Extension[T gdclass.Interface] struct { gdclass.Extension[T, Instance] }
/*
Singleton can be embedded in a new struct to create a Go singleton extension of the class.

It will become available as a global inside scripts and any any other Go Extension types will
have any *T typed fields filled in to point at this singleton once they have been instantiated.

T must be a type that is embedding this [Singleton] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
See [Interface] for methods that can be overridden by T.
*/
type Singleton[T gdclass.Interface] = Extension[T]
// Instance of the class with convieniently typed arguments and results.
type Instance [1]gdclass.PhysicalBone3D
var otype gdextension.ObjectType
var sname gdextension.StringName
var methods struct {
	apply_central_impulse gdextension.MethodForClass `hash:"3460891852"`
	apply_impulse gdextension.MethodForClass `hash:"2754756483"`
	set_joint_type gdextension.MethodForClass `hash:"2289552604"`
	get_joint_type gdextension.MethodForClass `hash:"931347320"`
	set_joint_offset gdextension.MethodForClass `hash:"2952846383"`
	get_joint_offset gdextension.MethodForClass `hash:"3229777777"`
	set_joint_rotation gdextension.MethodForClass `hash:"3460891852"`
	get_joint_rotation gdextension.MethodForClass `hash:"3360562783"`
	set_body_offset gdextension.MethodForClass `hash:"2952846383"`
	get_body_offset gdextension.MethodForClass `hash:"3229777777"`
	get_simulate_physics gdextension.MethodForClass `hash:"2240911060"`
	is_simulating_physics gdextension.MethodForClass `hash:"2240911060"`
	get_bone_id gdextension.MethodForClass `hash:"3905245786"`
	set_mass gdextension.MethodForClass `hash:"373806689"`
	get_mass gdextension.MethodForClass `hash:"1740695150"`
	set_friction gdextension.MethodForClass `hash:"373806689"`
	get_friction gdextension.MethodForClass `hash:"1740695150"`
	set_bounce gdextension.MethodForClass `hash:"373806689"`
	get_bounce gdextension.MethodForClass `hash:"1740695150"`
	set_gravity_scale gdextension.MethodForClass `hash:"373806689"`
	get_gravity_scale gdextension.MethodForClass `hash:"1740695150"`
	set_linear_damp_mode gdextension.MethodForClass `hash:"1244972221"`
	get_linear_damp_mode gdextension.MethodForClass `hash:"205884699"`
	set_angular_damp_mode gdextension.MethodForClass `hash:"1244972221"`
	get_angular_damp_mode gdextension.MethodForClass `hash:"205884699"`
	set_linear_damp gdextension.MethodForClass `hash:"373806689"`
	get_linear_damp gdextension.MethodForClass `hash:"1740695150"`
	set_angular_damp gdextension.MethodForClass `hash:"373806689"`
	get_angular_damp gdextension.MethodForClass `hash:"1740695150"`
	set_linear_velocity gdextension.MethodForClass `hash:"3460891852"`
	get_linear_velocity gdextension.MethodForClass `hash:"3360562783"`
	set_angular_velocity gdextension.MethodForClass `hash:"3460891852"`
	get_angular_velocity gdextension.MethodForClass `hash:"3360562783"`
	set_use_custom_integrator gdextension.MethodForClass `hash:"2586408642"`
	is_using_custom_integrator gdextension.MethodForClass `hash:"2240911060"`
	set_can_sleep gdextension.MethodForClass `hash:"2586408642"`
	is_able_to_sleep gdextension.MethodForClass `hash:"36873697"`
}
func init() {
	gd.Links = append(gd.Links, func() {
		sname = gdextension.Host.Strings.Intern.UTF8("PhysicalBone3D")
		otype = gdextension.Host.Objects.Type(sname)
		gd.LinkMethods(sname, &methods, false)
		})
	gd.RegisterCleanup(func() {
		noescape.Free(gdextension.TypeStringName, &sname)
	})
}
func (self Instance) ID() ID { return ID(Object.Instance(self.AsObject()).ID()) }
// MoreArgs is a container for [Instance] functions with additional 'optional' arguments.
type MoreArgs [1]gdclass.PhysicalBone3D
type Expanded = MoreArgs
// MoreArgs enables certain functions to be called with additional 'optional' arguments.
func (self Instance) MoreArgs() MoreArgs { return MoreArgs(self) }
// Nil is a nil/null instance of the class. Equivalent to the zero value.
var Nil Instance
type Any interface {
	gd.IsClass
	AsPhysicalBone3D() Instance
}

type Interface interface {
	IntegrateForces(state PhysicsDirectBodyState3D.Instance) 
}
// Implementation implements [Interface] with empty methods.
type Implementation = implementation

type implementation struct{}
func (self implementation) IntegrateForces(state PhysicsDirectBodyState3D.Instance) { 
 }
func (Instance) _integrate_forces(impl func(ptr gdclass.Receiver, state PhysicsDirectBodyState3D.Instance) ) (cb gd.ExtensionClassCallVirtualFunc) {
	return func(class any, p_args, p_back gdextension.Pointer) {
		var state = [1]gdclass.PhysicsDirectBodyState3D{gdclass.NewPhysicsDirectBodyState3D(gdreference.OwnObject(gd.UnsafeGet[gdextension.Object](p_args,0), gd.Free))}

		defer gdreference.EndObject(gdclass.GetPhysicsDirectBodyState3D(state[0])[0])
		self := gdclass.Receiver(reflect.ValueOf(class).UnsafePointer())
impl(self, state)
	}
}
func (self Instance) ApplyCentralImpulse(impulse Vector3.XYZ) { //gd:PhysicalBone3D.apply_central_impulse
	Advanced(self).ApplyCentralImpulse(Vector3.XYZ(impulse))
}
func (self Instance) ApplyImpulse(impulse Vector3.XYZ) { //gd:PhysicalBone3D.apply_impulse
	Advanced(self).ApplyImpulse(Vector3.XYZ(impulse), Vector3.XYZ(gd.Vector3{0, 0, 0}))
}
func (self MoreArgs) ApplyImpulse(impulse Vector3.XYZ, position Vector3.XYZ) { //gd:PhysicalBone3D.apply_impulse
	Advanced(self).ApplyImpulse(Vector3.XYZ(impulse), Vector3.XYZ(position))
}
func (self Instance) GetSimulatePhysics() bool { //gd:PhysicalBone3D.get_simulate_physics
	return bool(Advanced(self).GetSimulatePhysics())
}
func (self Instance) IsSimulatingPhysics() bool { //gd:PhysicalBone3D.is_simulating_physics
	return bool(Advanced(self).IsSimulatingPhysics())
}
func (self Instance) GetBoneId() int { //gd:PhysicalBone3D.get_bone_id
	return int(int(Advanced(self).GetBoneId()))
}
// Advanced exposes a 1:1 low-level instance of the class, undocumented, for those who know what they are doing.
type Advanced = class
type class [1]gdclass.PhysicalBone3D
func (o class) AsObject() [1]gdreference.Object { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (self *class) SetObject(obj [1]gdreference.Object) bool {
	if gdextension.Host.Objects.Cast(gdreference.GetObject(obj[0]), otype) != 0 {
		self[0] = gdclass.NewPhysicalBone3D(obj[0])
		return true
	}
	return false
}
func (self *Instance) SetObject(obj [1]gdreference.Object) bool {
	if gdextension.Host.Objects.Cast(gdreference.GetObject(obj[0]), otype) != 0 {
		self[0] = gdclass.NewPhysicalBone3D(obj[0])
		return true
	}
	return false
}
func (o Instance) AsObject() [1]gdreference.Object { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (o *Extension[T]) AsObject() [1]gdreference.Object { return o.Super().AsObject() }
func New() Instance {
if !gd.Linked {
		var placeholder = Instance([1]gdclass.PhysicalBone3D{gdclass.NewPhysicalBone3D(gdreference.NewObject())})
		gd.StartupFunctions = append(gd.StartupFunctions, func() {
			if gd.Linked {
				raw, _ := gdreference.EndObject(New().AsObject()[0])
				gdreference.SetObject(gdclass.GetPhysicalBone3D(placeholder[0])[0], raw)
				gd.RegisterCleanup(func() {
					if raw := gdreference.GetObject(placeholder.AsObject()[0]); raw != 0 {
						gdextension.Host.Objects.Unsafe.Free(raw)
					}
				})
			}
		})
		return placeholder
	}
	casted := Instance([1]gdclass.PhysicalBone3D{gdclass.NewPhysicalBone3D(gdreference.OwnObject(gdextension.Host.Objects.Make(sname), gd.Free))})
	gd.ObjectNotification(casted.AsObject()[0], 0, false)
	return casted
}

func (self Instance) JointType() JointType { //gd:PhysicalBone3D.joint_type
		return JointType(class(self).GetJointType())
}

// SetJointType sets the property returned by [GetJointType]. Returns the instance, so that property settings can be chained.
func (self Instance) SetJointType(value JointType) Instance { //gd:PhysicalBone3D.joint_type
	class(self).SetJointType(value)
	return self
}

func (self Instance) JointOffset() Transform3D.BasisOrigin { //gd:PhysicalBone3D.joint_offset
		return Transform3D.BasisOrigin(class(self).GetJointOffset())
}

// SetJointOffset sets the property returned by [GetJointOffset]. Returns the instance, so that property settings can be chained.
func (self Instance) SetJointOffset(value Transform3D.BasisOrigin) Instance { //gd:PhysicalBone3D.joint_offset
	class(self).SetJointOffset(Transform3D.BasisOrigin(value))
	return self
}

func (self Instance) JointRotation() Vector3.XYZ { //gd:PhysicalBone3D.joint_rotation
		return Vector3.XYZ(class(self).GetJointRotation())
}

// SetJointRotation sets the property returned by [GetJointRotation]. Returns the instance, so that property settings can be chained.
func (self Instance) SetJointRotation(value Vector3.XYZ) Instance { //gd:PhysicalBone3D.joint_rotation
	class(self).SetJointRotation(Vector3.XYZ(value))
	return self
}

func (self Instance) BodyOffset() Transform3D.BasisOrigin { //gd:PhysicalBone3D.body_offset
		return Transform3D.BasisOrigin(class(self).GetBodyOffset())
}

// SetBodyOffset sets the property returned by [GetBodyOffset]. Returns the instance, so that property settings can be chained.
func (self Instance) SetBodyOffset(value Transform3D.BasisOrigin) Instance { //gd:PhysicalBone3D.body_offset
	class(self).SetBodyOffset(Transform3D.BasisOrigin(value))
	return self
}

func (self Instance) Mass() Float.X { //gd:PhysicalBone3D.mass
		return Float.X(Float.X(class(self).GetMass()))
}

// SetMass sets the property returned by [GetMass]. Returns the instance, so that property settings can be chained.
func (self Instance) SetMass(value Float.X) Instance { //gd:PhysicalBone3D.mass
	class(self).SetMass(float64(value))
	return self
}

func (self Instance) Friction() Float.X { //gd:PhysicalBone3D.friction
		return Float.X(Float.X(class(self).GetFriction()))
}

// SetFriction sets the property returned by [GetFriction]. Returns the instance, so that property settings can be chained.
func (self Instance) SetFriction(value Float.X) Instance { //gd:PhysicalBone3D.friction
	class(self).SetFriction(float64(value))
	return self
}

func (self Instance) Bounce() Float.X { //gd:PhysicalBone3D.bounce
		return Float.X(Float.X(class(self).GetBounce()))
}

// SetBounce sets the property returned by [GetBounce]. Returns the instance, so that property settings can be chained.
func (self Instance) SetBounce(value Float.X) Instance { //gd:PhysicalBone3D.bounce
	class(self).SetBounce(float64(value))
	return self
}

func (self Instance) GravityScale() Float.X { //gd:PhysicalBone3D.gravity_scale
		return Float.X(Float.X(class(self).GetGravityScale()))
}

// SetGravityScale sets the property returned by [GetGravityScale]. Returns the instance, so that property settings can be chained.
func (self Instance) SetGravityScale(value Float.X) Instance { //gd:PhysicalBone3D.gravity_scale
	class(self).SetGravityScale(float64(value))
	return self
}

func (self Instance) CustomIntegrator() bool { //gd:PhysicalBone3D.custom_integrator
		return bool(class(self).IsUsingCustomIntegrator())
}

// SetCustomIntegrator sets the property returned by [IsUsingCustomIntegrator]. Returns the instance, so that property settings can be chained.
func (self Instance) SetCustomIntegrator(value bool) Instance { //gd:PhysicalBone3D.custom_integrator
	class(self).SetUseCustomIntegrator(value)
	return self
}

func (self Instance) LinearDampMode() DampMode { //gd:PhysicalBone3D.linear_damp_mode
		return DampMode(class(self).GetLinearDampMode())
}

// SetLinearDampMode sets the property returned by [GetLinearDampMode]. Returns the instance, so that property settings can be chained.
func (self Instance) SetLinearDampMode(value DampMode) Instance { //gd:PhysicalBone3D.linear_damp_mode
	class(self).SetLinearDampMode(value)
	return self
}

func (self Instance) LinearDamp() Float.X { //gd:PhysicalBone3D.linear_damp
		return Float.X(Float.X(class(self).GetLinearDamp()))
}

// SetLinearDamp sets the property returned by [GetLinearDamp]. Returns the instance, so that property settings can be chained.
func (self Instance) SetLinearDamp(value Float.X) Instance { //gd:PhysicalBone3D.linear_damp
	class(self).SetLinearDamp(float64(value))
	return self
}

func (self Instance) AngularDampMode() DampMode { //gd:PhysicalBone3D.angular_damp_mode
		return DampMode(class(self).GetAngularDampMode())
}

// SetAngularDampMode sets the property returned by [GetAngularDampMode]. Returns the instance, so that property settings can be chained.
func (self Instance) SetAngularDampMode(value DampMode) Instance { //gd:PhysicalBone3D.angular_damp_mode
	class(self).SetAngularDampMode(value)
	return self
}

func (self Instance) AngularDamp() Float.X { //gd:PhysicalBone3D.angular_damp
		return Float.X(Float.X(class(self).GetAngularDamp()))
}

// SetAngularDamp sets the property returned by [GetAngularDamp]. Returns the instance, so that property settings can be chained.
func (self Instance) SetAngularDamp(value Float.X) Instance { //gd:PhysicalBone3D.angular_damp
	class(self).SetAngularDamp(float64(value))
	return self
}

func (self Instance) LinearVelocity() Vector3.XYZ { //gd:PhysicalBone3D.linear_velocity
		return Vector3.XYZ(class(self).GetLinearVelocity())
}

// SetLinearVelocity sets the property returned by [GetLinearVelocity]. Returns the instance, so that property settings can be chained.
func (self Instance) SetLinearVelocity(value Vector3.XYZ) Instance { //gd:PhysicalBone3D.linear_velocity
	class(self).SetLinearVelocity(Vector3.XYZ(value))
	return self
}

func (self Instance) AngularVelocity() Vector3.XYZ { //gd:PhysicalBone3D.angular_velocity
		return Vector3.XYZ(class(self).GetAngularVelocity())
}

// SetAngularVelocity sets the property returned by [GetAngularVelocity]. Returns the instance, so that property settings can be chained.
func (self Instance) SetAngularVelocity(value Vector3.XYZ) Instance { //gd:PhysicalBone3D.angular_velocity
	class(self).SetAngularVelocity(Vector3.XYZ(value))
	return self
}

func (self Instance) CanSleep() bool { //gd:PhysicalBone3D.can_sleep
		return bool(class(self).IsAbleToSleep())
}

// SetCanSleep sets the property returned by [IsAbleToSleep]. Returns the instance, so that property settings can be chained.
func (self Instance) SetCanSleep(value bool) Instance { //gd:PhysicalBone3D.can_sleep
	class(self).SetCanSleep(value)
	return self
}
func (class) _integrate_forces(impl func(ptr gdclass.Receiver, state [1]gdclass.PhysicsDirectBodyState3D) ) (cb gd.ExtensionClassCallVirtualFunc) {
	return func(class any, p_args, p_back gdextension.Pointer) {
		var state = [1]gdclass.PhysicsDirectBodyState3D{gdclass.NewPhysicsDirectBodyState3D(gdreference.OwnObject(gd.UnsafeGet[gdextension.Object](p_args,0), gd.Free))}

		defer gdreference.EndObject(gdclass.GetPhysicsDirectBodyState3D(state[0])[0])
		self := gdclass.Receiver(reflect.ValueOf(class).UnsafePointer())
impl(self, state)
	}
}

func (self class) ApplyCentralImpulse(impulse Vector3.XYZ)  { //gd:PhysicalBone3D.apply_central_impulse
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.apply_central_impulse, 0|(gdextension.SizeVector3<<4), &struct{impulse Vector3.XYZ}{impulse})
}
func (self class) ApplyImpulse(impulse Vector3.XYZ, position Vector3.XYZ)  { //gd:PhysicalBone3D.apply_impulse
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.apply_impulse, 0|(gdextension.SizeVector3<<4)|(gdextension.SizeVector3<<8), &struct{impulse Vector3.XYZ; position Vector3.XYZ}{impulse, position})
}
func (self class) SetJointType(joint_type JointType)  { //gd:PhysicalBone3D.set_joint_type
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_joint_type, 0|(gdextension.SizeInt<<4), &struct{joint_type JointType}{joint_type})
}
func (self class) GetJointType() JointType { //gd:PhysicalBone3D.get_joint_type
	var r_ret = noescape.Call[JointType]( gd.ObjectChecked(self.AsObject()), methods.get_joint_type, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetJointOffset(offset Transform3D.BasisOrigin)  { //gd:PhysicalBone3D.set_joint_offset
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_joint_offset, 0|(gdextension.SizeTransform3D<<4), &struct{offset Transform3D.BasisOrigin}{gd.Transposed(offset)})
}
func (self class) GetJointOffset() Transform3D.BasisOrigin { //gd:PhysicalBone3D.get_joint_offset
	var r_ret = noescape.Call[Transform3D.BasisOrigin]( gd.ObjectChecked(self.AsObject()), methods.get_joint_offset, gdextension.SizeTransform3D, &struct{}{})
	var ret = gd.Transposed(r_ret)
	return ret
}
func (self class) SetJointRotation(euler Vector3.XYZ)  { //gd:PhysicalBone3D.set_joint_rotation
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_joint_rotation, 0|(gdextension.SizeVector3<<4), &struct{euler Vector3.XYZ}{euler})
}
func (self class) GetJointRotation() Vector3.XYZ { //gd:PhysicalBone3D.get_joint_rotation
	var r_ret = noescape.Call[Vector3.XYZ]( gd.ObjectChecked(self.AsObject()), methods.get_joint_rotation, gdextension.SizeVector3, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetBodyOffset(offset Transform3D.BasisOrigin)  { //gd:PhysicalBone3D.set_body_offset
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_body_offset, 0|(gdextension.SizeTransform3D<<4), &struct{offset Transform3D.BasisOrigin}{gd.Transposed(offset)})
}
func (self class) GetBodyOffset() Transform3D.BasisOrigin { //gd:PhysicalBone3D.get_body_offset
	var r_ret = noescape.Call[Transform3D.BasisOrigin]( gd.ObjectChecked(self.AsObject()), methods.get_body_offset, gdextension.SizeTransform3D, &struct{}{})
	var ret = gd.Transposed(r_ret)
	return ret
}
func (self class) GetSimulatePhysics() bool { //gd:PhysicalBone3D.get_simulate_physics
	var r_ret = noescape.Call[bool]( gd.ObjectChecked(self.AsObject()), methods.get_simulate_physics, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) IsSimulatingPhysics() bool { //gd:PhysicalBone3D.is_simulating_physics
	var r_ret = noescape.Call[bool]( gd.ObjectChecked(self.AsObject()), methods.is_simulating_physics, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) GetBoneId() int64 { //gd:PhysicalBone3D.get_bone_id
	var r_ret = noescape.Call[int64]( gd.ObjectChecked(self.AsObject()), methods.get_bone_id, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetMass(mass float64)  { //gd:PhysicalBone3D.set_mass
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_mass, 0|(gdextension.SizeFloat<<4), &struct{mass float64}{mass})
}
func (self class) GetMass() float64 { //gd:PhysicalBone3D.get_mass
	var r_ret = noescape.Call[float64]( gd.ObjectChecked(self.AsObject()), methods.get_mass, gdextension.SizeFloat, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetFriction(friction float64)  { //gd:PhysicalBone3D.set_friction
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_friction, 0|(gdextension.SizeFloat<<4), &struct{friction float64}{friction})
}
func (self class) GetFriction() float64 { //gd:PhysicalBone3D.get_friction
	var r_ret = noescape.Call[float64]( gd.ObjectChecked(self.AsObject()), methods.get_friction, gdextension.SizeFloat, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetBounce(bounce float64)  { //gd:PhysicalBone3D.set_bounce
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_bounce, 0|(gdextension.SizeFloat<<4), &struct{bounce float64}{bounce})
}
func (self class) GetBounce() float64 { //gd:PhysicalBone3D.get_bounce
	var r_ret = noescape.Call[float64]( gd.ObjectChecked(self.AsObject()), methods.get_bounce, gdextension.SizeFloat, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetGravityScale(gravity_scale float64)  { //gd:PhysicalBone3D.set_gravity_scale
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_gravity_scale, 0|(gdextension.SizeFloat<<4), &struct{gravity_scale float64}{gravity_scale})
}
func (self class) GetGravityScale() float64 { //gd:PhysicalBone3D.get_gravity_scale
	var r_ret = noescape.Call[float64]( gd.ObjectChecked(self.AsObject()), methods.get_gravity_scale, gdextension.SizeFloat, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetLinearDampMode(linear_damp_mode DampMode)  { //gd:PhysicalBone3D.set_linear_damp_mode
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_linear_damp_mode, 0|(gdextension.SizeInt<<4), &struct{linear_damp_mode DampMode}{linear_damp_mode})
}
func (self class) GetLinearDampMode() DampMode { //gd:PhysicalBone3D.get_linear_damp_mode
	var r_ret = noescape.Call[DampMode]( gd.ObjectChecked(self.AsObject()), methods.get_linear_damp_mode, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetAngularDampMode(angular_damp_mode DampMode)  { //gd:PhysicalBone3D.set_angular_damp_mode
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_angular_damp_mode, 0|(gdextension.SizeInt<<4), &struct{angular_damp_mode DampMode}{angular_damp_mode})
}
func (self class) GetAngularDampMode() DampMode { //gd:PhysicalBone3D.get_angular_damp_mode
	var r_ret = noescape.Call[DampMode]( gd.ObjectChecked(self.AsObject()), methods.get_angular_damp_mode, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetLinearDamp(linear_damp float64)  { //gd:PhysicalBone3D.set_linear_damp
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_linear_damp, 0|(gdextension.SizeFloat<<4), &struct{linear_damp float64}{linear_damp})
}
func (self class) GetLinearDamp() float64 { //gd:PhysicalBone3D.get_linear_damp
	var r_ret = noescape.Call[float64]( gd.ObjectChecked(self.AsObject()), methods.get_linear_damp, gdextension.SizeFloat, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetAngularDamp(angular_damp float64)  { //gd:PhysicalBone3D.set_angular_damp
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_angular_damp, 0|(gdextension.SizeFloat<<4), &struct{angular_damp float64}{angular_damp})
}
func (self class) GetAngularDamp() float64 { //gd:PhysicalBone3D.get_angular_damp
	var r_ret = noescape.Call[float64]( gd.ObjectChecked(self.AsObject()), methods.get_angular_damp, gdextension.SizeFloat, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetLinearVelocity(linear_velocity Vector3.XYZ)  { //gd:PhysicalBone3D.set_linear_velocity
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_linear_velocity, 0|(gdextension.SizeVector3<<4), &struct{linear_velocity Vector3.XYZ}{linear_velocity})
}
func (self class) GetLinearVelocity() Vector3.XYZ { //gd:PhysicalBone3D.get_linear_velocity
	var r_ret = noescape.Call[Vector3.XYZ]( gd.ObjectChecked(self.AsObject()), methods.get_linear_velocity, gdextension.SizeVector3, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetAngularVelocity(angular_velocity Vector3.XYZ)  { //gd:PhysicalBone3D.set_angular_velocity
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_angular_velocity, 0|(gdextension.SizeVector3<<4), &struct{angular_velocity Vector3.XYZ}{angular_velocity})
}
func (self class) GetAngularVelocity() Vector3.XYZ { //gd:PhysicalBone3D.get_angular_velocity
	var r_ret = noescape.Call[Vector3.XYZ]( gd.ObjectChecked(self.AsObject()), methods.get_angular_velocity, gdextension.SizeVector3, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetUseCustomIntegrator(enable bool)  { //gd:PhysicalBone3D.set_use_custom_integrator
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_use_custom_integrator, 0|(gdextension.SizeBool<<4), &struct{enable bool}{enable})
}
func (self class) IsUsingCustomIntegrator() bool { //gd:PhysicalBone3D.is_using_custom_integrator
	var r_ret = noescape.Call[bool]( gd.ObjectChecked(self.AsObject()), methods.is_using_custom_integrator, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetCanSleep(able_to_sleep bool)  { //gd:PhysicalBone3D.set_can_sleep
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_can_sleep, 0|(gdextension.SizeBool<<4), &struct{able_to_sleep bool}{able_to_sleep})
}
func (self class) IsAbleToSleep() bool { //gd:PhysicalBone3D.is_able_to_sleep
	var r_ret = noescape.Call[bool]( gd.ObjectChecked(self.AsObject()), methods.is_able_to_sleep, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (o class) AsPhysicalBone3D() Advanced { return Advanced(o) }
func (o Instance) AsPhysicalBone3D() Instance { return o }
func (o *Extension[T]) AsPhysicalBone3D() Instance { return o.Super() }
func (o class) AsPhysicsBody3D() PhysicsBody3D.Advanced { return *(*PhysicsBody3D.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsPhysicsBody3D() PhysicsBody3D.Instance { return o.Super().AsPhysicsBody3D() }
func (o Instance) AsPhysicsBody3D() PhysicsBody3D.Instance { return *(*PhysicsBody3D.Instance)(ie.As(&o)) }
func (o class) AsCollisionObject3D() CollisionObject3D.Advanced { return *(*CollisionObject3D.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsCollisionObject3D() CollisionObject3D.Instance { return o.Super().AsCollisionObject3D() }
func (o Instance) AsCollisionObject3D() CollisionObject3D.Instance { return *(*CollisionObject3D.Instance)(ie.As(&o)) }
func (o class) AsNode3D() Node3D.Advanced { return *(*Node3D.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsNode3D() Node3D.Instance { return o.Super().AsNode3D() }
func (o Instance) AsNode3D() Node3D.Instance { return *(*Node3D.Instance)(ie.As(&o)) }
func (o class) AsNode() Node.Advanced { return *(*Node.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsNode() Node.Instance { return o.Super().AsNode() }
func (o Instance) AsNode() Node.Instance { return *(*Node.Instance)(ie.As(&o)) }

// OnInputEvent is promoted from [CollisionObject3D.Instance.OnInputEvent].
func (self Instance) OnInputEvent(cb func(camera Node.Instance, event InputEvent.Instance, event_position Vector3.XYZ, normal Vector3.XYZ, shape_idx int), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("input_event"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnMouseEntered is promoted from [CollisionObject3D.Instance.OnMouseEntered].
func (self Instance) OnMouseEntered(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("mouse_entered"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnMouseExited is promoted from [CollisionObject3D.Instance.OnMouseExited].
func (self Instance) OnMouseExited(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("mouse_exited"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnVisibilityChanged is promoted from [Node3D.Instance.OnVisibilityChanged].
func (self Instance) OnVisibilityChanged(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("visibility_changed"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnReady is promoted from [Node.Instance.OnReady].
func (self Instance) OnReady(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("ready"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnRenamed is promoted from [Node.Instance.OnRenamed].
func (self Instance) OnRenamed(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("renamed"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnTreeEntered is promoted from [Node.Instance.OnTreeEntered].
func (self Instance) OnTreeEntered(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("tree_entered"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnTreeExiting is promoted from [Node.Instance.OnTreeExiting].
func (self Instance) OnTreeExiting(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("tree_exiting"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnTreeExited is promoted from [Node.Instance.OnTreeExited].
func (self Instance) OnTreeExited(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("tree_exited"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnChildEnteredTree is promoted from [Node.Instance.OnChildEnteredTree].
func (self Instance) OnChildEnteredTree(cb func(node Node.Instance), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("child_entered_tree"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnChildExitingTree is promoted from [Node.Instance.OnChildExitingTree].
func (self Instance) OnChildExitingTree(cb func(node Node.Instance), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("child_exiting_tree"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnChildOrderChanged is promoted from [Node.Instance.OnChildOrderChanged].
func (self Instance) OnChildOrderChanged(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("child_order_changed"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnReplacingBy is promoted from [Node.Instance.OnReplacingBy].
func (self Instance) OnReplacingBy(cb func(node Node.Instance), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("replacing_by"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnEditorDescriptionChanged is promoted from [Node.Instance.OnEditorDescriptionChanged].
func (self Instance) OnEditorDescriptionChanged(cb func(node Node.Instance), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("editor_description_changed"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnEditorStateChanged is promoted from [Node.Instance.OnEditorStateChanged].
func (self Instance) OnEditorStateChanged(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("editor_state_changed"), gd.NewCallable(cb), int64(flags_together))
	return self
}

func (self class) Virtual(name string) reflect.Value {
	switch name {
	case "_integrate_forces": return reflect.ValueOf(self._integrate_forces);
	default: return gd.VirtualByName(PhysicsBody3D.Advanced(self.AsPhysicsBody3D()), name)
	}
}

func (self Instance) Virtual(name string) reflect.Value {
	switch name {
	case "_integrate_forces": return reflect.ValueOf(self._integrate_forces);
	default: return gd.VirtualByName(PhysicsBody3D.Instance(self.AsPhysicsBody3D()), name)
	}
}
func init() {gdclass.Register("PhysicalBone3D", func(ptr gdreference.Object) any { return Instance{gdclass.NewPhysicalBone3D(ptr)} })}
type DampMode int64//gd:PhysicalBone3D.DampMode

const (
	DampModeCombine DampMode = 0
	DampModeReplace DampMode = 1
)
type JointType int64//gd:PhysicalBone3D.JointType

const (
	JointTypeNone JointType = 0
	JointTypePin JointType = 1
	JointTypeCone JointType = 2
	JointTypeHinge JointType = 3
	JointTypeSlider JointType = 4
	JointType6dof JointType = 5
)
