// Code generated by the generate package DO NOT EDIT


package Skeleton2D

import "reflect"
import "slices"
import "graphics.gd/internal/pointers"
import "graphics.gd/internal/callframe"
import "graphics.gd/internal/gdextension"
import "graphics.gd/internal/gdreference"
import "graphics.gd/internal/noescape"
import gd "graphics.gd/internal"
import "graphics.gd/internal/gdclass"
import "graphics.gd/internal/ie"
import "graphics.gd/variant"
import "graphics.gd/variant/Angle"
import "graphics.gd/variant/Euler"
import "graphics.gd/variant/Signal"
import "graphics.gd/classdb/Bone2D"
import "graphics.gd/classdb/CanvasItem"
import "graphics.gd/classdb/CanvasLayer"
import "graphics.gd/classdb/InputEvent"
import "graphics.gd/classdb/Material"
import "graphics.gd/classdb/MultiMesh"
import "graphics.gd/classdb/MultiplayerAPI"
import "graphics.gd/classdb/Node"
import "graphics.gd/classdb/Node2D"
import "graphics.gd/classdb/SkeletonModificationStack2D"
import "graphics.gd/classdb/Texture2D"
import "graphics.gd/classdb/Tween"
import "graphics.gd/classdb/World2D"
import "graphics.gd/variant/Array"
import "graphics.gd/variant/Callable"
import "graphics.gd/variant/Color"
import "graphics.gd/variant/Dictionary"
import "graphics.gd/variant/Error"
import "graphics.gd/variant/Float"
import "graphics.gd/variant/Object"
import "graphics.gd/variant/Packed"
import "graphics.gd/variant/Path"
import "graphics.gd/variant/RID"
import "graphics.gd/variant/Rect2"
import "graphics.gd/variant/RefCounted"
import "graphics.gd/variant/String"
import "graphics.gd/variant/Transform2D"
import "graphics.gd/variant/Vector2"

var _ Object.ID
type _ gdclass.Node
var _ gd.String
var _ RefCounted.Instance
var _ reflect.Type
var _ callframe.Frame
var _ = pointers.Cycle
var _ = Array.Nil
var _ variant.Any
var _ Callable.Function
var _ Dictionary.Any
var _ RID.Any
var _ noescape.Variant
var _ String.Readable
var _ Path.ToNode
var _ Packed.Bytes
var _ Error.Code
var _ Float.X
var _ Signal.Any
var _ Angle.Radians
var _ Euler.Radians
var _ gdextension.Object
var _ = slices.Delete[[]struct{}, struct{}]

/*
ID is a typed object ID (reference) to an instance of this class, use it to store references to objects with
unknown lifetimes, as an ID will not panic on use if the underlying object has been destroyed.
*/
type ID Object.ID
func (id ID) Instance() (Instance, bool) { return Object.As[Instance](Object.ID(id).Instance()) }
/*
Extension can be embedded in a new struct to create a Go extension of this class.

T must be a type that is embedding this [Extension] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Extension[T gdclass.Interface] struct { gdclass.Extension[T, Instance] }
/*
Singleton can be embedded in a new struct to create a Go singleton extension of the class.

It will become available as a global inside scripts and any any other Go Extension types will
have any *T typed fields filled in to point at this singleton once they have been instantiated.

T must be a type that is embedding this [Singleton] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Singleton[T gdclass.Interface] = Extension[T]
// Instance of the class with convieniently typed arguments and results.
type Instance [1]gdclass.Skeleton2D
var otype gdextension.ObjectType
var sname gdextension.StringName
var methods struct {
	get_bone_count gdextension.MethodForClass `hash:"3905245786"`
	get_bone gdextension.MethodForClass `hash:"2556267111"`
	get_skeleton gdextension.MethodForClass `hash:"2944877500"`
	set_modification_stack gdextension.MethodForClass `hash:"3907307132"`
	get_modification_stack gdextension.MethodForClass `hash:"2107508396"`
	execute_modifications gdextension.MethodForClass `hash:"1005356550"`
	set_bone_local_pose_override gdextension.MethodForClass `hash:"555457532"`
	get_bone_local_pose_override gdextension.MethodForClass `hash:"2995540667"`
}
func init() {
	gd.Links = append(gd.Links, func() {
		sname = gdextension.Host.Strings.Intern.UTF8("Skeleton2D")
		otype = gdextension.Host.Objects.Type(sname)
		gd.LinkMethods(sname, &methods, false)
		})
	gd.RegisterCleanup(func() {
		noescape.Free(gdextension.TypeStringName, &sname)
	})
}
func (self Instance) ID() ID { return ID(Object.Instance(self.AsObject()).ID()) }
// Nil is a nil/null instance of the class. Equivalent to the zero value.
var Nil Instance
type Any interface {
	gd.IsClass
	AsSkeleton2D() Instance
}
func (self Instance) GetBoneCount() int { //gd:Skeleton2D.get_bone_count
	return int(int(Advanced(self).GetBoneCount()))
}
func (self Instance) GetBone(idx int) Bone2D.Instance { //gd:Skeleton2D.get_bone
	return Bone2D.Instance(Advanced(self).GetBone(int64(idx)))
}
func (self Instance) GetSkeleton() RID.Skeleton { //gd:Skeleton2D.get_skeleton
	return RID.Skeleton(RID.Skeleton(Advanced(self).GetSkeleton()))
}
func (self Instance) SetModificationStack(modification_stack SkeletonModificationStack2D.Instance)  Instance { //gd:Skeleton2D.set_modification_stack
	Advanced(self).SetModificationStack(modification_stack)
	return self
}
func (self Instance) GetModificationStack() SkeletonModificationStack2D.Instance { //gd:Skeleton2D.get_modification_stack
	return SkeletonModificationStack2D.Instance(Advanced(self).GetModificationStack())
}
func (self Instance) ExecuteModifications(delta Float.X, execution_mode int) { //gd:Skeleton2D.execute_modifications
	Advanced(self).ExecuteModifications(float64(delta), int64(execution_mode))
}
func (self Instance) SetBoneLocalPoseOverride(bone_idx int, override_pose Transform2D.OriginXY, strength Float.X, persistent bool)  Instance { //gd:Skeleton2D.set_bone_local_pose_override
	Advanced(self).SetBoneLocalPoseOverride(int64(bone_idx), Transform2D.OriginXY(override_pose), float64(strength), persistent)
	return self
}
func (self Instance) GetBoneLocalPoseOverride(bone_idx int) Transform2D.OriginXY { //gd:Skeleton2D.get_bone_local_pose_override
	return Transform2D.OriginXY(Advanced(self).GetBoneLocalPoseOverride(int64(bone_idx)))
}
func Get(peer SkeletonModificationStack2D.Instance) Instance { //gd:SkeletonModificationStack2D.get_skeleton
	return Instance(SkeletonModificationStack2D.Advanced(peer).GetSkeleton())
}
// Advanced exposes a 1:1 low-level instance of the class, undocumented, for those who know what they are doing.
type Advanced = class
type class [1]gdclass.Skeleton2D
func (o class) AsObject() [1]gdreference.Object { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (self *class) SetObject(obj [1]gdreference.Object) bool {
	if gdextension.Host.Objects.Cast(gdreference.GetObject(obj[0]), otype) != 0 {
		self[0] = gdclass.NewSkeleton2D(obj[0])
		return true
	}
	return false
}
func (self *Instance) SetObject(obj [1]gdreference.Object) bool {
	if gdextension.Host.Objects.Cast(gdreference.GetObject(obj[0]), otype) != 0 {
		self[0] = gdclass.NewSkeleton2D(obj[0])
		return true
	}
	return false
}
func (o Instance) AsObject() [1]gdreference.Object { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (o *Extension[T]) AsObject() [1]gdreference.Object { return o.Super().AsObject() }
func New() Instance {
if !gd.Linked {
		var placeholder = Instance([1]gdclass.Skeleton2D{gdclass.NewSkeleton2D(gdreference.NewObject())})
		gd.StartupFunctions = append(gd.StartupFunctions, func() {
			if gd.Linked {
				raw, _ := gdreference.EndObject(New().AsObject()[0])
				gdreference.SetObject(gdclass.GetSkeleton2D(placeholder[0])[0], raw)
				gd.RegisterCleanup(func() {
					if raw := gdreference.GetObject(placeholder.AsObject()[0]); raw != 0 {
						gdextension.Host.Objects.Unsafe.Free(raw)
					}
				})
			}
		})
		return placeholder
	}
	casted := Instance([1]gdclass.Skeleton2D{gdclass.NewSkeleton2D(gdreference.OwnObject(gdextension.Host.Objects.Make(sname), gd.Free))})
	gd.ObjectNotification(casted.AsObject()[0], 0, false)
	return casted
}

func (self class) GetBoneCount() int64 { //gd:Skeleton2D.get_bone_count
	var r_ret = noescape.Call[int64]( gd.ObjectChecked(self.AsObject()), methods.get_bone_count, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) GetBone(idx int64) [1]gdclass.Bone2D { //gd:Skeleton2D.get_bone
	var r_ret = noescape.Call[gdextension.Object]( gd.ObjectChecked(self.AsObject()), methods.get_bone, gdextension.SizeObject|(gdextension.SizeInt<<4), &struct{idx int64}{idx})
	var ret = [1]gdclass.Bone2D{gdclass.NewBone2D(gdreference.LetObject(r_ret))}
	return ret
}
func (self class) GetSkeleton() RID.Any { //gd:Skeleton2D.get_skeleton
	var r_ret = noescape.Call[RID.Any]( gd.ObjectChecked(self.AsObject()), methods.get_skeleton, gdextension.SizeRID, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetModificationStack(modification_stack [1]gdclass.SkeletonModificationStack2D)  { //gd:Skeleton2D.set_modification_stack
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_modification_stack, 0|(gdextension.SizeObject<<4), &struct{modification_stack gdextension.Object}{	gdextension.Object(gdreference.GetObject(gdclass.GetSkeletonModificationStack2D(modification_stack[0])[0]))})
}
func (self class) GetModificationStack() [1]gdclass.SkeletonModificationStack2D { //gd:Skeleton2D.get_modification_stack
	var r_ret = noescape.Call[gdextension.Object]( gd.ObjectChecked(self.AsObject()), methods.get_modification_stack, gdextension.SizeObject, &struct{}{})
	var ret = [1]gdclass.SkeletonModificationStack2D{gdclass.NewSkeletonModificationStack2D(gd.PointerWithOwnershipTransferredToGo(r_ret))}
	return ret
}
func (self class) ExecuteModifications(delta float64, execution_mode int64)  { //gd:Skeleton2D.execute_modifications
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.execute_modifications, 0|(gdextension.SizeFloat<<4)|(gdextension.SizeInt<<8), &struct{delta float64; execution_mode int64}{delta, execution_mode})
}
func (self class) SetBoneLocalPoseOverride(bone_idx int64, override_pose Transform2D.OriginXY, strength float64, persistent bool)  { //gd:Skeleton2D.set_bone_local_pose_override
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_bone_local_pose_override, 0|(gdextension.SizeInt<<4)|(gdextension.SizeTransform2D<<8)|(gdextension.SizeFloat<<12)|(gdextension.SizeBool<<16), &struct{bone_idx int64; override_pose Transform2D.OriginXY; strength float64; persistent bool}{bone_idx, override_pose, strength, persistent})
}
func (self class) GetBoneLocalPoseOverride(bone_idx int64) Transform2D.OriginXY { //gd:Skeleton2D.get_bone_local_pose_override
	var r_ret = noescape.Call[Transform2D.OriginXY]( gd.ObjectChecked(self.AsObject()), methods.get_bone_local_pose_override, gdextension.SizeTransform2D|(gdextension.SizeInt<<4), &struct{bone_idx int64}{bone_idx})
	var ret = r_ret
	return ret
}
func (self Instance) OnBoneSetupChanged(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("bone_setup_changed"), gd.NewCallable(cb), int64(flags_together))
	return self
}



func (self class) BoneSetupChanged() Signal.Any {
return Signal.Via(gd.SignalProxy{}, pointers.Pack(gd.NewSignalOf(self.AsObject(), gd.NewStringName(`bone_setup_changed`))))}

func (o class) AsSkeleton2D() Advanced { return Advanced(o) }
func (o Instance) AsSkeleton2D() Instance { return o }
func (o *Extension[T]) AsSkeleton2D() Instance { return o.Super() }
func (o class) AsNode2D() Node2D.Advanced { return *(*Node2D.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsNode2D() Node2D.Instance { return o.Super().AsNode2D() }
func (o Instance) AsNode2D() Node2D.Instance { return *(*Node2D.Instance)(ie.As(&o)) }
func (o class) AsCanvasItem() CanvasItem.Advanced { return *(*CanvasItem.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsCanvasItem() CanvasItem.Instance { return o.Super().AsCanvasItem() }
func (o Instance) AsCanvasItem() CanvasItem.Instance { return *(*CanvasItem.Instance)(ie.As(&o)) }
func (o class) AsNode() Node.Advanced { return *(*Node.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsNode() Node.Instance { return o.Super().AsNode() }
func (o Instance) AsNode() Node.Instance { return *(*Node.Instance)(ie.As(&o)) }
func (o *Extension[T]) OnBoneSetupChanged(cb func(), flags ...Signal.Flags) *Extension[T] {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(o.AsObject()[0], gd.NewStringName("bone_setup_changed"), gd.NewCallable(cb), int64(flags_together))
	return o
}

// OnDraw is promoted from [CanvasItem.Instance.OnDraw].
func (self Instance) OnDraw(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("draw"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnDraw is promoted from [CanvasItem.Instance.OnDraw].
func (o *Extension[T]) OnDraw(cb func(), flags ...Signal.Flags) *Extension[T] {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(o.AsObject()[0], gd.NewStringName("draw"), gd.NewCallable(cb), int64(flags_together))
	return o
}

// OnVisibilityChanged is promoted from [CanvasItem.Instance.OnVisibilityChanged].
func (self Instance) OnVisibilityChanged(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("visibility_changed"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnVisibilityChanged is promoted from [CanvasItem.Instance.OnVisibilityChanged].
func (o *Extension[T]) OnVisibilityChanged(cb func(), flags ...Signal.Flags) *Extension[T] {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(o.AsObject()[0], gd.NewStringName("visibility_changed"), gd.NewCallable(cb), int64(flags_together))
	return o
}

// OnHidden is promoted from [CanvasItem.Instance.OnHidden].
func (self Instance) OnHidden(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("hidden"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnHidden is promoted from [CanvasItem.Instance.OnHidden].
func (o *Extension[T]) OnHidden(cb func(), flags ...Signal.Flags) *Extension[T] {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(o.AsObject()[0], gd.NewStringName("hidden"), gd.NewCallable(cb), int64(flags_together))
	return o
}

// OnItemRectChanged is promoted from [CanvasItem.Instance.OnItemRectChanged].
func (self Instance) OnItemRectChanged(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("item_rect_changed"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnItemRectChanged is promoted from [CanvasItem.Instance.OnItemRectChanged].
func (o *Extension[T]) OnItemRectChanged(cb func(), flags ...Signal.Flags) *Extension[T] {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(o.AsObject()[0], gd.NewStringName("item_rect_changed"), gd.NewCallable(cb), int64(flags_together))
	return o
}

// OnReady is promoted from [Node.Instance.OnReady].
func (self Instance) OnReady(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("ready"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnReady is promoted from [Node.Instance.OnReady].
func (o *Extension[T]) OnReady(cb func(), flags ...Signal.Flags) *Extension[T] {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(o.AsObject()[0], gd.NewStringName("ready"), gd.NewCallable(cb), int64(flags_together))
	return o
}

// OnRenamed is promoted from [Node.Instance.OnRenamed].
func (self Instance) OnRenamed(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("renamed"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnRenamed is promoted from [Node.Instance.OnRenamed].
func (o *Extension[T]) OnRenamed(cb func(), flags ...Signal.Flags) *Extension[T] {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(o.AsObject()[0], gd.NewStringName("renamed"), gd.NewCallable(cb), int64(flags_together))
	return o
}

// OnTreeEntered is promoted from [Node.Instance.OnTreeEntered].
func (self Instance) OnTreeEntered(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("tree_entered"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnTreeEntered is promoted from [Node.Instance.OnTreeEntered].
func (o *Extension[T]) OnTreeEntered(cb func(), flags ...Signal.Flags) *Extension[T] {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(o.AsObject()[0], gd.NewStringName("tree_entered"), gd.NewCallable(cb), int64(flags_together))
	return o
}

// OnTreeExiting is promoted from [Node.Instance.OnTreeExiting].
func (self Instance) OnTreeExiting(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("tree_exiting"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnTreeExiting is promoted from [Node.Instance.OnTreeExiting].
func (o *Extension[T]) OnTreeExiting(cb func(), flags ...Signal.Flags) *Extension[T] {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(o.AsObject()[0], gd.NewStringName("tree_exiting"), gd.NewCallable(cb), int64(flags_together))
	return o
}

// OnTreeExited is promoted from [Node.Instance.OnTreeExited].
func (self Instance) OnTreeExited(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("tree_exited"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnTreeExited is promoted from [Node.Instance.OnTreeExited].
func (o *Extension[T]) OnTreeExited(cb func(), flags ...Signal.Flags) *Extension[T] {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(o.AsObject()[0], gd.NewStringName("tree_exited"), gd.NewCallable(cb), int64(flags_together))
	return o
}

// OnChildEnteredTree is promoted from [Node.Instance.OnChildEnteredTree].
func (self Instance) OnChildEnteredTree(cb func(node Node.Instance), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("child_entered_tree"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnChildEnteredTree is promoted from [Node.Instance.OnChildEnteredTree].
func (o *Extension[T]) OnChildEnteredTree(cb func(node Node.Instance), flags ...Signal.Flags) *Extension[T] {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(o.AsObject()[0], gd.NewStringName("child_entered_tree"), gd.NewCallable(cb), int64(flags_together))
	return o
}

// OnChildExitingTree is promoted from [Node.Instance.OnChildExitingTree].
func (self Instance) OnChildExitingTree(cb func(node Node.Instance), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("child_exiting_tree"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnChildExitingTree is promoted from [Node.Instance.OnChildExitingTree].
func (o *Extension[T]) OnChildExitingTree(cb func(node Node.Instance), flags ...Signal.Flags) *Extension[T] {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(o.AsObject()[0], gd.NewStringName("child_exiting_tree"), gd.NewCallable(cb), int64(flags_together))
	return o
}

// OnChildOrderChanged is promoted from [Node.Instance.OnChildOrderChanged].
func (self Instance) OnChildOrderChanged(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("child_order_changed"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnChildOrderChanged is promoted from [Node.Instance.OnChildOrderChanged].
func (o *Extension[T]) OnChildOrderChanged(cb func(), flags ...Signal.Flags) *Extension[T] {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(o.AsObject()[0], gd.NewStringName("child_order_changed"), gd.NewCallable(cb), int64(flags_together))
	return o
}

// OnReplacingBy is promoted from [Node.Instance.OnReplacingBy].
func (self Instance) OnReplacingBy(cb func(node Node.Instance), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("replacing_by"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnReplacingBy is promoted from [Node.Instance.OnReplacingBy].
func (o *Extension[T]) OnReplacingBy(cb func(node Node.Instance), flags ...Signal.Flags) *Extension[T] {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(o.AsObject()[0], gd.NewStringName("replacing_by"), gd.NewCallable(cb), int64(flags_together))
	return o
}

// OnEditorDescriptionChanged is promoted from [Node.Instance.OnEditorDescriptionChanged].
func (self Instance) OnEditorDescriptionChanged(cb func(node Node.Instance), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("editor_description_changed"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnEditorDescriptionChanged is promoted from [Node.Instance.OnEditorDescriptionChanged].
func (o *Extension[T]) OnEditorDescriptionChanged(cb func(node Node.Instance), flags ...Signal.Flags) *Extension[T] {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(o.AsObject()[0], gd.NewStringName("editor_description_changed"), gd.NewCallable(cb), int64(flags_together))
	return o
}

// OnEditorStateChanged is promoted from [Node.Instance.OnEditorStateChanged].
func (self Instance) OnEditorStateChanged(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("editor_state_changed"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnEditorStateChanged is promoted from [Node.Instance.OnEditorStateChanged].
func (o *Extension[T]) OnEditorStateChanged(cb func(), flags ...Signal.Flags) *Extension[T] {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(o.AsObject()[0], gd.NewStringName("editor_state_changed"), gd.NewCallable(cb), int64(flags_together))
	return o
}
func (o *Extension[T]) GetBoneCount() int {
	return o.Super().GetBoneCount()
}
func (o *Extension[T]) GetBone(idx int) Bone2D.Instance {
	return o.Super().GetBone(idx)
}
func (o *Extension[T]) GetSkeleton() RID.Skeleton {
	return o.Super().GetSkeleton()
}
func (o *Extension[T]) SetModificationStack(modification_stack SkeletonModificationStack2D.Instance) *Extension[T] {
	o.Super().SetModificationStack(modification_stack)
	return o
}
func (o *Extension[T]) GetModificationStack() SkeletonModificationStack2D.Instance {
	return o.Super().GetModificationStack()
}
func (o *Extension[T]) ExecuteModifications(delta Float.X, execution_mode int) {
	o.Super().ExecuteModifications(delta, execution_mode)
}
func (o *Extension[T]) SetBoneLocalPoseOverride(bone_idx int, override_pose Transform2D.OriginXY, strength Float.X, persistent bool) *Extension[T] {
	o.Super().SetBoneLocalPoseOverride(bone_idx, override_pose, strength, persistent)
	return o
}
func (o *Extension[T]) GetBoneLocalPoseOverride(bone_idx int) Transform2D.OriginXY {
	return o.Super().GetBoneLocalPoseOverride(bone_idx)
}

// Rotate is promoted from [Node2D.Instance.Rotate].
func (self Instance) Rotate(radians Angle.Radians) {
	self.AsNode2D().Rotate(radians)
}

// Rotate is promoted from [Node2D.Instance.Rotate].
func (o *Extension[T]) Rotate(radians Angle.Radians) {
	o.Super().AsNode2D().Rotate(radians)
}

// Translate is promoted from [Node2D.Instance.Translate].
func (self Instance) Translate(offset Vector2.XY) {
	self.AsNode2D().Translate(offset)
}

// Translate is promoted from [Node2D.Instance.Translate].
func (o *Extension[T]) Translate(offset Vector2.XY) {
	o.Super().AsNode2D().Translate(offset)
}

// GlobalTranslate is promoted from [Node2D.Instance.GlobalTranslate].
func (self Instance) GlobalTranslate(offset Vector2.XY) {
	self.AsNode2D().GlobalTranslate(offset)
}

// GlobalTranslate is promoted from [Node2D.Instance.GlobalTranslate].
func (o *Extension[T]) GlobalTranslate(offset Vector2.XY) {
	o.Super().AsNode2D().GlobalTranslate(offset)
}

// ApplyScale is promoted from [Node2D.Instance.ApplyScale].
func (self Instance) ApplyScale(ratio Vector2.XY) {
	self.AsNode2D().ApplyScale(ratio)
}

// ApplyScale is promoted from [Node2D.Instance.ApplyScale].
func (o *Extension[T]) ApplyScale(ratio Vector2.XY) {
	o.Super().AsNode2D().ApplyScale(ratio)
}

// LookAt is promoted from [Node2D.Instance.LookAt].
func (self Instance) LookAt(point Vector2.XY) {
	self.AsNode2D().LookAt(point)
}

// LookAt is promoted from [Node2D.Instance.LookAt].
func (o *Extension[T]) LookAt(point Vector2.XY) {
	o.Super().AsNode2D().LookAt(point)
}

// GetAngleTo is promoted from [Node2D.Instance.GetAngleTo].
func (self Instance) GetAngleTo(point Vector2.XY) Angle.Radians {
	return self.AsNode2D().GetAngleTo(point)
}

// GetAngleTo is promoted from [Node2D.Instance.GetAngleTo].
func (o *Extension[T]) GetAngleTo(point Vector2.XY) Angle.Radians {
	return o.Super().AsNode2D().GetAngleTo(point)
}

// ToLocal is promoted from [Node2D.Instance.ToLocal].
func (self Instance) ToLocal(global_point Vector2.XY) Vector2.XY {
	return self.AsNode2D().ToLocal(global_point)
}

// ToLocal is promoted from [Node2D.Instance.ToLocal].
func (o *Extension[T]) ToLocal(global_point Vector2.XY) Vector2.XY {
	return o.Super().AsNode2D().ToLocal(global_point)
}

// ToGlobal is promoted from [Node2D.Instance.ToGlobal].
func (self Instance) ToGlobal(local_point Vector2.XY) Vector2.XY {
	return self.AsNode2D().ToGlobal(local_point)
}

// ToGlobal is promoted from [Node2D.Instance.ToGlobal].
func (o *Extension[T]) ToGlobal(local_point Vector2.XY) Vector2.XY {
	return o.Super().AsNode2D().ToGlobal(local_point)
}

// GetRelativeTransformToParent is promoted from [Node2D.Instance.GetRelativeTransformToParent].
func (self Instance) GetRelativeTransformToParent(parent Node.Instance) Transform2D.OriginXY {
	return self.AsNode2D().GetRelativeTransformToParent(parent)
}

// GetRelativeTransformToParent is promoted from [Node2D.Instance.GetRelativeTransformToParent].
func (o *Extension[T]) GetRelativeTransformToParent(parent Node.Instance) Transform2D.OriginXY {
	return o.Super().AsNode2D().GetRelativeTransformToParent(parent)
}

// GetCanvasItem is promoted from [CanvasItem.Instance.GetCanvasItem].
func (self Instance) GetCanvasItem() RID.CanvasItem {
	return self.AsCanvasItem().GetCanvasItem()
}

// GetCanvasItem is promoted from [CanvasItem.Instance.GetCanvasItem].
func (o *Extension[T]) GetCanvasItem() RID.CanvasItem {
	return o.Super().AsCanvasItem().GetCanvasItem()
}

// IsVisibleInTree is promoted from [CanvasItem.Instance.IsVisibleInTree].
func (self Instance) IsVisibleInTree() bool {
	return self.AsCanvasItem().IsVisibleInTree()
}

// IsVisibleInTree is promoted from [CanvasItem.Instance.IsVisibleInTree].
func (o *Extension[T]) IsVisibleInTree() bool {
	return o.Super().AsCanvasItem().IsVisibleInTree()
}

// Show is promoted from [CanvasItem.Instance.Show].
func (self Instance) Show() {
	self.AsCanvasItem().Show()
}

// Show is promoted from [CanvasItem.Instance.Show].
func (o *Extension[T]) Show() {
	o.Super().AsCanvasItem().Show()
}

// Hide is promoted from [CanvasItem.Instance.Hide].
func (self Instance) Hide() {
	self.AsCanvasItem().Hide()
}

// Hide is promoted from [CanvasItem.Instance.Hide].
func (o *Extension[T]) Hide() {
	o.Super().AsCanvasItem().Hide()
}

// QueueRedraw is promoted from [CanvasItem.Instance.QueueRedraw].
func (self Instance) QueueRedraw() {
	self.AsCanvasItem().QueueRedraw()
}

// QueueRedraw is promoted from [CanvasItem.Instance.QueueRedraw].
func (o *Extension[T]) QueueRedraw() {
	o.Super().AsCanvasItem().QueueRedraw()
}

// MoveToFront is promoted from [CanvasItem.Instance.MoveToFront].
func (self Instance) MoveToFront() {
	self.AsCanvasItem().MoveToFront()
}

// MoveToFront is promoted from [CanvasItem.Instance.MoveToFront].
func (o *Extension[T]) MoveToFront() {
	o.Super().AsCanvasItem().MoveToFront()
}

// DrawMultimesh is promoted from [CanvasItem.Instance.DrawMultimesh].
func (self Instance) DrawMultimesh(multimesh MultiMesh.Instance, texture Texture2D.Instance) {
	self.AsCanvasItem().DrawMultimesh(multimesh, texture)
}

// DrawMultimesh is promoted from [CanvasItem.Instance.DrawMultimesh].
func (o *Extension[T]) DrawMultimesh(multimesh MultiMesh.Instance, texture Texture2D.Instance) {
	o.Super().AsCanvasItem().DrawMultimesh(multimesh, texture)
}

// DrawSetTransformMatrix is promoted from [CanvasItem.Instance.DrawSetTransformMatrix].
func (self Instance) DrawSetTransformMatrix(xform Transform2D.OriginXY) {
	self.AsCanvasItem().DrawSetTransformMatrix(xform)
}

// DrawSetTransformMatrix is promoted from [CanvasItem.Instance.DrawSetTransformMatrix].
func (o *Extension[T]) DrawSetTransformMatrix(xform Transform2D.OriginXY) {
	o.Super().AsCanvasItem().DrawSetTransformMatrix(xform)
}

// DrawEndAnimation is promoted from [CanvasItem.Instance.DrawEndAnimation].
func (self Instance) DrawEndAnimation() {
	self.AsCanvasItem().DrawEndAnimation()
}

// DrawEndAnimation is promoted from [CanvasItem.Instance.DrawEndAnimation].
func (o *Extension[T]) DrawEndAnimation() {
	o.Super().AsCanvasItem().DrawEndAnimation()
}

// GetTransform is promoted from [CanvasItem.Instance.GetTransform].
func (self Instance) GetTransform() Transform2D.OriginXY {
	return self.AsCanvasItem().GetTransform()
}

// GetTransform is promoted from [CanvasItem.Instance.GetTransform].
func (o *Extension[T]) GetTransform() Transform2D.OriginXY {
	return o.Super().AsCanvasItem().GetTransform()
}

// GetGlobalTransform is promoted from [CanvasItem.Instance.GetGlobalTransform].
func (self Instance) GetGlobalTransform() Transform2D.OriginXY {
	return self.AsCanvasItem().GetGlobalTransform()
}

// GetGlobalTransform is promoted from [CanvasItem.Instance.GetGlobalTransform].
func (o *Extension[T]) GetGlobalTransform() Transform2D.OriginXY {
	return o.Super().AsCanvasItem().GetGlobalTransform()
}

// GetGlobalTransformWithCanvas is promoted from [CanvasItem.Instance.GetGlobalTransformWithCanvas].
func (self Instance) GetGlobalTransformWithCanvas() Transform2D.OriginXY {
	return self.AsCanvasItem().GetGlobalTransformWithCanvas()
}

// GetGlobalTransformWithCanvas is promoted from [CanvasItem.Instance.GetGlobalTransformWithCanvas].
func (o *Extension[T]) GetGlobalTransformWithCanvas() Transform2D.OriginXY {
	return o.Super().AsCanvasItem().GetGlobalTransformWithCanvas()
}

// GetViewportTransform is promoted from [CanvasItem.Instance.GetViewportTransform].
func (self Instance) GetViewportTransform() Transform2D.OriginXY {
	return self.AsCanvasItem().GetViewportTransform()
}

// GetViewportTransform is promoted from [CanvasItem.Instance.GetViewportTransform].
func (o *Extension[T]) GetViewportTransform() Transform2D.OriginXY {
	return o.Super().AsCanvasItem().GetViewportTransform()
}

// GetViewportRect is promoted from [CanvasItem.Instance.GetViewportRect].
func (self Instance) GetViewportRect() Rect2.PositionSize {
	return self.AsCanvasItem().GetViewportRect()
}

// GetViewportRect is promoted from [CanvasItem.Instance.GetViewportRect].
func (o *Extension[T]) GetViewportRect() Rect2.PositionSize {
	return o.Super().AsCanvasItem().GetViewportRect()
}

// GetCanvasTransform is promoted from [CanvasItem.Instance.GetCanvasTransform].
func (self Instance) GetCanvasTransform() Transform2D.OriginXY {
	return self.AsCanvasItem().GetCanvasTransform()
}

// GetCanvasTransform is promoted from [CanvasItem.Instance.GetCanvasTransform].
func (o *Extension[T]) GetCanvasTransform() Transform2D.OriginXY {
	return o.Super().AsCanvasItem().GetCanvasTransform()
}

// GetScreenTransform is promoted from [CanvasItem.Instance.GetScreenTransform].
func (self Instance) GetScreenTransform() Transform2D.OriginXY {
	return self.AsCanvasItem().GetScreenTransform()
}

// GetScreenTransform is promoted from [CanvasItem.Instance.GetScreenTransform].
func (o *Extension[T]) GetScreenTransform() Transform2D.OriginXY {
	return o.Super().AsCanvasItem().GetScreenTransform()
}

// GetLocalMousePosition is promoted from [CanvasItem.Instance.GetLocalMousePosition].
func (self Instance) GetLocalMousePosition() Vector2.XY {
	return self.AsCanvasItem().GetLocalMousePosition()
}

// GetLocalMousePosition is promoted from [CanvasItem.Instance.GetLocalMousePosition].
func (o *Extension[T]) GetLocalMousePosition() Vector2.XY {
	return o.Super().AsCanvasItem().GetLocalMousePosition()
}

// GetGlobalMousePosition is promoted from [CanvasItem.Instance.GetGlobalMousePosition].
func (self Instance) GetGlobalMousePosition() Vector2.XY {
	return self.AsCanvasItem().GetGlobalMousePosition()
}

// GetGlobalMousePosition is promoted from [CanvasItem.Instance.GetGlobalMousePosition].
func (o *Extension[T]) GetGlobalMousePosition() Vector2.XY {
	return o.Super().AsCanvasItem().GetGlobalMousePosition()
}

// GetCanvas is promoted from [CanvasItem.Instance.GetCanvas].
func (self Instance) GetCanvas() RID.Canvas {
	return self.AsCanvasItem().GetCanvas()
}

// GetCanvas is promoted from [CanvasItem.Instance.GetCanvas].
func (o *Extension[T]) GetCanvas() RID.Canvas {
	return o.Super().AsCanvasItem().GetCanvas()
}

// GetCanvasLayerNode is promoted from [CanvasItem.Instance.GetCanvasLayerNode].
func (self Instance) GetCanvasLayerNode() CanvasLayer.Instance {
	return self.AsCanvasItem().GetCanvasLayerNode()
}

// GetCanvasLayerNode is promoted from [CanvasItem.Instance.GetCanvasLayerNode].
func (o *Extension[T]) GetCanvasLayerNode() CanvasLayer.Instance {
	return o.Super().AsCanvasItem().GetCanvasLayerNode()
}

// GetWorld2d is promoted from [CanvasItem.Instance.GetWorld2d].
func (self Instance) GetWorld2d() World2D.Instance {
	return self.AsCanvasItem().GetWorld2d()
}

// GetWorld2d is promoted from [CanvasItem.Instance.GetWorld2d].
func (o *Extension[T]) GetWorld2d() World2D.Instance {
	return o.Super().AsCanvasItem().GetWorld2d()
}

// SetInstanceShaderParameter is promoted from [CanvasItem.Instance.SetInstanceShaderParameter].
func (self Instance) SetInstanceShaderParameter(name string, value any) Instance {
	self.AsCanvasItem().SetInstanceShaderParameter(name, value)
	return self
}

// SetInstanceShaderParameter is promoted from [CanvasItem.Instance.SetInstanceShaderParameter].
func (o *Extension[T]) SetInstanceShaderParameter(name string, value any) *Extension[T] {
	o.Super().AsCanvasItem().SetInstanceShaderParameter(name, value)
	return o
}

// GetInstanceShaderParameter is promoted from [CanvasItem.Instance.GetInstanceShaderParameter].
func (self Instance) GetInstanceShaderParameter(name string) any {
	return self.AsCanvasItem().GetInstanceShaderParameter(name)
}

// GetInstanceShaderParameter is promoted from [CanvasItem.Instance.GetInstanceShaderParameter].
func (o *Extension[T]) GetInstanceShaderParameter(name string) any {
	return o.Super().AsCanvasItem().GetInstanceShaderParameter(name)
}

// SetNotifyLocalTransform is promoted from [CanvasItem.Instance.SetNotifyLocalTransform].
func (self Instance) SetNotifyLocalTransform(enable bool) Instance {
	self.AsCanvasItem().SetNotifyLocalTransform(enable)
	return self
}

// SetNotifyLocalTransform is promoted from [CanvasItem.Instance.SetNotifyLocalTransform].
func (o *Extension[T]) SetNotifyLocalTransform(enable bool) *Extension[T] {
	o.Super().AsCanvasItem().SetNotifyLocalTransform(enable)
	return o
}

// IsLocalTransformNotificationEnabled is promoted from [CanvasItem.Instance.IsLocalTransformNotificationEnabled].
func (self Instance) IsLocalTransformNotificationEnabled() bool {
	return self.AsCanvasItem().IsLocalTransformNotificationEnabled()
}

// IsLocalTransformNotificationEnabled is promoted from [CanvasItem.Instance.IsLocalTransformNotificationEnabled].
func (o *Extension[T]) IsLocalTransformNotificationEnabled() bool {
	return o.Super().AsCanvasItem().IsLocalTransformNotificationEnabled()
}

// SetNotifyTransform is promoted from [CanvasItem.Instance.SetNotifyTransform].
func (self Instance) SetNotifyTransform(enable bool) Instance {
	self.AsCanvasItem().SetNotifyTransform(enable)
	return self
}

// SetNotifyTransform is promoted from [CanvasItem.Instance.SetNotifyTransform].
func (o *Extension[T]) SetNotifyTransform(enable bool) *Extension[T] {
	o.Super().AsCanvasItem().SetNotifyTransform(enable)
	return o
}

// IsTransformNotificationEnabled is promoted from [CanvasItem.Instance.IsTransformNotificationEnabled].
func (self Instance) IsTransformNotificationEnabled() bool {
	return self.AsCanvasItem().IsTransformNotificationEnabled()
}

// IsTransformNotificationEnabled is promoted from [CanvasItem.Instance.IsTransformNotificationEnabled].
func (o *Extension[T]) IsTransformNotificationEnabled() bool {
	return o.Super().AsCanvasItem().IsTransformNotificationEnabled()
}

// ForceUpdateTransform is promoted from [CanvasItem.Instance.ForceUpdateTransform].
func (self Instance) ForceUpdateTransform() {
	self.AsCanvasItem().ForceUpdateTransform()
}

// ForceUpdateTransform is promoted from [CanvasItem.Instance.ForceUpdateTransform].
func (o *Extension[T]) ForceUpdateTransform() {
	o.Super().AsCanvasItem().ForceUpdateTransform()
}

// MakeCanvasPositionLocal is promoted from [CanvasItem.Instance.MakeCanvasPositionLocal].
func (self Instance) MakeCanvasPositionLocal(viewport_point Vector2.XY) Vector2.XY {
	return self.AsCanvasItem().MakeCanvasPositionLocal(viewport_point)
}

// MakeCanvasPositionLocal is promoted from [CanvasItem.Instance.MakeCanvasPositionLocal].
func (o *Extension[T]) MakeCanvasPositionLocal(viewport_point Vector2.XY) Vector2.XY {
	return o.Super().AsCanvasItem().MakeCanvasPositionLocal(viewport_point)
}

// MakeInputLocal is promoted from [CanvasItem.Instance.MakeInputLocal].
func (self Instance) MakeInputLocal(event InputEvent.Instance) InputEvent.Instance {
	return self.AsCanvasItem().MakeInputLocal(event)
}

// MakeInputLocal is promoted from [CanvasItem.Instance.MakeInputLocal].
func (o *Extension[T]) MakeInputLocal(event InputEvent.Instance) InputEvent.Instance {
	return o.Super().AsCanvasItem().MakeInputLocal(event)
}

// SetVisibilityLayerBit is promoted from [CanvasItem.Instance.SetVisibilityLayerBit].
func (self Instance) SetVisibilityLayerBit(layer int, enabled bool) Instance {
	self.AsCanvasItem().SetVisibilityLayerBit(layer, enabled)
	return self
}

// SetVisibilityLayerBit is promoted from [CanvasItem.Instance.SetVisibilityLayerBit].
func (o *Extension[T]) SetVisibilityLayerBit(layer int, enabled bool) *Extension[T] {
	o.Super().AsCanvasItem().SetVisibilityLayerBit(layer, enabled)
	return o
}

// GetVisibilityLayerBit is promoted from [CanvasItem.Instance.GetVisibilityLayerBit].
func (self Instance) GetVisibilityLayerBit(layer int) bool {
	return self.AsCanvasItem().GetVisibilityLayerBit(layer)
}

// GetVisibilityLayerBit is promoted from [CanvasItem.Instance.GetVisibilityLayerBit].
func (o *Extension[T]) GetVisibilityLayerBit(layer int) bool {
	return o.Super().AsCanvasItem().GetVisibilityLayerBit(layer)
}

// RemoveChild is promoted from [Node.Instance.RemoveChild].
func (self Instance) RemoveChild(node Node.Instance) {
	self.AsNode().RemoveChild(node)
}

// RemoveChild is promoted from [Node.Instance.RemoveChild].
func (o *Extension[T]) RemoveChild(node Node.Instance) {
	o.Super().AsNode().RemoveChild(node)
}

// HasNode is promoted from [Node.Instance.HasNode].
func (self Instance) HasNode(path string) bool {
	return self.AsNode().HasNode(path)
}

// HasNode is promoted from [Node.Instance.HasNode].
func (o *Extension[T]) HasNode(path string) bool {
	return o.Super().AsNode().HasNode(path)
}

// GetNode is promoted from [Node.Instance.GetNode].
func (self Instance) GetNode(path string) Node.Instance {
	return self.AsNode().GetNode(path)
}

// GetNode is promoted from [Node.Instance.GetNode].
func (o *Extension[T]) GetNode(path string) Node.Instance {
	return o.Super().AsNode().GetNode(path)
}

// GetNodeOrNull is promoted from [Node.Instance.GetNodeOrNull].
func (self Instance) GetNodeOrNull(path string) Node.Instance {
	return self.AsNode().GetNodeOrNull(path)
}

// GetNodeOrNull is promoted from [Node.Instance.GetNodeOrNull].
func (o *Extension[T]) GetNodeOrNull(path string) Node.Instance {
	return o.Super().AsNode().GetNodeOrNull(path)
}

// GetParent is promoted from [Node.Instance.GetParent].
func (self Instance) GetParent() Node.Instance {
	return self.AsNode().GetParent()
}

// GetParent is promoted from [Node.Instance.GetParent].
func (o *Extension[T]) GetParent() Node.Instance {
	return o.Super().AsNode().GetParent()
}

// FindParent is promoted from [Node.Instance.FindParent].
func (self Instance) FindParent(pattern string) Node.Instance {
	return self.AsNode().FindParent(pattern)
}

// FindParent is promoted from [Node.Instance.FindParent].
func (o *Extension[T]) FindParent(pattern string) Node.Instance {
	return o.Super().AsNode().FindParent(pattern)
}

// HasNodeAndResource is promoted from [Node.Instance.HasNodeAndResource].
func (self Instance) HasNodeAndResource(path string) bool {
	return self.AsNode().HasNodeAndResource(path)
}

// HasNodeAndResource is promoted from [Node.Instance.HasNodeAndResource].
func (o *Extension[T]) HasNodeAndResource(path string) bool {
	return o.Super().AsNode().HasNodeAndResource(path)
}

// IsInsideTree is promoted from [Node.Instance.IsInsideTree].
func (self Instance) IsInsideTree() bool {
	return self.AsNode().IsInsideTree()
}

// IsInsideTree is promoted from [Node.Instance.IsInsideTree].
func (o *Extension[T]) IsInsideTree() bool {
	return o.Super().AsNode().IsInsideTree()
}

// IsPartOfEditedScene is promoted from [Node.Instance.IsPartOfEditedScene].
func (self Instance) IsPartOfEditedScene() bool {
	return self.AsNode().IsPartOfEditedScene()
}

// IsPartOfEditedScene is promoted from [Node.Instance.IsPartOfEditedScene].
func (o *Extension[T]) IsPartOfEditedScene() bool {
	return o.Super().AsNode().IsPartOfEditedScene()
}

// IsAncestorOf is promoted from [Node.Instance.IsAncestorOf].
func (self Instance) IsAncestorOf(node Node.Instance) bool {
	return self.AsNode().IsAncestorOf(node)
}

// IsAncestorOf is promoted from [Node.Instance.IsAncestorOf].
func (o *Extension[T]) IsAncestorOf(node Node.Instance) bool {
	return o.Super().AsNode().IsAncestorOf(node)
}

// IsGreaterThan is promoted from [Node.Instance.IsGreaterThan].
func (self Instance) IsGreaterThan(node Node.Instance) bool {
	return self.AsNode().IsGreaterThan(node)
}

// IsGreaterThan is promoted from [Node.Instance.IsGreaterThan].
func (o *Extension[T]) IsGreaterThan(node Node.Instance) bool {
	return o.Super().AsNode().IsGreaterThan(node)
}

// GetPath is promoted from [Node.Instance.GetPath].
func (self Instance) GetPath() string {
	return self.AsNode().GetPath()
}

// GetPath is promoted from [Node.Instance.GetPath].
func (o *Extension[T]) GetPath() string {
	return o.Super().AsNode().GetPath()
}

// RemoveFromGroup is promoted from [Node.Instance.RemoveFromGroup].
func (self Instance) RemoveFromGroup(group string) {
	self.AsNode().RemoveFromGroup(group)
}

// RemoveFromGroup is promoted from [Node.Instance.RemoveFromGroup].
func (o *Extension[T]) RemoveFromGroup(group string) {
	o.Super().AsNode().RemoveFromGroup(group)
}

// IsInGroup is promoted from [Node.Instance.IsInGroup].
func (self Instance) IsInGroup(group string) bool {
	return self.AsNode().IsInGroup(group)
}

// IsInGroup is promoted from [Node.Instance.IsInGroup].
func (o *Extension[T]) IsInGroup(group string) bool {
	return o.Super().AsNode().IsInGroup(group)
}

// MoveChild is promoted from [Node.Instance.MoveChild].
func (self Instance) MoveChild(child_node Node.Instance, to_index int) {
	self.AsNode().MoveChild(child_node, to_index)
}

// MoveChild is promoted from [Node.Instance.MoveChild].
func (o *Extension[T]) MoveChild(child_node Node.Instance, to_index int) {
	o.Super().AsNode().MoveChild(child_node, to_index)
}

// GetGroups is promoted from [Node.Instance.GetGroups].
func (self Instance) GetGroups() []string {
	return self.AsNode().GetGroups()
}

// GetGroups is promoted from [Node.Instance.GetGroups].
func (o *Extension[T]) GetGroups() []string {
	return o.Super().AsNode().GetGroups()
}

// PrintTree is promoted from [Node.Instance.PrintTree].
func (self Instance) PrintTree() {
	self.AsNode().PrintTree()
}

// PrintTree is promoted from [Node.Instance.PrintTree].
func (o *Extension[T]) PrintTree() {
	o.Super().AsNode().PrintTree()
}

// PrintTreePretty is promoted from [Node.Instance.PrintTreePretty].
func (self Instance) PrintTreePretty() {
	self.AsNode().PrintTreePretty()
}

// PrintTreePretty is promoted from [Node.Instance.PrintTreePretty].
func (o *Extension[T]) PrintTreePretty() {
	o.Super().AsNode().PrintTreePretty()
}

// GetTreeString is promoted from [Node.Instance.GetTreeString].
func (self Instance) GetTreeString() string {
	return self.AsNode().GetTreeString()
}

// GetTreeString is promoted from [Node.Instance.GetTreeString].
func (o *Extension[T]) GetTreeString() string {
	return o.Super().AsNode().GetTreeString()
}

// GetTreeStringPretty is promoted from [Node.Instance.GetTreeStringPretty].
func (self Instance) GetTreeStringPretty() string {
	return self.AsNode().GetTreeStringPretty()
}

// GetTreeStringPretty is promoted from [Node.Instance.GetTreeStringPretty].
func (o *Extension[T]) GetTreeStringPretty() string {
	return o.Super().AsNode().GetTreeStringPretty()
}

// PropagateNotification is promoted from [Node.Instance.PropagateNotification].
func (self Instance) PropagateNotification(what int) {
	self.AsNode().PropagateNotification(what)
}

// PropagateNotification is promoted from [Node.Instance.PropagateNotification].
func (o *Extension[T]) PropagateNotification(what int) {
	o.Super().AsNode().PropagateNotification(what)
}

// SetPhysicsProcess is promoted from [Node.Instance.SetPhysicsProcess].
func (self Instance) SetPhysicsProcess(enable bool) Instance {
	self.AsNode().SetPhysicsProcess(enable)
	return self
}

// SetPhysicsProcess is promoted from [Node.Instance.SetPhysicsProcess].
func (o *Extension[T]) SetPhysicsProcess(enable bool) *Extension[T] {
	o.Super().AsNode().SetPhysicsProcess(enable)
	return o
}

// GetPhysicsProcessDeltaTime is promoted from [Node.Instance.GetPhysicsProcessDeltaTime].
func (self Instance) GetPhysicsProcessDeltaTime() Float.X {
	return self.AsNode().GetPhysicsProcessDeltaTime()
}

// GetPhysicsProcessDeltaTime is promoted from [Node.Instance.GetPhysicsProcessDeltaTime].
func (o *Extension[T]) GetPhysicsProcessDeltaTime() Float.X {
	return o.Super().AsNode().GetPhysicsProcessDeltaTime()
}

// IsPhysicsProcessing is promoted from [Node.Instance.IsPhysicsProcessing].
func (self Instance) IsPhysicsProcessing() bool {
	return self.AsNode().IsPhysicsProcessing()
}

// IsPhysicsProcessing is promoted from [Node.Instance.IsPhysicsProcessing].
func (o *Extension[T]) IsPhysicsProcessing() bool {
	return o.Super().AsNode().IsPhysicsProcessing()
}

// GetProcessDeltaTime is promoted from [Node.Instance.GetProcessDeltaTime].
func (self Instance) GetProcessDeltaTime() Float.X {
	return self.AsNode().GetProcessDeltaTime()
}

// GetProcessDeltaTime is promoted from [Node.Instance.GetProcessDeltaTime].
func (o *Extension[T]) GetProcessDeltaTime() Float.X {
	return o.Super().AsNode().GetProcessDeltaTime()
}

// SetProcess is promoted from [Node.Instance.SetProcess].
func (self Instance) SetProcess(enable bool) Instance {
	self.AsNode().SetProcess(enable)
	return self
}

// SetProcess is promoted from [Node.Instance.SetProcess].
func (o *Extension[T]) SetProcess(enable bool) *Extension[T] {
	o.Super().AsNode().SetProcess(enable)
	return o
}

// IsProcessing is promoted from [Node.Instance.IsProcessing].
func (self Instance) IsProcessing() bool {
	return self.AsNode().IsProcessing()
}

// IsProcessing is promoted from [Node.Instance.IsProcessing].
func (o *Extension[T]) IsProcessing() bool {
	return o.Super().AsNode().IsProcessing()
}

// SetProcessInput is promoted from [Node.Instance.SetProcessInput].
func (self Instance) SetProcessInput(enable bool) Instance {
	self.AsNode().SetProcessInput(enable)
	return self
}

// SetProcessInput is promoted from [Node.Instance.SetProcessInput].
func (o *Extension[T]) SetProcessInput(enable bool) *Extension[T] {
	o.Super().AsNode().SetProcessInput(enable)
	return o
}

// IsProcessingInput is promoted from [Node.Instance.IsProcessingInput].
func (self Instance) IsProcessingInput() bool {
	return self.AsNode().IsProcessingInput()
}

// IsProcessingInput is promoted from [Node.Instance.IsProcessingInput].
func (o *Extension[T]) IsProcessingInput() bool {
	return o.Super().AsNode().IsProcessingInput()
}

// SetProcessShortcutInput is promoted from [Node.Instance.SetProcessShortcutInput].
func (self Instance) SetProcessShortcutInput(enable bool) Instance {
	self.AsNode().SetProcessShortcutInput(enable)
	return self
}

// SetProcessShortcutInput is promoted from [Node.Instance.SetProcessShortcutInput].
func (o *Extension[T]) SetProcessShortcutInput(enable bool) *Extension[T] {
	o.Super().AsNode().SetProcessShortcutInput(enable)
	return o
}

// IsProcessingShortcutInput is promoted from [Node.Instance.IsProcessingShortcutInput].
func (self Instance) IsProcessingShortcutInput() bool {
	return self.AsNode().IsProcessingShortcutInput()
}

// IsProcessingShortcutInput is promoted from [Node.Instance.IsProcessingShortcutInput].
func (o *Extension[T]) IsProcessingShortcutInput() bool {
	return o.Super().AsNode().IsProcessingShortcutInput()
}

// SetProcessUnhandledInput is promoted from [Node.Instance.SetProcessUnhandledInput].
func (self Instance) SetProcessUnhandledInput(enable bool) Instance {
	self.AsNode().SetProcessUnhandledInput(enable)
	return self
}

// SetProcessUnhandledInput is promoted from [Node.Instance.SetProcessUnhandledInput].
func (o *Extension[T]) SetProcessUnhandledInput(enable bool) *Extension[T] {
	o.Super().AsNode().SetProcessUnhandledInput(enable)
	return o
}

// IsProcessingUnhandledInput is promoted from [Node.Instance.IsProcessingUnhandledInput].
func (self Instance) IsProcessingUnhandledInput() bool {
	return self.AsNode().IsProcessingUnhandledInput()
}

// IsProcessingUnhandledInput is promoted from [Node.Instance.IsProcessingUnhandledInput].
func (o *Extension[T]) IsProcessingUnhandledInput() bool {
	return o.Super().AsNode().IsProcessingUnhandledInput()
}

// SetProcessUnhandledKeyInput is promoted from [Node.Instance.SetProcessUnhandledKeyInput].
func (self Instance) SetProcessUnhandledKeyInput(enable bool) Instance {
	self.AsNode().SetProcessUnhandledKeyInput(enable)
	return self
}

// SetProcessUnhandledKeyInput is promoted from [Node.Instance.SetProcessUnhandledKeyInput].
func (o *Extension[T]) SetProcessUnhandledKeyInput(enable bool) *Extension[T] {
	o.Super().AsNode().SetProcessUnhandledKeyInput(enable)
	return o
}

// IsProcessingUnhandledKeyInput is promoted from [Node.Instance.IsProcessingUnhandledKeyInput].
func (self Instance) IsProcessingUnhandledKeyInput() bool {
	return self.AsNode().IsProcessingUnhandledKeyInput()
}

// IsProcessingUnhandledKeyInput is promoted from [Node.Instance.IsProcessingUnhandledKeyInput].
func (o *Extension[T]) IsProcessingUnhandledKeyInput() bool {
	return o.Super().AsNode().IsProcessingUnhandledKeyInput()
}

// CanProcess is promoted from [Node.Instance.CanProcess].
func (self Instance) CanProcess() bool {
	return self.AsNode().CanProcess()
}

// CanProcess is promoted from [Node.Instance.CanProcess].
func (o *Extension[T]) CanProcess() bool {
	return o.Super().AsNode().CanProcess()
}

// QueueAccessibilityUpdate is promoted from [Node.Instance.QueueAccessibilityUpdate].
func (self Instance) QueueAccessibilityUpdate() {
	self.AsNode().QueueAccessibilityUpdate()
}

// QueueAccessibilityUpdate is promoted from [Node.Instance.QueueAccessibilityUpdate].
func (o *Extension[T]) QueueAccessibilityUpdate() {
	o.Super().AsNode().QueueAccessibilityUpdate()
}

// GetAccessibilityElement is promoted from [Node.Instance.GetAccessibilityElement].
func (self Instance) GetAccessibilityElement() RID.AccessibilityElement {
	return self.AsNode().GetAccessibilityElement()
}

// GetAccessibilityElement is promoted from [Node.Instance.GetAccessibilityElement].
func (o *Extension[T]) GetAccessibilityElement() RID.AccessibilityElement {
	return o.Super().AsNode().GetAccessibilityElement()
}

// SetDisplayFolded is promoted from [Node.Instance.SetDisplayFolded].
func (self Instance) SetDisplayFolded(fold bool) Instance {
	self.AsNode().SetDisplayFolded(fold)
	return self
}

// SetDisplayFolded is promoted from [Node.Instance.SetDisplayFolded].
func (o *Extension[T]) SetDisplayFolded(fold bool) *Extension[T] {
	o.Super().AsNode().SetDisplayFolded(fold)
	return o
}

// IsDisplayedFolded is promoted from [Node.Instance.IsDisplayedFolded].
func (self Instance) IsDisplayedFolded() bool {
	return self.AsNode().IsDisplayedFolded()
}

// IsDisplayedFolded is promoted from [Node.Instance.IsDisplayedFolded].
func (o *Extension[T]) IsDisplayedFolded() bool {
	return o.Super().AsNode().IsDisplayedFolded()
}

// SetProcessInternal is promoted from [Node.Instance.SetProcessInternal].
func (self Instance) SetProcessInternal(enable bool) Instance {
	self.AsNode().SetProcessInternal(enable)
	return self
}

// SetProcessInternal is promoted from [Node.Instance.SetProcessInternal].
func (o *Extension[T]) SetProcessInternal(enable bool) *Extension[T] {
	o.Super().AsNode().SetProcessInternal(enable)
	return o
}

// IsProcessingInternal is promoted from [Node.Instance.IsProcessingInternal].
func (self Instance) IsProcessingInternal() bool {
	return self.AsNode().IsProcessingInternal()
}

// IsProcessingInternal is promoted from [Node.Instance.IsProcessingInternal].
func (o *Extension[T]) IsProcessingInternal() bool {
	return o.Super().AsNode().IsProcessingInternal()
}

// SetPhysicsProcessInternal is promoted from [Node.Instance.SetPhysicsProcessInternal].
func (self Instance) SetPhysicsProcessInternal(enable bool) Instance {
	self.AsNode().SetPhysicsProcessInternal(enable)
	return self
}

// SetPhysicsProcessInternal is promoted from [Node.Instance.SetPhysicsProcessInternal].
func (o *Extension[T]) SetPhysicsProcessInternal(enable bool) *Extension[T] {
	o.Super().AsNode().SetPhysicsProcessInternal(enable)
	return o
}

// IsPhysicsProcessingInternal is promoted from [Node.Instance.IsPhysicsProcessingInternal].
func (self Instance) IsPhysicsProcessingInternal() bool {
	return self.AsNode().IsPhysicsProcessingInternal()
}

// IsPhysicsProcessingInternal is promoted from [Node.Instance.IsPhysicsProcessingInternal].
func (o *Extension[T]) IsPhysicsProcessingInternal() bool {
	return o.Super().AsNode().IsPhysicsProcessingInternal()
}

// IsPhysicsInterpolated is promoted from [Node.Instance.IsPhysicsInterpolated].
func (self Instance) IsPhysicsInterpolated() bool {
	return self.AsNode().IsPhysicsInterpolated()
}

// IsPhysicsInterpolated is promoted from [Node.Instance.IsPhysicsInterpolated].
func (o *Extension[T]) IsPhysicsInterpolated() bool {
	return o.Super().AsNode().IsPhysicsInterpolated()
}

// IsPhysicsInterpolatedAndEnabled is promoted from [Node.Instance.IsPhysicsInterpolatedAndEnabled].
func (self Instance) IsPhysicsInterpolatedAndEnabled() bool {
	return self.AsNode().IsPhysicsInterpolatedAndEnabled()
}

// IsPhysicsInterpolatedAndEnabled is promoted from [Node.Instance.IsPhysicsInterpolatedAndEnabled].
func (o *Extension[T]) IsPhysicsInterpolatedAndEnabled() bool {
	return o.Super().AsNode().IsPhysicsInterpolatedAndEnabled()
}

// ResetPhysicsInterpolation is promoted from [Node.Instance.ResetPhysicsInterpolation].
func (self Instance) ResetPhysicsInterpolation() {
	self.AsNode().ResetPhysicsInterpolation()
}

// ResetPhysicsInterpolation is promoted from [Node.Instance.ResetPhysicsInterpolation].
func (o *Extension[T]) ResetPhysicsInterpolation() {
	o.Super().AsNode().ResetPhysicsInterpolation()
}

// CanAutoTranslate is promoted from [Node.Instance.CanAutoTranslate].
func (self Instance) CanAutoTranslate() bool {
	return self.AsNode().CanAutoTranslate()
}

// CanAutoTranslate is promoted from [Node.Instance.CanAutoTranslate].
func (o *Extension[T]) CanAutoTranslate() bool {
	return o.Super().AsNode().CanAutoTranslate()
}

// SetTranslationDomainInherited is promoted from [Node.Instance.SetTranslationDomainInherited].
func (self Instance) SetTranslationDomainInherited() Instance {
	self.AsNode().SetTranslationDomainInherited()
	return self
}

// SetTranslationDomainInherited is promoted from [Node.Instance.SetTranslationDomainInherited].
func (o *Extension[T]) SetTranslationDomainInherited() *Extension[T] {
	o.Super().AsNode().SetTranslationDomainInherited()
	return o
}

// CreateTween is promoted from [Node.Instance.CreateTween].
func (self Instance) CreateTween() Tween.Instance {
	return self.AsNode().CreateTween()
}

// CreateTween is promoted from [Node.Instance.CreateTween].
func (o *Extension[T]) CreateTween() Tween.Instance {
	return o.Super().AsNode().CreateTween()
}

// SetSceneInstanceLoadPlaceholder is promoted from [Node.Instance.SetSceneInstanceLoadPlaceholder].
func (self Instance) SetSceneInstanceLoadPlaceholder(load_placeholder bool) Instance {
	self.AsNode().SetSceneInstanceLoadPlaceholder(load_placeholder)
	return self
}

// SetSceneInstanceLoadPlaceholder is promoted from [Node.Instance.SetSceneInstanceLoadPlaceholder].
func (o *Extension[T]) SetSceneInstanceLoadPlaceholder(load_placeholder bool) *Extension[T] {
	o.Super().AsNode().SetSceneInstanceLoadPlaceholder(load_placeholder)
	return o
}

// GetSceneInstanceLoadPlaceholder is promoted from [Node.Instance.GetSceneInstanceLoadPlaceholder].
func (self Instance) GetSceneInstanceLoadPlaceholder() bool {
	return self.AsNode().GetSceneInstanceLoadPlaceholder()
}

// GetSceneInstanceLoadPlaceholder is promoted from [Node.Instance.GetSceneInstanceLoadPlaceholder].
func (o *Extension[T]) GetSceneInstanceLoadPlaceholder() bool {
	return o.Super().AsNode().GetSceneInstanceLoadPlaceholder()
}

// SetEditableInstance is promoted from [Node.Instance.SetEditableInstance].
func (self Instance) SetEditableInstance(node Node.Instance, is_editable bool) Instance {
	self.AsNode().SetEditableInstance(node, is_editable)
	return self
}

// SetEditableInstance is promoted from [Node.Instance.SetEditableInstance].
func (o *Extension[T]) SetEditableInstance(node Node.Instance, is_editable bool) *Extension[T] {
	o.Super().AsNode().SetEditableInstance(node, is_editable)
	return o
}

// IsEditableInstance is promoted from [Node.Instance.IsEditableInstance].
func (self Instance) IsEditableInstance(node Node.Instance) bool {
	return self.AsNode().IsEditableInstance(node)
}

// IsEditableInstance is promoted from [Node.Instance.IsEditableInstance].
func (o *Extension[T]) IsEditableInstance(node Node.Instance) bool {
	return o.Super().AsNode().IsEditableInstance(node)
}

// QueueFree is promoted from [Node.Instance.QueueFree].
func (self Instance) QueueFree() {
	self.AsNode().QueueFree()
}

// QueueFree is promoted from [Node.Instance.QueueFree].
func (o *Extension[T]) QueueFree() {
	o.Super().AsNode().QueueFree()
}

// RequestReady is promoted from [Node.Instance.RequestReady].
func (self Instance) RequestReady() {
	self.AsNode().RequestReady()
}

// RequestReady is promoted from [Node.Instance.RequestReady].
func (o *Extension[T]) RequestReady() {
	o.Super().AsNode().RequestReady()
}

// IsNodeReady is promoted from [Node.Instance.IsNodeReady].
func (self Instance) IsNodeReady() bool {
	return self.AsNode().IsNodeReady()
}

// IsNodeReady is promoted from [Node.Instance.IsNodeReady].
func (o *Extension[T]) IsNodeReady() bool {
	return o.Super().AsNode().IsNodeReady()
}

// GetMultiplayerAuthority is promoted from [Node.Instance.GetMultiplayerAuthority].
func (self Instance) GetMultiplayerAuthority() int {
	return self.AsNode().GetMultiplayerAuthority()
}

// GetMultiplayerAuthority is promoted from [Node.Instance.GetMultiplayerAuthority].
func (o *Extension[T]) GetMultiplayerAuthority() int {
	return o.Super().AsNode().GetMultiplayerAuthority()
}

// IsMultiplayerAuthority is promoted from [Node.Instance.IsMultiplayerAuthority].
func (self Instance) IsMultiplayerAuthority() bool {
	return self.AsNode().IsMultiplayerAuthority()
}

// IsMultiplayerAuthority is promoted from [Node.Instance.IsMultiplayerAuthority].
func (o *Extension[T]) IsMultiplayerAuthority() bool {
	return o.Super().AsNode().IsMultiplayerAuthority()
}

// RpcConfig is promoted from [Node.Instance.RpcConfig].
func (self Instance) RpcConfig(method string, config any) {
	self.AsNode().RpcConfig(method, config)
}

// RpcConfig is promoted from [Node.Instance.RpcConfig].
func (o *Extension[T]) RpcConfig(method string, config any) {
	o.Super().AsNode().RpcConfig(method, config)
}

// GetNodeRpcConfig is promoted from [Node.Instance.GetNodeRpcConfig].
func (self Instance) GetNodeRpcConfig() any {
	return self.AsNode().GetNodeRpcConfig()
}

// GetNodeRpcConfig is promoted from [Node.Instance.GetNodeRpcConfig].
func (o *Extension[T]) GetNodeRpcConfig() any {
	return o.Super().AsNode().GetNodeRpcConfig()
}

// UpdateConfigurationWarnings is promoted from [Node.Instance.UpdateConfigurationWarnings].
func (self Instance) UpdateConfigurationWarnings() {
	self.AsNode().UpdateConfigurationWarnings()
}

// UpdateConfigurationWarnings is promoted from [Node.Instance.UpdateConfigurationWarnings].
func (o *Extension[T]) UpdateConfigurationWarnings() {
	o.Super().AsNode().UpdateConfigurationWarnings()
}

// SetDeferredThreadGroup is promoted from [Node.Instance.SetDeferredThreadGroup].
func (self Instance) SetDeferredThreadGroup(property string, value any) Instance {
	self.AsNode().SetDeferredThreadGroup(property, value)
	return self
}

// SetDeferredThreadGroup is promoted from [Node.Instance.SetDeferredThreadGroup].
func (o *Extension[T]) SetDeferredThreadGroup(property string, value any) *Extension[T] {
	o.Super().AsNode().SetDeferredThreadGroup(property, value)
	return o
}

// NotifyDeferredThreadGroup is promoted from [Node.Instance.NotifyDeferredThreadGroup].
func (self Instance) NotifyDeferredThreadGroup(what int) {
	self.AsNode().NotifyDeferredThreadGroup(what)
}

// NotifyDeferredThreadGroup is promoted from [Node.Instance.NotifyDeferredThreadGroup].
func (o *Extension[T]) NotifyDeferredThreadGroup(what int) {
	o.Super().AsNode().NotifyDeferredThreadGroup(what)
}

// SetThreadSafe is promoted from [Node.Instance.SetThreadSafe].
func (self Instance) SetThreadSafe(property string, value any) Instance {
	self.AsNode().SetThreadSafe(property, value)
	return self
}

// SetThreadSafe is promoted from [Node.Instance.SetThreadSafe].
func (o *Extension[T]) SetThreadSafe(property string, value any) *Extension[T] {
	o.Super().AsNode().SetThreadSafe(property, value)
	return o
}

// NotifyThreadSafe is promoted from [Node.Instance.NotifyThreadSafe].
func (self Instance) NotifyThreadSafe(what int) {
	self.AsNode().NotifyThreadSafe(what)
}

// NotifyThreadSafe is promoted from [Node.Instance.NotifyThreadSafe].
func (o *Extension[T]) NotifyThreadSafe(what int) {
	o.Super().AsNode().NotifyThreadSafe(what)
}

// Position is promoted from [Node2D.Instance.Position].
func (self Instance) Position() Vector2.XY { return self.AsNode2D().Position() }
func (o *Extension[T]) Position() Vector2.XY { return o.Super().AsNode2D().Position() }

// SetPosition is promoted from [Node2D.Instance.SetPosition].
func (self Instance) SetPosition(value Vector2.XY) Instance {
	self.AsNode2D().SetPosition(value)
	return self
}
func (o *Extension[T]) SetPosition(value Vector2.XY) *Extension[T] {
	o.Super().AsNode2D().SetPosition(value)
	return o
}

// Rotation is promoted from [Node2D.Instance.Rotation].
func (self Instance) Rotation() Angle.Radians { return self.AsNode2D().Rotation() }
func (o *Extension[T]) Rotation() Angle.Radians { return o.Super().AsNode2D().Rotation() }

// SetRotation is promoted from [Node2D.Instance.SetRotation].
func (self Instance) SetRotation(value Angle.Radians) Instance {
	self.AsNode2D().SetRotation(value)
	return self
}
func (o *Extension[T]) SetRotation(value Angle.Radians) *Extension[T] {
	o.Super().AsNode2D().SetRotation(value)
	return o
}

// RotationDegrees is promoted from [Node2D.Instance.RotationDegrees].
func (self Instance) RotationDegrees() Angle.Degrees { return self.AsNode2D().RotationDegrees() }
func (o *Extension[T]) RotationDegrees() Angle.Degrees { return o.Super().AsNode2D().RotationDegrees() }

// SetRotationDegrees is promoted from [Node2D.Instance.SetRotationDegrees].
func (self Instance) SetRotationDegrees(value Angle.Degrees) Instance {
	self.AsNode2D().SetRotationDegrees(value)
	return self
}
func (o *Extension[T]) SetRotationDegrees(value Angle.Degrees) *Extension[T] {
	o.Super().AsNode2D().SetRotationDegrees(value)
	return o
}

// Scale is promoted from [Node2D.Instance.Scale].
func (self Instance) Scale() Vector2.XY { return self.AsNode2D().Scale() }
func (o *Extension[T]) Scale() Vector2.XY { return o.Super().AsNode2D().Scale() }

// SetScale is promoted from [Node2D.Instance.SetScale].
func (self Instance) SetScale(value Vector2.XY) Instance {
	self.AsNode2D().SetScale(value)
	return self
}
func (o *Extension[T]) SetScale(value Vector2.XY) *Extension[T] {
	o.Super().AsNode2D().SetScale(value)
	return o
}

// Skew is promoted from [Node2D.Instance.Skew].
func (self Instance) Skew() Float.X { return self.AsNode2D().Skew() }
func (o *Extension[T]) Skew() Float.X { return o.Super().AsNode2D().Skew() }

// SetSkew is promoted from [Node2D.Instance.SetSkew].
func (self Instance) SetSkew(value Float.X) Instance {
	self.AsNode2D().SetSkew(value)
	return self
}
func (o *Extension[T]) SetSkew(value Float.X) *Extension[T] {
	o.Super().AsNode2D().SetSkew(value)
	return o
}

// SetTransform is promoted from [Node2D.Instance.SetTransform].
func (self Instance) SetTransform(value Transform2D.OriginXY) Instance {
	self.AsNode2D().SetTransform(value)
	return self
}
func (o *Extension[T]) SetTransform(value Transform2D.OriginXY) *Extension[T] {
	o.Super().AsNode2D().SetTransform(value)
	return o
}

// GlobalPosition is promoted from [Node2D.Instance.GlobalPosition].
func (self Instance) GlobalPosition() Vector2.XY { return self.AsNode2D().GlobalPosition() }
func (o *Extension[T]) GlobalPosition() Vector2.XY { return o.Super().AsNode2D().GlobalPosition() }

// SetGlobalPosition is promoted from [Node2D.Instance.SetGlobalPosition].
func (self Instance) SetGlobalPosition(value Vector2.XY) Instance {
	self.AsNode2D().SetGlobalPosition(value)
	return self
}
func (o *Extension[T]) SetGlobalPosition(value Vector2.XY) *Extension[T] {
	o.Super().AsNode2D().SetGlobalPosition(value)
	return o
}

// GlobalRotation is promoted from [Node2D.Instance.GlobalRotation].
func (self Instance) GlobalRotation() Angle.Radians { return self.AsNode2D().GlobalRotation() }
func (o *Extension[T]) GlobalRotation() Angle.Radians { return o.Super().AsNode2D().GlobalRotation() }

// SetGlobalRotation is promoted from [Node2D.Instance.SetGlobalRotation].
func (self Instance) SetGlobalRotation(value Angle.Radians) Instance {
	self.AsNode2D().SetGlobalRotation(value)
	return self
}
func (o *Extension[T]) SetGlobalRotation(value Angle.Radians) *Extension[T] {
	o.Super().AsNode2D().SetGlobalRotation(value)
	return o
}

// GlobalRotationDegrees is promoted from [Node2D.Instance.GlobalRotationDegrees].
func (self Instance) GlobalRotationDegrees() Angle.Degrees { return self.AsNode2D().GlobalRotationDegrees() }
func (o *Extension[T]) GlobalRotationDegrees() Angle.Degrees { return o.Super().AsNode2D().GlobalRotationDegrees() }

// SetGlobalRotationDegrees is promoted from [Node2D.Instance.SetGlobalRotationDegrees].
func (self Instance) SetGlobalRotationDegrees(value Angle.Degrees) Instance {
	self.AsNode2D().SetGlobalRotationDegrees(value)
	return self
}
func (o *Extension[T]) SetGlobalRotationDegrees(value Angle.Degrees) *Extension[T] {
	o.Super().AsNode2D().SetGlobalRotationDegrees(value)
	return o
}

// GlobalScale is promoted from [Node2D.Instance.GlobalScale].
func (self Instance) GlobalScale() Vector2.XY { return self.AsNode2D().GlobalScale() }
func (o *Extension[T]) GlobalScale() Vector2.XY { return o.Super().AsNode2D().GlobalScale() }

// SetGlobalScale is promoted from [Node2D.Instance.SetGlobalScale].
func (self Instance) SetGlobalScale(value Vector2.XY) Instance {
	self.AsNode2D().SetGlobalScale(value)
	return self
}
func (o *Extension[T]) SetGlobalScale(value Vector2.XY) *Extension[T] {
	o.Super().AsNode2D().SetGlobalScale(value)
	return o
}

// GlobalSkew is promoted from [Node2D.Instance.GlobalSkew].
func (self Instance) GlobalSkew() Float.X { return self.AsNode2D().GlobalSkew() }
func (o *Extension[T]) GlobalSkew() Float.X { return o.Super().AsNode2D().GlobalSkew() }

// SetGlobalSkew is promoted from [Node2D.Instance.SetGlobalSkew].
func (self Instance) SetGlobalSkew(value Float.X) Instance {
	self.AsNode2D().SetGlobalSkew(value)
	return self
}
func (o *Extension[T]) SetGlobalSkew(value Float.X) *Extension[T] {
	o.Super().AsNode2D().SetGlobalSkew(value)
	return o
}

// SetGlobalTransform is promoted from [Node2D.Instance.SetGlobalTransform].
func (self Instance) SetGlobalTransform(value Transform2D.OriginXY) Instance {
	self.AsNode2D().SetGlobalTransform(value)
	return self
}
func (o *Extension[T]) SetGlobalTransform(value Transform2D.OriginXY) *Extension[T] {
	o.Super().AsNode2D().SetGlobalTransform(value)
	return o
}

// Visible is promoted from [CanvasItem.Instance.Visible].
func (self Instance) Visible() bool { return self.AsCanvasItem().Visible() }
func (o *Extension[T]) Visible() bool { return o.Super().AsCanvasItem().Visible() }

// SetVisible is promoted from [CanvasItem.Instance.SetVisible].
func (self Instance) SetVisible(value bool) Instance {
	self.AsCanvasItem().SetVisible(value)
	return self
}
func (o *Extension[T]) SetVisible(value bool) *Extension[T] {
	o.Super().AsCanvasItem().SetVisible(value)
	return o
}

// Modulate is promoted from [CanvasItem.Instance.Modulate].
func (self Instance) Modulate() Color.RGBA { return self.AsCanvasItem().Modulate() }
func (o *Extension[T]) Modulate() Color.RGBA { return o.Super().AsCanvasItem().Modulate() }

// SetModulate is promoted from [CanvasItem.Instance.SetModulate].
func (self Instance) SetModulate(value Color.RGBA) Instance {
	self.AsCanvasItem().SetModulate(value)
	return self
}
func (o *Extension[T]) SetModulate(value Color.RGBA) *Extension[T] {
	o.Super().AsCanvasItem().SetModulate(value)
	return o
}

// SelfModulate is promoted from [CanvasItem.Instance.SelfModulate].
func (self Instance) SelfModulate() Color.RGBA { return self.AsCanvasItem().SelfModulate() }
func (o *Extension[T]) SelfModulate() Color.RGBA { return o.Super().AsCanvasItem().SelfModulate() }

// SetSelfModulate is promoted from [CanvasItem.Instance.SetSelfModulate].
func (self Instance) SetSelfModulate(value Color.RGBA) Instance {
	self.AsCanvasItem().SetSelfModulate(value)
	return self
}
func (o *Extension[T]) SetSelfModulate(value Color.RGBA) *Extension[T] {
	o.Super().AsCanvasItem().SetSelfModulate(value)
	return o
}

// ShowBehindParent is promoted from [CanvasItem.Instance.ShowBehindParent].
func (self Instance) ShowBehindParent() bool { return self.AsCanvasItem().ShowBehindParent() }
func (o *Extension[T]) ShowBehindParent() bool { return o.Super().AsCanvasItem().ShowBehindParent() }

// SetShowBehindParent is promoted from [CanvasItem.Instance.SetShowBehindParent].
func (self Instance) SetShowBehindParent(value bool) Instance {
	self.AsCanvasItem().SetShowBehindParent(value)
	return self
}
func (o *Extension[T]) SetShowBehindParent(value bool) *Extension[T] {
	o.Super().AsCanvasItem().SetShowBehindParent(value)
	return o
}

// TopLevel is promoted from [CanvasItem.Instance.TopLevel].
func (self Instance) TopLevel() bool { return self.AsCanvasItem().TopLevel() }
func (o *Extension[T]) TopLevel() bool { return o.Super().AsCanvasItem().TopLevel() }

// SetTopLevel is promoted from [CanvasItem.Instance.SetTopLevel].
func (self Instance) SetTopLevel(value bool) Instance {
	self.AsCanvasItem().SetTopLevel(value)
	return self
}
func (o *Extension[T]) SetTopLevel(value bool) *Extension[T] {
	o.Super().AsCanvasItem().SetTopLevel(value)
	return o
}

// ClipChildren is promoted from [CanvasItem.Instance.ClipChildren].
func (self Instance) ClipChildren() CanvasItem.ClipChildrenMode { return self.AsCanvasItem().ClipChildren() }
func (o *Extension[T]) ClipChildren() CanvasItem.ClipChildrenMode { return o.Super().AsCanvasItem().ClipChildren() }

// SetClipChildren is promoted from [CanvasItem.Instance.SetClipChildren].
func (self Instance) SetClipChildren(value CanvasItem.ClipChildrenMode) Instance {
	self.AsCanvasItem().SetClipChildren(value)
	return self
}
func (o *Extension[T]) SetClipChildren(value CanvasItem.ClipChildrenMode) *Extension[T] {
	o.Super().AsCanvasItem().SetClipChildren(value)
	return o
}

// LightMask is promoted from [CanvasItem.Instance.LightMask].
func (self Instance) LightMask() int { return self.AsCanvasItem().LightMask() }
func (o *Extension[T]) LightMask() int { return o.Super().AsCanvasItem().LightMask() }

// SetLightMask is promoted from [CanvasItem.Instance.SetLightMask].
func (self Instance) SetLightMask(value int) Instance {
	self.AsCanvasItem().SetLightMask(value)
	return self
}
func (o *Extension[T]) SetLightMask(value int) *Extension[T] {
	o.Super().AsCanvasItem().SetLightMask(value)
	return o
}

// VisibilityLayer is promoted from [CanvasItem.Instance.VisibilityLayer].
func (self Instance) VisibilityLayer() int { return self.AsCanvasItem().VisibilityLayer() }
func (o *Extension[T]) VisibilityLayer() int { return o.Super().AsCanvasItem().VisibilityLayer() }

// SetVisibilityLayer is promoted from [CanvasItem.Instance.SetVisibilityLayer].
func (self Instance) SetVisibilityLayer(value int) Instance {
	self.AsCanvasItem().SetVisibilityLayer(value)
	return self
}
func (o *Extension[T]) SetVisibilityLayer(value int) *Extension[T] {
	o.Super().AsCanvasItem().SetVisibilityLayer(value)
	return o
}

// ZIndex is promoted from [CanvasItem.Instance.ZIndex].
func (self Instance) ZIndex() int { return self.AsCanvasItem().ZIndex() }
func (o *Extension[T]) ZIndex() int { return o.Super().AsCanvasItem().ZIndex() }

// SetZIndex is promoted from [CanvasItem.Instance.SetZIndex].
func (self Instance) SetZIndex(value int) Instance {
	self.AsCanvasItem().SetZIndex(value)
	return self
}
func (o *Extension[T]) SetZIndex(value int) *Extension[T] {
	o.Super().AsCanvasItem().SetZIndex(value)
	return o
}

// ZAsRelative is promoted from [CanvasItem.Instance.ZAsRelative].
func (self Instance) ZAsRelative() bool { return self.AsCanvasItem().ZAsRelative() }
func (o *Extension[T]) ZAsRelative() bool { return o.Super().AsCanvasItem().ZAsRelative() }

// SetZAsRelative is promoted from [CanvasItem.Instance.SetZAsRelative].
func (self Instance) SetZAsRelative(value bool) Instance {
	self.AsCanvasItem().SetZAsRelative(value)
	return self
}
func (o *Extension[T]) SetZAsRelative(value bool) *Extension[T] {
	o.Super().AsCanvasItem().SetZAsRelative(value)
	return o
}

// YSortEnabled is promoted from [CanvasItem.Instance.YSortEnabled].
func (self Instance) YSortEnabled() bool { return self.AsCanvasItem().YSortEnabled() }
func (o *Extension[T]) YSortEnabled() bool { return o.Super().AsCanvasItem().YSortEnabled() }

// SetYSortEnabled is promoted from [CanvasItem.Instance.SetYSortEnabled].
func (self Instance) SetYSortEnabled(value bool) Instance {
	self.AsCanvasItem().SetYSortEnabled(value)
	return self
}
func (o *Extension[T]) SetYSortEnabled(value bool) *Extension[T] {
	o.Super().AsCanvasItem().SetYSortEnabled(value)
	return o
}

// TextureFilter is promoted from [CanvasItem.Instance.TextureFilter].
func (self Instance) TextureFilter() CanvasItem.TextureFilter { return self.AsCanvasItem().TextureFilter() }
func (o *Extension[T]) TextureFilter() CanvasItem.TextureFilter { return o.Super().AsCanvasItem().TextureFilter() }

// SetTextureFilter is promoted from [CanvasItem.Instance.SetTextureFilter].
func (self Instance) SetTextureFilter(value CanvasItem.TextureFilter) Instance {
	self.AsCanvasItem().SetTextureFilter(value)
	return self
}
func (o *Extension[T]) SetTextureFilter(value CanvasItem.TextureFilter) *Extension[T] {
	o.Super().AsCanvasItem().SetTextureFilter(value)
	return o
}

// TextureRepeat is promoted from [CanvasItem.Instance.TextureRepeat].
func (self Instance) TextureRepeat() CanvasItem.TextureRepeat { return self.AsCanvasItem().TextureRepeat() }
func (o *Extension[T]) TextureRepeat() CanvasItem.TextureRepeat { return o.Super().AsCanvasItem().TextureRepeat() }

// SetTextureRepeat is promoted from [CanvasItem.Instance.SetTextureRepeat].
func (self Instance) SetTextureRepeat(value CanvasItem.TextureRepeat) Instance {
	self.AsCanvasItem().SetTextureRepeat(value)
	return self
}
func (o *Extension[T]) SetTextureRepeat(value CanvasItem.TextureRepeat) *Extension[T] {
	o.Super().AsCanvasItem().SetTextureRepeat(value)
	return o
}

// Material is promoted from [CanvasItem.Instance.Material].
func (self Instance) Material() Material.Instance { return self.AsCanvasItem().Material() }
func (o *Extension[T]) Material() Material.Instance { return o.Super().AsCanvasItem().Material() }

// SetMaterial is promoted from [CanvasItem.Instance.SetMaterial].
func (self Instance) SetMaterial(value Material.Instance) Instance {
	self.AsCanvasItem().SetMaterial(value)
	return self
}
func (o *Extension[T]) SetMaterial(value Material.Instance) *Extension[T] {
	o.Super().AsCanvasItem().SetMaterial(value)
	return o
}

// UseParentMaterial is promoted from [CanvasItem.Instance.UseParentMaterial].
func (self Instance) UseParentMaterial() bool { return self.AsCanvasItem().UseParentMaterial() }
func (o *Extension[T]) UseParentMaterial() bool { return o.Super().AsCanvasItem().UseParentMaterial() }

// SetUseParentMaterial is promoted from [CanvasItem.Instance.SetUseParentMaterial].
func (self Instance) SetUseParentMaterial(value bool) Instance {
	self.AsCanvasItem().SetUseParentMaterial(value)
	return self
}
func (o *Extension[T]) SetUseParentMaterial(value bool) *Extension[T] {
	o.Super().AsCanvasItem().SetUseParentMaterial(value)
	return o
}

// Name is promoted from [Node.Instance.Name].
func (self Instance) Name() string { return self.AsNode().Name() }
func (o *Extension[T]) Name() string { return o.Super().AsNode().Name() }

// SetName is promoted from [Node.Instance.SetName].
func (self Instance) SetName(value string) Instance {
	self.AsNode().SetName(value)
	return self
}
func (o *Extension[T]) SetName(value string) *Extension[T] {
	o.Super().AsNode().SetName(value)
	return o
}

// UniqueNameInOwner is promoted from [Node.Instance.UniqueNameInOwner].
func (self Instance) UniqueNameInOwner() bool { return self.AsNode().UniqueNameInOwner() }
func (o *Extension[T]) UniqueNameInOwner() bool { return o.Super().AsNode().UniqueNameInOwner() }

// SetUniqueNameInOwner is promoted from [Node.Instance.SetUniqueNameInOwner].
func (self Instance) SetUniqueNameInOwner(value bool) Instance {
	self.AsNode().SetUniqueNameInOwner(value)
	return self
}
func (o *Extension[T]) SetUniqueNameInOwner(value bool) *Extension[T] {
	o.Super().AsNode().SetUniqueNameInOwner(value)
	return o
}

// SceneFilePath is promoted from [Node.Instance.SceneFilePath].
func (self Instance) SceneFilePath() string { return self.AsNode().SceneFilePath() }
func (o *Extension[T]) SceneFilePath() string { return o.Super().AsNode().SceneFilePath() }

// SetSceneFilePath is promoted from [Node.Instance.SetSceneFilePath].
func (self Instance) SetSceneFilePath(value string) Instance {
	self.AsNode().SetSceneFilePath(value)
	return self
}
func (o *Extension[T]) SetSceneFilePath(value string) *Extension[T] {
	o.Super().AsNode().SetSceneFilePath(value)
	return o
}

// Owner is promoted from [Node.Instance.Owner].
func (self Instance) Owner() Node.Instance { return self.AsNode().Owner() }
func (o *Extension[T]) Owner() Node.Instance { return o.Super().AsNode().Owner() }

// SetOwner is promoted from [Node.Instance.SetOwner].
func (self Instance) SetOwner(value Node.Instance) Instance {
	self.AsNode().SetOwner(value)
	return self
}
func (o *Extension[T]) SetOwner(value Node.Instance) *Extension[T] {
	o.Super().AsNode().SetOwner(value)
	return o
}

// Multiplayer is promoted from [Node.Instance.Multiplayer].
func (self Instance) Multiplayer() MultiplayerAPI.Instance { return self.AsNode().Multiplayer() }
func (o *Extension[T]) Multiplayer() MultiplayerAPI.Instance { return o.Super().AsNode().Multiplayer() }

// ProcessMode is promoted from [Node.Instance.ProcessMode].
func (self Instance) ProcessMode() Node.ProcessMode { return self.AsNode().ProcessMode() }
func (o *Extension[T]) ProcessMode() Node.ProcessMode { return o.Super().AsNode().ProcessMode() }

// SetProcessMode is promoted from [Node.Instance.SetProcessMode].
func (self Instance) SetProcessMode(value Node.ProcessMode) Instance {
	self.AsNode().SetProcessMode(value)
	return self
}
func (o *Extension[T]) SetProcessMode(value Node.ProcessMode) *Extension[T] {
	o.Super().AsNode().SetProcessMode(value)
	return o
}

// ProcessPriority is promoted from [Node.Instance.ProcessPriority].
func (self Instance) ProcessPriority() int { return self.AsNode().ProcessPriority() }
func (o *Extension[T]) ProcessPriority() int { return o.Super().AsNode().ProcessPriority() }

// SetProcessPriority is promoted from [Node.Instance.SetProcessPriority].
func (self Instance) SetProcessPriority(value int) Instance {
	self.AsNode().SetProcessPriority(value)
	return self
}
func (o *Extension[T]) SetProcessPriority(value int) *Extension[T] {
	o.Super().AsNode().SetProcessPriority(value)
	return o
}

// ProcessPhysicsPriority is promoted from [Node.Instance.ProcessPhysicsPriority].
func (self Instance) ProcessPhysicsPriority() int { return self.AsNode().ProcessPhysicsPriority() }
func (o *Extension[T]) ProcessPhysicsPriority() int { return o.Super().AsNode().ProcessPhysicsPriority() }

// SetProcessPhysicsPriority is promoted from [Node.Instance.SetProcessPhysicsPriority].
func (self Instance) SetProcessPhysicsPriority(value int) Instance {
	self.AsNode().SetProcessPhysicsPriority(value)
	return self
}
func (o *Extension[T]) SetProcessPhysicsPriority(value int) *Extension[T] {
	o.Super().AsNode().SetProcessPhysicsPriority(value)
	return o
}

// ProcessThreadGroup is promoted from [Node.Instance.ProcessThreadGroup].
func (self Instance) ProcessThreadGroup() Node.ProcessThreadGroup { return self.AsNode().ProcessThreadGroup() }
func (o *Extension[T]) ProcessThreadGroup() Node.ProcessThreadGroup { return o.Super().AsNode().ProcessThreadGroup() }

// SetProcessThreadGroup is promoted from [Node.Instance.SetProcessThreadGroup].
func (self Instance) SetProcessThreadGroup(value Node.ProcessThreadGroup) Instance {
	self.AsNode().SetProcessThreadGroup(value)
	return self
}
func (o *Extension[T]) SetProcessThreadGroup(value Node.ProcessThreadGroup) *Extension[T] {
	o.Super().AsNode().SetProcessThreadGroup(value)
	return o
}

// ProcessThreadGroupOrder is promoted from [Node.Instance.ProcessThreadGroupOrder].
func (self Instance) ProcessThreadGroupOrder() int { return self.AsNode().ProcessThreadGroupOrder() }
func (o *Extension[T]) ProcessThreadGroupOrder() int { return o.Super().AsNode().ProcessThreadGroupOrder() }

// SetProcessThreadGroupOrder is promoted from [Node.Instance.SetProcessThreadGroupOrder].
func (self Instance) SetProcessThreadGroupOrder(value int) Instance {
	self.AsNode().SetProcessThreadGroupOrder(value)
	return self
}
func (o *Extension[T]) SetProcessThreadGroupOrder(value int) *Extension[T] {
	o.Super().AsNode().SetProcessThreadGroupOrder(value)
	return o
}

// ProcessThreadMessages is promoted from [Node.Instance.ProcessThreadMessages].
func (self Instance) ProcessThreadMessages() Node.ProcessThreadMessages { return self.AsNode().ProcessThreadMessages() }
func (o *Extension[T]) ProcessThreadMessages() Node.ProcessThreadMessages { return o.Super().AsNode().ProcessThreadMessages() }

// SetProcessThreadMessages is promoted from [Node.Instance.SetProcessThreadMessages].
func (self Instance) SetProcessThreadMessages(value Node.ProcessThreadMessages) Instance {
	self.AsNode().SetProcessThreadMessages(value)
	return self
}
func (o *Extension[T]) SetProcessThreadMessages(value Node.ProcessThreadMessages) *Extension[T] {
	o.Super().AsNode().SetProcessThreadMessages(value)
	return o
}

// PhysicsInterpolationMode is promoted from [Node.Instance.PhysicsInterpolationMode].
func (self Instance) PhysicsInterpolationMode() Node.PhysicsInterpolationMode { return self.AsNode().PhysicsInterpolationMode() }
func (o *Extension[T]) PhysicsInterpolationMode() Node.PhysicsInterpolationMode { return o.Super().AsNode().PhysicsInterpolationMode() }

// SetPhysicsInterpolationMode is promoted from [Node.Instance.SetPhysicsInterpolationMode].
func (self Instance) SetPhysicsInterpolationMode(value Node.PhysicsInterpolationMode) Instance {
	self.AsNode().SetPhysicsInterpolationMode(value)
	return self
}
func (o *Extension[T]) SetPhysicsInterpolationMode(value Node.PhysicsInterpolationMode) *Extension[T] {
	o.Super().AsNode().SetPhysicsInterpolationMode(value)
	return o
}

// AutoTranslateMode is promoted from [Node.Instance.AutoTranslateMode].
func (self Instance) AutoTranslateMode() Node.AutoTranslateMode { return self.AsNode().AutoTranslateMode() }
func (o *Extension[T]) AutoTranslateMode() Node.AutoTranslateMode { return o.Super().AsNode().AutoTranslateMode() }

// SetAutoTranslateMode is promoted from [Node.Instance.SetAutoTranslateMode].
func (self Instance) SetAutoTranslateMode(value Node.AutoTranslateMode) Instance {
	self.AsNode().SetAutoTranslateMode(value)
	return self
}
func (o *Extension[T]) SetAutoTranslateMode(value Node.AutoTranslateMode) *Extension[T] {
	o.Super().AsNode().SetAutoTranslateMode(value)
	return o
}

// EditorDescription is promoted from [Node.Instance.EditorDescription].
func (self Instance) EditorDescription() string { return self.AsNode().EditorDescription() }
func (o *Extension[T]) EditorDescription() string { return o.Super().AsNode().EditorDescription() }

// SetEditorDescription is promoted from [Node.Instance.SetEditorDescription].
func (self Instance) SetEditorDescription(value string) Instance {
	self.AsNode().SetEditorDescription(value)
	return self
}
func (o *Extension[T]) SetEditorDescription(value string) *Extension[T] {
	o.Super().AsNode().SetEditorDescription(value)
	return o
}

func (self class) Virtual(name string) reflect.Value {
	switch name {
	default: return gd.VirtualByName(Node2D.Advanced(self.AsNode2D()), name)
	}
}

func (self Instance) Virtual(name string) reflect.Value {
	switch name {
	default: return gd.VirtualByName(Node2D.Instance(self.AsNode2D()), name)
	}
}
func init() {gdclass.Register("Skeleton2D", func(ptr gdreference.Object) any { return Instance{gdclass.NewSkeleton2D(ptr)} })}
