// Code generated by the generate package DO NOT EDIT


package InputEventShortcut

import "reflect"
import "slices"
import "github.com/AveryLucas/gogogd/internal/pointers"
import "github.com/AveryLucas/gogogd/internal/callframe"
import "github.com/AveryLucas/gogogd/internal/gdextension"
import "github.com/AveryLucas/gogogd/internal/gdreference"
import "github.com/AveryLucas/gogogd/internal/noescape"
import gd "github.com/AveryLucas/gogogd/internal"
import "github.com/AveryLucas/gogogd/internal/gdclass"
import "github.com/AveryLucas/gogogd/internal/ie"
import "github.com/AveryLucas/gogogd/variant"
import "github.com/AveryLucas/gogogd/variant/Angle"
import "github.com/AveryLucas/gogogd/variant/Euler"
import "github.com/AveryLucas/gogogd/variant/Signal"
import "github.com/AveryLucas/gogogd/classdb/InputEvent"
import "github.com/AveryLucas/gogogd/classdb/Resource"
import "github.com/AveryLucas/gogogd/classdb/Shortcut"
import "github.com/AveryLucas/gogogd/variant/Array"
import "github.com/AveryLucas/gogogd/variant/Callable"
import "github.com/AveryLucas/gogogd/variant/Dictionary"
import "github.com/AveryLucas/gogogd/variant/Error"
import "github.com/AveryLucas/gogogd/variant/Float"
import "github.com/AveryLucas/gogogd/variant/Object"
import "github.com/AveryLucas/gogogd/variant/Packed"
import "github.com/AveryLucas/gogogd/variant/Path"
import "github.com/AveryLucas/gogogd/variant/RID"
import "github.com/AveryLucas/gogogd/variant/RefCounted"
import "github.com/AveryLucas/gogogd/variant/String"

var _ Object.ID
type _ gdclass.Node
var _ gd.String
var _ RefCounted.Instance
var _ reflect.Type
var _ callframe.Frame
var _ = pointers.Cycle
var _ = Array.Nil
var _ variant.Any
var _ Callable.Function
var _ Dictionary.Any
var _ RID.Any
var _ noescape.Variant
var _ String.Readable
var _ Path.ToNode
var _ Packed.Bytes
var _ Error.Code
var _ Float.X
var _ Signal.Any
var _ Angle.Radians
var _ Euler.Radians
var _ gdextension.Object
var _ = slices.Delete[[]struct{}, struct{}]

/*
ID is a typed object ID (reference) to an instance of this class, use it to store references to objects with
unknown lifetimes, as an ID will not panic on use if the underlying object has been destroyed.
*/
type ID Object.ID
func (id ID) Instance() (Instance, bool) { return Object.As[Instance](Object.ID(id).Instance()) }
/*
Extension can be embedded in a new struct to create a Go extension of this class.

T must be a type that is embedding this [Extension] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Extension[T gdclass.Interface] struct { gdclass.Extension[T, Instance] }
/*
Singleton can be embedded in a new struct to create a Go singleton extension of the class.

It will become available as a global inside scripts and any any other Go Extension types will
have any *T typed fields filled in to point at this singleton once they have been instantiated.

T must be a type that is embedding this [Singleton] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Singleton[T gdclass.Interface] = Extension[T]
// Instance of the class with convieniently typed arguments and results.
type Instance [1]gdclass.InputEventShortcut
var otype gdextension.ObjectType
var sname gdextension.StringName
var methods struct {
	set_shortcut gdextension.MethodForClass `hash:"857163497"`
	get_shortcut gdextension.MethodForClass `hash:"3766804753"`
}
func init() {
	gd.Links = append(gd.Links, func() {
		sname = gdextension.Host.Strings.Intern.UTF8("InputEventShortcut")
		otype = gdextension.Host.Objects.Type(sname)
		gd.LinkMethods(sname, &methods, false)
		})
	gd.RegisterCleanup(func() {
		noescape.Free(gdextension.TypeStringName, &sname)
	})
}
func (self Instance) ID() ID { return ID(Object.Instance(self.AsObject()).ID()) }
// Nil is a nil/null instance of the class. Equivalent to the zero value.
var Nil Instance
type Any interface {
	gd.IsClass
	AsInputEventShortcut() Instance
}
// Advanced exposes a 1:1 low-level instance of the class, undocumented, for those who know what they are doing.
type Advanced = class
type class [1]gdclass.InputEventShortcut
func (o class) AsObject() [1]gdreference.Object { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (self *class) SetObject(obj [1]gdreference.Object) bool {
	if gdextension.Host.Objects.Cast(gdreference.GetObject(obj[0]), otype) != 0 {
		self[0] = gdclass.NewInputEventShortcut(obj[0])
		return true
	}
	return false
}
func (self *Instance) SetObject(obj [1]gdreference.Object) bool {
	if gdextension.Host.Objects.Cast(gdreference.GetObject(obj[0]), otype) != 0 {
		self[0] = gdclass.NewInputEventShortcut(obj[0])
		return true
	}
	return false
}
func (o Instance) AsObject() [1]gdreference.Object { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (o *Extension[T]) AsObject() [1]gdreference.Object { return o.Super().AsObject() }
func New() Instance {
if !gd.Linked {
		var placeholder = Instance([1]gdclass.InputEventShortcut{gdclass.NewInputEventShortcut(gdreference.NewObject())})
		gd.StartupFunctions = append(gd.StartupFunctions, func() {
			if gd.Linked {
				raw, _ := gdreference.EndObject(New().AsObject()[0])
				gdreference.SetObject(gdclass.GetInputEventShortcut(placeholder[0])[0], raw)
				gd.RegisterCleanup(func() {
					if raw := gdreference.GetObject(placeholder.AsObject()[0]); raw != 0 {
						gdextension.Host.Objects.Unsafe.Free(raw)
					}
				})
			}
		})
		return placeholder
	}
	casted := Instance([1]gdclass.InputEventShortcut{gdclass.NewInputEventShortcut(gdreference.OwnObject(gdextension.Host.Objects.Make(sname), gd.Free))})
	casted.AsRefCounted()[0].InitRef()
	gd.ObjectNotification(casted.AsObject()[0], 0, false)
	return casted
}

func (self Instance) Shortcut() Shortcut.Instance { //gd:InputEventShortcut.shortcut
		return Shortcut.Instance(class(self).GetShortcut())
}

func (o *Extension[T]) Shortcut() Shortcut.Instance { return o.Super().Shortcut() }

// SetShortcut sets the property returned by [GetShortcut]. Returns the instance, so that property settings can be chained.
func (self Instance) SetShortcut(value Shortcut.Instance) Instance { //gd:InputEventShortcut.shortcut
	class(self).SetShortcut(value)
	return self
}

func (o *Extension[T]) SetShortcut(value Shortcut.Instance) *Extension[T] {
	o.Super().SetShortcut(value)
	return o
}

func (self class) SetShortcut(shortcut [1]gdclass.Shortcut)  { //gd:InputEventShortcut.set_shortcut
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_shortcut, 0|(gdextension.SizeObject<<4), &struct{shortcut gdextension.Object}{	gdextension.Object(gdreference.GetObject(gdclass.GetShortcut(shortcut[0])[0]))})
}
func (self class) GetShortcut() [1]gdclass.Shortcut { //gd:InputEventShortcut.get_shortcut
	var r_ret = noescape.Call[gdextension.Object]( gd.ObjectChecked(self.AsObject()), methods.get_shortcut, gdextension.SizeObject, &struct{}{})
	var ret = [1]gdclass.Shortcut{gdclass.NewShortcut(gd.PointerWithOwnershipTransferredToGo(r_ret))}
	return ret
}
func (o class) AsInputEventShortcut() Advanced { return Advanced(o) }
func (o Instance) AsInputEventShortcut() Instance { return o }
func (o *Extension[T]) AsInputEventShortcut() Instance { return o.Super() }
func (o class) AsInputEvent() InputEvent.Advanced { return *(*InputEvent.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsInputEvent() InputEvent.Instance { return o.Super().AsInputEvent() }
func (o Instance) AsInputEvent() InputEvent.Instance { return *(*InputEvent.Instance)(ie.As(&o)) }
func (o class) AsResource() Resource.Advanced { return *(*Resource.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsResource() Resource.Instance { return o.Super().AsResource() }
func (o Instance) AsResource() Resource.Instance { return *(*Resource.Instance)(ie.As(&o)) }
func (o class) AsRefCounted() ie.RC { return *(*ie.RC)(ie.As(&o)) }
func (o *Extension[T]) AsRefCounted() ie.RC { return o.Super().AsRefCounted() }
func (o Instance) AsRefCounted() ie.RC { return *(*ie.RC)(ie.As(&o)) }

// OnChanged is promoted from [Resource.Instance.OnChanged].
func (self Instance) OnChanged(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("changed"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnChanged is promoted from [Resource.Instance.OnChanged].
func (o *Extension[T]) OnChanged(cb func(), flags ...Signal.Flags) *Extension[T] {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(o.AsObject()[0], gd.NewStringName("changed"), gd.NewCallable(cb), int64(flags_together))
	return o
}

// OnSetupLocalToSceneRequested is promoted from [Resource.Instance.OnSetupLocalToSceneRequested].
func (self Instance) OnSetupLocalToSceneRequested(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("setup_local_to_scene_requested"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnSetupLocalToSceneRequested is promoted from [Resource.Instance.OnSetupLocalToSceneRequested].
func (o *Extension[T]) OnSetupLocalToSceneRequested(cb func(), flags ...Signal.Flags) *Extension[T] {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(o.AsObject()[0], gd.NewStringName("setup_local_to_scene_requested"), gd.NewCallable(cb), int64(flags_together))
	return o
}

// IsCanceled is promoted from [InputEvent.Instance.IsCanceled].
func (self Instance) IsCanceled() bool {
	return self.AsInputEvent().IsCanceled()
}

// IsCanceled is promoted from [InputEvent.Instance.IsCanceled].
func (o *Extension[T]) IsCanceled() bool {
	return o.Super().AsInputEvent().IsCanceled()
}

// IsPressed is promoted from [InputEvent.Instance.IsPressed].
func (self Instance) IsPressed() bool {
	return self.AsInputEvent().IsPressed()
}

// IsPressed is promoted from [InputEvent.Instance.IsPressed].
func (o *Extension[T]) IsPressed() bool {
	return o.Super().AsInputEvent().IsPressed()
}

// IsReleased is promoted from [InputEvent.Instance.IsReleased].
func (self Instance) IsReleased() bool {
	return self.AsInputEvent().IsReleased()
}

// IsReleased is promoted from [InputEvent.Instance.IsReleased].
func (o *Extension[T]) IsReleased() bool {
	return o.Super().AsInputEvent().IsReleased()
}

// IsEcho is promoted from [InputEvent.Instance.IsEcho].
func (self Instance) IsEcho() bool {
	return self.AsInputEvent().IsEcho()
}

// IsEcho is promoted from [InputEvent.Instance.IsEcho].
func (o *Extension[T]) IsEcho() bool {
	return o.Super().AsInputEvent().IsEcho()
}

// AsText is promoted from [InputEvent.Instance.AsText].
func (self Instance) AsText() string {
	return self.AsInputEvent().AsText()
}

// AsText is promoted from [InputEvent.Instance.AsText].
func (o *Extension[T]) AsText() string {
	return o.Super().AsInputEvent().AsText()
}

// IsActionType is promoted from [InputEvent.Instance.IsActionType].
func (self Instance) IsActionType() bool {
	return self.AsInputEvent().IsActionType()
}

// IsActionType is promoted from [InputEvent.Instance.IsActionType].
func (o *Extension[T]) IsActionType() bool {
	return o.Super().AsInputEvent().IsActionType()
}

// Accumulate is promoted from [InputEvent.Instance.Accumulate].
func (self Instance) Accumulate(with_event InputEvent.Instance) bool {
	return self.AsInputEvent().Accumulate(with_event)
}

// Accumulate is promoted from [InputEvent.Instance.Accumulate].
func (o *Extension[T]) Accumulate(with_event InputEvent.Instance) bool {
	return o.Super().AsInputEvent().Accumulate(with_event)
}

// TakeOverPath is promoted from [Resource.Instance.TakeOverPath].
func (self Instance) TakeOverPath(path string) {
	self.AsResource().TakeOverPath(path)
}

// TakeOverPath is promoted from [Resource.Instance.TakeOverPath].
func (o *Extension[T]) TakeOverPath(path string) {
	o.Super().AsResource().TakeOverPath(path)
}

// SetPathCache is promoted from [Resource.Instance.SetPathCache].
func (self Instance) SetPathCache(path string) Instance {
	self.AsResource().SetPathCache(path)
	return self
}

// SetPathCache is promoted from [Resource.Instance.SetPathCache].
func (o *Extension[T]) SetPathCache(path string) *Extension[T] {
	o.Super().AsResource().SetPathCache(path)
	return o
}

// GetRid is promoted from [Resource.Instance.GetRid].
func (self Instance) GetRid() Resource.ID {
	return self.AsResource().GetRid()
}

// GetRid is promoted from [Resource.Instance.GetRid].
func (o *Extension[T]) GetRid() Resource.ID {
	return o.Super().AsResource().GetRid()
}

// SetupLocalToScene is promoted from [Resource.Instance.SetupLocalToScene].
func (self Instance) SetupLocalToScene() {
	self.AsResource().SetupLocalToScene()
}

// SetupLocalToScene is promoted from [Resource.Instance.SetupLocalToScene].
func (o *Extension[T]) SetupLocalToScene() {
	o.Super().AsResource().SetupLocalToScene()
}

// ResetState is promoted from [Resource.Instance.ResetState].
func (self Instance) ResetState() {
	self.AsResource().ResetState()
}

// ResetState is promoted from [Resource.Instance.ResetState].
func (o *Extension[T]) ResetState() {
	o.Super().AsResource().ResetState()
}

// SetIdForPath is promoted from [Resource.Instance.SetIdForPath].
func (self Instance) SetIdForPath(path string, id string) Instance {
	self.AsResource().SetIdForPath(path, id)
	return self
}

// SetIdForPath is promoted from [Resource.Instance.SetIdForPath].
func (o *Extension[T]) SetIdForPath(path string, id string) *Extension[T] {
	o.Super().AsResource().SetIdForPath(path, id)
	return o
}

// GetIdForPath is promoted from [Resource.Instance.GetIdForPath].
func (self Instance) GetIdForPath(path string) string {
	return self.AsResource().GetIdForPath(path)
}

// GetIdForPath is promoted from [Resource.Instance.GetIdForPath].
func (o *Extension[T]) GetIdForPath(path string) string {
	return o.Super().AsResource().GetIdForPath(path)
}

// IsBuiltIn is promoted from [Resource.Instance.IsBuiltIn].
func (self Instance) IsBuiltIn() bool {
	return self.AsResource().IsBuiltIn()
}

// IsBuiltIn is promoted from [Resource.Instance.IsBuiltIn].
func (o *Extension[T]) IsBuiltIn() bool {
	return o.Super().AsResource().IsBuiltIn()
}

// EmitChanged is promoted from [Resource.Instance.EmitChanged].
func (self Instance) EmitChanged() {
	self.AsResource().EmitChanged()
}

// EmitChanged is promoted from [Resource.Instance.EmitChanged].
func (o *Extension[T]) EmitChanged() {
	o.Super().AsResource().EmitChanged()
}

// Device is promoted from [InputEvent.Instance.Device].
func (self Instance) Device() int { return self.AsInputEvent().Device() }
func (o *Extension[T]) Device() int { return o.Super().AsInputEvent().Device() }

// SetDevice is promoted from [InputEvent.Instance.SetDevice].
func (self Instance) SetDevice(value int) Instance {
	self.AsInputEvent().SetDevice(value)
	return self
}
func (o *Extension[T]) SetDevice(value int) *Extension[T] {
	o.Super().AsInputEvent().SetDevice(value)
	return o
}

// ResourceLocalToScene is promoted from [Resource.Instance.ResourceLocalToScene].
func (self Instance) ResourceLocalToScene() bool { return self.AsResource().ResourceLocalToScene() }
func (o *Extension[T]) ResourceLocalToScene() bool { return o.Super().AsResource().ResourceLocalToScene() }

// SetResourceLocalToScene is promoted from [Resource.Instance.SetResourceLocalToScene].
func (self Instance) SetResourceLocalToScene(value bool) Instance {
	self.AsResource().SetResourceLocalToScene(value)
	return self
}
func (o *Extension[T]) SetResourceLocalToScene(value bool) *Extension[T] {
	o.Super().AsResource().SetResourceLocalToScene(value)
	return o
}

// ResourcePath is promoted from [Resource.Instance.ResourcePath].
func (self Instance) ResourcePath() string { return self.AsResource().ResourcePath() }
func (o *Extension[T]) ResourcePath() string { return o.Super().AsResource().ResourcePath() }

// SetResourcePath is promoted from [Resource.Instance.SetResourcePath].
func (self Instance) SetResourcePath(value string) Instance {
	self.AsResource().SetResourcePath(value)
	return self
}
func (o *Extension[T]) SetResourcePath(value string) *Extension[T] {
	o.Super().AsResource().SetResourcePath(value)
	return o
}

// ResourceName is promoted from [Resource.Instance.ResourceName].
func (self Instance) ResourceName() string { return self.AsResource().ResourceName() }
func (o *Extension[T]) ResourceName() string { return o.Super().AsResource().ResourceName() }

// SetResourceName is promoted from [Resource.Instance.SetResourceName].
func (self Instance) SetResourceName(value string) Instance {
	self.AsResource().SetResourceName(value)
	return self
}
func (o *Extension[T]) SetResourceName(value string) *Extension[T] {
	o.Super().AsResource().SetResourceName(value)
	return o
}

// ResourceSceneUniqueId is promoted from [Resource.Instance.ResourceSceneUniqueId].
func (self Instance) ResourceSceneUniqueId() string { return self.AsResource().ResourceSceneUniqueId() }
func (o *Extension[T]) ResourceSceneUniqueId() string { return o.Super().AsResource().ResourceSceneUniqueId() }

// SetResourceSceneUniqueId is promoted from [Resource.Instance.SetResourceSceneUniqueId].
func (self Instance) SetResourceSceneUniqueId(value string) Instance {
	self.AsResource().SetResourceSceneUniqueId(value)
	return self
}
func (o *Extension[T]) SetResourceSceneUniqueId(value string) *Extension[T] {
	o.Super().AsResource().SetResourceSceneUniqueId(value)
	return o
}

func (self class) Virtual(name string) reflect.Value {
	switch name {
	default: return gd.VirtualByName(InputEvent.Advanced(self.AsInputEvent()), name)
	}
}

func (self Instance) Virtual(name string) reflect.Value {
	switch name {
	default: return gd.VirtualByName(InputEvent.Instance(self.AsInputEvent()), name)
	}
}
func init() {gdclass.Register("InputEventShortcut", func(ptr gdreference.Object) any { return Instance{gdclass.NewInputEventShortcut(ptr)} })}
