// Code generated by the generate package DO NOT EDIT


package CharacterBody2D

import "reflect"
import "slices"
import "graphics.gd/internal/pointers"
import "graphics.gd/internal/callframe"
import "graphics.gd/internal/gdextension"
import "graphics.gd/internal/gdreference"
import "graphics.gd/internal/noescape"
import gd "graphics.gd/internal"
import "graphics.gd/internal/gdclass"
import "graphics.gd/internal/ie"
import "graphics.gd/variant"
import "graphics.gd/variant/Angle"
import "graphics.gd/variant/Euler"
import "graphics.gd/variant/Signal"
import "graphics.gd/classdb/CanvasItem"
import "graphics.gd/classdb/CollisionObject2D"
import "graphics.gd/classdb/InputEvent"
import "graphics.gd/classdb/KinematicCollision2D"
import "graphics.gd/classdb/Node"
import "graphics.gd/classdb/Node2D"
import "graphics.gd/classdb/PhysicsBody2D"
import "graphics.gd/variant/Array"
import "graphics.gd/variant/Callable"
import "graphics.gd/variant/Dictionary"
import "graphics.gd/variant/Error"
import "graphics.gd/variant/Float"
import "graphics.gd/variant/Object"
import "graphics.gd/variant/Packed"
import "graphics.gd/variant/Path"
import "graphics.gd/variant/RID"
import "graphics.gd/variant/RefCounted"
import "graphics.gd/variant/String"
import "graphics.gd/variant/Vector2"

var _ Object.ID
type _ gdclass.Node
var _ gd.String
var _ RefCounted.Instance
var _ reflect.Type
var _ callframe.Frame
var _ = pointers.Cycle
var _ = Array.Nil
var _ variant.Any
var _ Callable.Function
var _ Dictionary.Any
var _ RID.Any
var _ noescape.Variant
var _ String.Readable
var _ Path.ToNode
var _ Packed.Bytes
var _ Error.Code
var _ Float.X
var _ Signal.Any
var _ Angle.Radians
var _ Euler.Radians
var _ gdextension.Object
var _ = slices.Delete[[]struct{}, struct{}]

/*
ID is a typed object ID (reference) to an instance of this class, use it to store references to objects with
unknown lifetimes, as an ID will not panic on use if the underlying object has been destroyed.
*/
type ID Object.ID
func (id ID) Instance() (Instance, bool) { return Object.As[Instance](Object.ID(id).Instance()) }
/*
Extension can be embedded in a new struct to create a Go extension of this class.

T must be a type that is embedding this [Extension] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Extension[T gdclass.Interface] struct { gdclass.Extension[T, Instance] }
/*
Singleton can be embedded in a new struct to create a Go singleton extension of the class.

It will become available as a global inside scripts and any any other Go Extension types will
have any *T typed fields filled in to point at this singleton once they have been instantiated.

T must be a type that is embedding this [Singleton] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Singleton[T gdclass.Interface] = Extension[T]
// Instance of the class with convieniently typed arguments and results.
type Instance [1]gdclass.CharacterBody2D
var otype gdextension.ObjectType
var sname gdextension.StringName
var methods struct {
	move_and_slide gdextension.MethodForClass `hash:"2240911060"`
	apply_floor_snap gdextension.MethodForClass `hash:"3218959716"`
	set_velocity gdextension.MethodForClass `hash:"743155724"`
	get_velocity gdextension.MethodForClass `hash:"3341600327"`
	set_safe_margin gdextension.MethodForClass `hash:"373806689"`
	get_safe_margin gdextension.MethodForClass `hash:"1740695150"`
	is_floor_stop_on_slope_enabled gdextension.MethodForClass `hash:"36873697"`
	set_floor_stop_on_slope_enabled gdextension.MethodForClass `hash:"2586408642"`
	set_floor_constant_speed_enabled gdextension.MethodForClass `hash:"2586408642"`
	is_floor_constant_speed_enabled gdextension.MethodForClass `hash:"36873697"`
	set_floor_block_on_wall_enabled gdextension.MethodForClass `hash:"2586408642"`
	is_floor_block_on_wall_enabled gdextension.MethodForClass `hash:"36873697"`
	set_slide_on_ceiling_enabled gdextension.MethodForClass `hash:"2586408642"`
	is_slide_on_ceiling_enabled gdextension.MethodForClass `hash:"36873697"`
	set_platform_floor_layers gdextension.MethodForClass `hash:"1286410249"`
	get_platform_floor_layers gdextension.MethodForClass `hash:"3905245786"`
	set_platform_wall_layers gdextension.MethodForClass `hash:"1286410249"`
	get_platform_wall_layers gdextension.MethodForClass `hash:"3905245786"`
	get_max_slides gdextension.MethodForClass `hash:"3905245786"`
	set_max_slides gdextension.MethodForClass `hash:"1286410249"`
	get_floor_max_angle gdextension.MethodForClass `hash:"1740695150"`
	set_floor_max_angle gdextension.MethodForClass `hash:"373806689"`
	get_floor_snap_length gdextension.MethodForClass `hash:"191475506"`
	set_floor_snap_length gdextension.MethodForClass `hash:"373806689"`
	get_wall_min_slide_angle gdextension.MethodForClass `hash:"1740695150"`
	set_wall_min_slide_angle gdextension.MethodForClass `hash:"373806689"`
	get_up_direction gdextension.MethodForClass `hash:"3341600327"`
	set_up_direction gdextension.MethodForClass `hash:"743155724"`
	set_motion_mode gdextension.MethodForClass `hash:"1224392233"`
	get_motion_mode gdextension.MethodForClass `hash:"1160151236"`
	set_platform_on_leave gdextension.MethodForClass `hash:"2423324375"`
	get_platform_on_leave gdextension.MethodForClass `hash:"4054324341"`
	is_on_floor gdextension.MethodForClass `hash:"36873697"`
	is_on_floor_only gdextension.MethodForClass `hash:"36873697"`
	is_on_ceiling gdextension.MethodForClass `hash:"36873697"`
	is_on_ceiling_only gdextension.MethodForClass `hash:"36873697"`
	is_on_wall gdextension.MethodForClass `hash:"36873697"`
	is_on_wall_only gdextension.MethodForClass `hash:"36873697"`
	get_floor_normal gdextension.MethodForClass `hash:"3341600327"`
	get_wall_normal gdextension.MethodForClass `hash:"3341600327"`
	get_last_motion gdextension.MethodForClass `hash:"3341600327"`
	get_position_delta gdextension.MethodForClass `hash:"3341600327"`
	get_real_velocity gdextension.MethodForClass `hash:"3341600327"`
	get_floor_angle gdextension.MethodForClass `hash:"2841063350"`
	get_platform_velocity gdextension.MethodForClass `hash:"3341600327"`
	get_slide_collision_count gdextension.MethodForClass `hash:"3905245786"`
	get_slide_collision gdextension.MethodForClass `hash:"860659811"`
	get_last_slide_collision gdextension.MethodForClass `hash:"2161834755"`
}
func init() {
	gd.Links = append(gd.Links, func() {
		sname = gdextension.Host.Strings.Intern.UTF8("CharacterBody2D")
		otype = gdextension.Host.Objects.Type(sname)
		gd.LinkMethods(sname, &methods, false)
		})
	gd.RegisterCleanup(func() {
		noescape.Free(gdextension.TypeStringName, &sname)
	})
}
func (self Instance) ID() ID { return ID(Object.Instance(self.AsObject()).ID()) }
// MoreArgs is a container for [Instance] functions with additional 'optional' arguments.
type MoreArgs [1]gdclass.CharacterBody2D
type Expanded = MoreArgs
// MoreArgs enables certain functions to be called with additional 'optional' arguments.
func (self Instance) MoreArgs() MoreArgs { return MoreArgs(self) }
// Nil is a nil/null instance of the class. Equivalent to the zero value.
var Nil Instance
type Any interface {
	gd.IsClass
	AsCharacterBody2D() Instance
}
func (self Instance) MoveAndSlide() bool { //gd:CharacterBody2D.move_and_slide
	return bool(Advanced(self).MoveAndSlide())
}
func (self Instance) ApplyFloorSnap() { //gd:CharacterBody2D.apply_floor_snap
	Advanced(self).ApplyFloorSnap()
}
func (self Instance) IsOnFloor() bool { //gd:CharacterBody2D.is_on_floor
	return bool(Advanced(self).IsOnFloor())
}
func (self Instance) IsOnFloorOnly() bool { //gd:CharacterBody2D.is_on_floor_only
	return bool(Advanced(self).IsOnFloorOnly())
}
func (self Instance) IsOnCeiling() bool { //gd:CharacterBody2D.is_on_ceiling
	return bool(Advanced(self).IsOnCeiling())
}
func (self Instance) IsOnCeilingOnly() bool { //gd:CharacterBody2D.is_on_ceiling_only
	return bool(Advanced(self).IsOnCeilingOnly())
}
func (self Instance) IsOnWall() bool { //gd:CharacterBody2D.is_on_wall
	return bool(Advanced(self).IsOnWall())
}
func (self Instance) IsOnWallOnly() bool { //gd:CharacterBody2D.is_on_wall_only
	return bool(Advanced(self).IsOnWallOnly())
}
func (self Instance) GetFloorNormal() Vector2.XY { //gd:CharacterBody2D.get_floor_normal
	return Vector2.XY(Advanced(self).GetFloorNormal())
}
func (self Instance) GetWallNormal() Vector2.XY { //gd:CharacterBody2D.get_wall_normal
	return Vector2.XY(Advanced(self).GetWallNormal())
}
func (self Instance) GetLastMotion() Vector2.XY { //gd:CharacterBody2D.get_last_motion
	return Vector2.XY(Advanced(self).GetLastMotion())
}
func (self Instance) GetPositionDelta() Vector2.XY { //gd:CharacterBody2D.get_position_delta
	return Vector2.XY(Advanced(self).GetPositionDelta())
}
func (self Instance) GetRealVelocity() Vector2.XY { //gd:CharacterBody2D.get_real_velocity
	return Vector2.XY(Advanced(self).GetRealVelocity())
}
func (self Instance) GetFloorAngle() Angle.Radians { //gd:CharacterBody2D.get_floor_angle
	return Angle.Radians(Float.X(Advanced(self).GetFloorAngle(Vector2.XY(gd.Vector2{0, -1}))))
}
func (self MoreArgs) GetFloorAngle(up_direction Vector2.XY) Angle.Radians { //gd:CharacterBody2D.get_floor_angle
	return Angle.Radians(Float.X(Advanced(self).GetFloorAngle(Vector2.XY(up_direction))))
}
func (self Instance) GetPlatformVelocity() Vector2.XY { //gd:CharacterBody2D.get_platform_velocity
	return Vector2.XY(Advanced(self).GetPlatformVelocity())
}
func (self Instance) GetSlideCollisionCount() int { //gd:CharacterBody2D.get_slide_collision_count
	return int(int(Advanced(self).GetSlideCollisionCount()))
}
func (self Instance) GetSlideCollision(slide_idx int) KinematicCollision2D.Instance { //gd:CharacterBody2D.get_slide_collision
	return KinematicCollision2D.Instance(Advanced(self).GetSlideCollision(int64(slide_idx)))
}
func (self Instance) GetLastSlideCollision() KinematicCollision2D.Instance { //gd:CharacterBody2D.get_last_slide_collision
	return KinematicCollision2D.Instance(Advanced(self).GetLastSlideCollision())
}
// Advanced exposes a 1:1 low-level instance of the class, undocumented, for those who know what they are doing.
type Advanced = class
type class [1]gdclass.CharacterBody2D
func (o class) AsObject() [1]gdreference.Object { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (self *class) SetObject(obj [1]gdreference.Object) bool {
	if gdextension.Host.Objects.Cast(gdreference.GetObject(obj[0]), otype) != 0 {
		self[0] = gdclass.NewCharacterBody2D(obj[0])
		return true
	}
	return false
}
func (self *Instance) SetObject(obj [1]gdreference.Object) bool {
	if gdextension.Host.Objects.Cast(gdreference.GetObject(obj[0]), otype) != 0 {
		self[0] = gdclass.NewCharacterBody2D(obj[0])
		return true
	}
	return false
}
func (o Instance) AsObject() [1]gdreference.Object { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (o *Extension[T]) AsObject() [1]gdreference.Object { return o.Super().AsObject() }
func New() Instance {
if !gd.Linked {
		var placeholder = Instance([1]gdclass.CharacterBody2D{gdclass.NewCharacterBody2D(gdreference.NewObject())})
		gd.StartupFunctions = append(gd.StartupFunctions, func() {
			if gd.Linked {
				raw, _ := gdreference.EndObject(New().AsObject()[0])
				gdreference.SetObject(gdclass.GetCharacterBody2D(placeholder[0])[0], raw)
				gd.RegisterCleanup(func() {
					if raw := gdreference.GetObject(placeholder.AsObject()[0]); raw != 0 {
						gdextension.Host.Objects.Unsafe.Free(raw)
					}
				})
			}
		})
		return placeholder
	}
	casted := Instance([1]gdclass.CharacterBody2D{gdclass.NewCharacterBody2D(gdreference.OwnObject(gdextension.Host.Objects.Make(sname), gd.Free))})
	gd.ObjectNotification(casted.AsObject()[0], 0, false)
	return casted
}

func (self Instance) MotionMode() MotionMode { //gd:CharacterBody2D.motion_mode
		return MotionMode(class(self).GetMotionMode())
}

// SetMotionMode sets the property returned by [GetMotionMode]. Returns the instance, so that property settings can be chained.
func (self Instance) SetMotionMode(value MotionMode) Instance { //gd:CharacterBody2D.motion_mode
	class(self).SetMotionMode(value)
	return self
}

func (self Instance) UpDirection() Vector2.XY { //gd:CharacterBody2D.up_direction
		return Vector2.XY(class(self).GetUpDirection())
}

// SetUpDirection sets the property returned by [GetUpDirection]. Returns the instance, so that property settings can be chained.
func (self Instance) SetUpDirection(value Vector2.XY) Instance { //gd:CharacterBody2D.up_direction
	class(self).SetUpDirection(Vector2.XY(value))
	return self
}

func (self Instance) Velocity() Vector2.XY { //gd:CharacterBody2D.velocity
		return Vector2.XY(class(self).GetVelocity())
}

// SetVelocity sets the property returned by [GetVelocity]. Returns the instance, so that property settings can be chained.
func (self Instance) SetVelocity(value Vector2.XY) Instance { //gd:CharacterBody2D.velocity
	class(self).SetVelocity(Vector2.XY(value))
	return self
}

func (self Instance) SlideOnCeiling() bool { //gd:CharacterBody2D.slide_on_ceiling
		return bool(class(self).IsSlideOnCeilingEnabled())
}

// SetSlideOnCeiling sets the property returned by [IsSlideOnCeilingEnabled]. Returns the instance, so that property settings can be chained.
func (self Instance) SetSlideOnCeiling(value bool) Instance { //gd:CharacterBody2D.slide_on_ceiling
	class(self).SetSlideOnCeilingEnabled(value)
	return self
}

func (self Instance) MaxSlides() int { //gd:CharacterBody2D.max_slides
		return int(int(class(self).GetMaxSlides()))
}

// SetMaxSlides sets the property returned by [GetMaxSlides]. Returns the instance, so that property settings can be chained.
func (self Instance) SetMaxSlides(value int) Instance { //gd:CharacterBody2D.max_slides
	class(self).SetMaxSlides(int64(value))
	return self
}

func (self Instance) WallMinSlideAngle() Angle.Radians { //gd:CharacterBody2D.wall_min_slide_angle
		return Angle.Radians(Float.X(class(self).GetWallMinSlideAngle()))
}

// SetWallMinSlideAngle sets the property returned by [GetWallMinSlideAngle]. Returns the instance, so that property settings can be chained.
func (self Instance) SetWallMinSlideAngle(value Angle.Radians) Instance { //gd:CharacterBody2D.wall_min_slide_angle
	class(self).SetWallMinSlideAngle(float64(value))
	return self
}

func (self Instance) FloorStopOnSlope() bool { //gd:CharacterBody2D.floor_stop_on_slope
		return bool(class(self).IsFloorStopOnSlopeEnabled())
}

// SetFloorStopOnSlope sets the property returned by [IsFloorStopOnSlopeEnabled]. Returns the instance, so that property settings can be chained.
func (self Instance) SetFloorStopOnSlope(value bool) Instance { //gd:CharacterBody2D.floor_stop_on_slope
	class(self).SetFloorStopOnSlopeEnabled(value)
	return self
}

func (self Instance) FloorConstantSpeed() bool { //gd:CharacterBody2D.floor_constant_speed
		return bool(class(self).IsFloorConstantSpeedEnabled())
}

// SetFloorConstantSpeed sets the property returned by [IsFloorConstantSpeedEnabled]. Returns the instance, so that property settings can be chained.
func (self Instance) SetFloorConstantSpeed(value bool) Instance { //gd:CharacterBody2D.floor_constant_speed
	class(self).SetFloorConstantSpeedEnabled(value)
	return self
}

func (self Instance) FloorBlockOnWall() bool { //gd:CharacterBody2D.floor_block_on_wall
		return bool(class(self).IsFloorBlockOnWallEnabled())
}

// SetFloorBlockOnWall sets the property returned by [IsFloorBlockOnWallEnabled]. Returns the instance, so that property settings can be chained.
func (self Instance) SetFloorBlockOnWall(value bool) Instance { //gd:CharacterBody2D.floor_block_on_wall
	class(self).SetFloorBlockOnWallEnabled(value)
	return self
}

func (self Instance) FloorMaxAngle() Angle.Radians { //gd:CharacterBody2D.floor_max_angle
		return Angle.Radians(Float.X(class(self).GetFloorMaxAngle()))
}

// SetFloorMaxAngle sets the property returned by [GetFloorMaxAngle]. Returns the instance, so that property settings can be chained.
func (self Instance) SetFloorMaxAngle(value Angle.Radians) Instance { //gd:CharacterBody2D.floor_max_angle
	class(self).SetFloorMaxAngle(float64(value))
	return self
}

func (self Instance) FloorSnapLength() Float.X { //gd:CharacterBody2D.floor_snap_length
		return Float.X(Float.X(class(self).GetFloorSnapLength()))
}

// SetFloorSnapLength sets the property returned by [GetFloorSnapLength]. Returns the instance, so that property settings can be chained.
func (self Instance) SetFloorSnapLength(value Float.X) Instance { //gd:CharacterBody2D.floor_snap_length
	class(self).SetFloorSnapLength(float64(value))
	return self
}

func (self Instance) PlatformOnLeave() PlatformOnLeave { //gd:CharacterBody2D.platform_on_leave
		return PlatformOnLeave(class(self).GetPlatformOnLeave())
}

// SetPlatformOnLeave sets the property returned by [GetPlatformOnLeave]. Returns the instance, so that property settings can be chained.
func (self Instance) SetPlatformOnLeave(value PlatformOnLeave) Instance { //gd:CharacterBody2D.platform_on_leave
	class(self).SetPlatformOnLeave(value)
	return self
}

func (self Instance) PlatformFloorLayers() int { //gd:CharacterBody2D.platform_floor_layers
		return int(int(class(self).GetPlatformFloorLayers()))
}

// SetPlatformFloorLayers sets the property returned by [GetPlatformFloorLayers]. Returns the instance, so that property settings can be chained.
func (self Instance) SetPlatformFloorLayers(value int) Instance { //gd:CharacterBody2D.platform_floor_layers
	class(self).SetPlatformFloorLayers(int64(value))
	return self
}

func (self Instance) PlatformWallLayers() int { //gd:CharacterBody2D.platform_wall_layers
		return int(int(class(self).GetPlatformWallLayers()))
}

// SetPlatformWallLayers sets the property returned by [GetPlatformWallLayers]. Returns the instance, so that property settings can be chained.
func (self Instance) SetPlatformWallLayers(value int) Instance { //gd:CharacterBody2D.platform_wall_layers
	class(self).SetPlatformWallLayers(int64(value))
	return self
}

func (self Instance) SafeMargin() Float.X { //gd:CharacterBody2D.safe_margin
		return Float.X(Float.X(class(self).GetSafeMargin()))
}

// SetSafeMargin sets the property returned by [GetSafeMargin]. Returns the instance, so that property settings can be chained.
func (self Instance) SetSafeMargin(value Float.X) Instance { //gd:CharacterBody2D.safe_margin
	class(self).SetSafeMargin(float64(value))
	return self
}

func (self class) MoveAndSlide() bool { //gd:CharacterBody2D.move_and_slide
	var r_ret = noescape.Call[bool]( gd.ObjectChecked(self.AsObject()), methods.move_and_slide, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) ApplyFloorSnap()  { //gd:CharacterBody2D.apply_floor_snap
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.apply_floor_snap, 0, &struct{}{})
}
func (self class) SetVelocity(velocity Vector2.XY)  { //gd:CharacterBody2D.set_velocity
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_velocity, 0|(gdextension.SizeVector2<<4), &struct{velocity Vector2.XY}{velocity})
}
func (self class) GetVelocity() Vector2.XY { //gd:CharacterBody2D.get_velocity
	var r_ret = noescape.Call[Vector2.XY]( gd.ObjectChecked(self.AsObject()), methods.get_velocity, gdextension.SizeVector2, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetSafeMargin(margin float64)  { //gd:CharacterBody2D.set_safe_margin
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_safe_margin, 0|(gdextension.SizeFloat<<4), &struct{margin float64}{margin})
}
func (self class) GetSafeMargin() float64 { //gd:CharacterBody2D.get_safe_margin
	var r_ret = noescape.Call[float64]( gd.ObjectChecked(self.AsObject()), methods.get_safe_margin, gdextension.SizeFloat, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) IsFloorStopOnSlopeEnabled() bool { //gd:CharacterBody2D.is_floor_stop_on_slope_enabled
	var r_ret = noescape.Call[bool]( gd.ObjectChecked(self.AsObject()), methods.is_floor_stop_on_slope_enabled, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetFloorStopOnSlopeEnabled(enabled bool)  { //gd:CharacterBody2D.set_floor_stop_on_slope_enabled
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_floor_stop_on_slope_enabled, 0|(gdextension.SizeBool<<4), &struct{enabled bool}{enabled})
}
func (self class) SetFloorConstantSpeedEnabled(enabled bool)  { //gd:CharacterBody2D.set_floor_constant_speed_enabled
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_floor_constant_speed_enabled, 0|(gdextension.SizeBool<<4), &struct{enabled bool}{enabled})
}
func (self class) IsFloorConstantSpeedEnabled() bool { //gd:CharacterBody2D.is_floor_constant_speed_enabled
	var r_ret = noescape.Call[bool]( gd.ObjectChecked(self.AsObject()), methods.is_floor_constant_speed_enabled, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetFloorBlockOnWallEnabled(enabled bool)  { //gd:CharacterBody2D.set_floor_block_on_wall_enabled
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_floor_block_on_wall_enabled, 0|(gdextension.SizeBool<<4), &struct{enabled bool}{enabled})
}
func (self class) IsFloorBlockOnWallEnabled() bool { //gd:CharacterBody2D.is_floor_block_on_wall_enabled
	var r_ret = noescape.Call[bool]( gd.ObjectChecked(self.AsObject()), methods.is_floor_block_on_wall_enabled, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetSlideOnCeilingEnabled(enabled bool)  { //gd:CharacterBody2D.set_slide_on_ceiling_enabled
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_slide_on_ceiling_enabled, 0|(gdextension.SizeBool<<4), &struct{enabled bool}{enabled})
}
func (self class) IsSlideOnCeilingEnabled() bool { //gd:CharacterBody2D.is_slide_on_ceiling_enabled
	var r_ret = noescape.Call[bool]( gd.ObjectChecked(self.AsObject()), methods.is_slide_on_ceiling_enabled, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetPlatformFloorLayers(exclude_layer int64)  { //gd:CharacterBody2D.set_platform_floor_layers
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_platform_floor_layers, 0|(gdextension.SizeInt<<4), &struct{exclude_layer int64}{exclude_layer})
}
func (self class) GetPlatformFloorLayers() int64 { //gd:CharacterBody2D.get_platform_floor_layers
	var r_ret = noescape.Call[int64]( gd.ObjectChecked(self.AsObject()), methods.get_platform_floor_layers, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetPlatformWallLayers(exclude_layer int64)  { //gd:CharacterBody2D.set_platform_wall_layers
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_platform_wall_layers, 0|(gdextension.SizeInt<<4), &struct{exclude_layer int64}{exclude_layer})
}
func (self class) GetPlatformWallLayers() int64 { //gd:CharacterBody2D.get_platform_wall_layers
	var r_ret = noescape.Call[int64]( gd.ObjectChecked(self.AsObject()), methods.get_platform_wall_layers, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) GetMaxSlides() int64 { //gd:CharacterBody2D.get_max_slides
	var r_ret = noescape.Call[int64]( gd.ObjectChecked(self.AsObject()), methods.get_max_slides, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetMaxSlides(max_slides int64)  { //gd:CharacterBody2D.set_max_slides
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_max_slides, 0|(gdextension.SizeInt<<4), &struct{max_slides int64}{max_slides})
}
func (self class) GetFloorMaxAngle() float64 { //gd:CharacterBody2D.get_floor_max_angle
	var r_ret = noescape.Call[float64]( gd.ObjectChecked(self.AsObject()), methods.get_floor_max_angle, gdextension.SizeFloat, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetFloorMaxAngle(radians float64)  { //gd:CharacterBody2D.set_floor_max_angle
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_floor_max_angle, 0|(gdextension.SizeFloat<<4), &struct{radians float64}{radians})
}
func (self class) GetFloorSnapLength() float64 { //gd:CharacterBody2D.get_floor_snap_length
	var r_ret = noescape.Call[float64]( gd.ObjectChecked(self.AsObject()), methods.get_floor_snap_length, gdextension.SizeFloat, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetFloorSnapLength(floor_snap_length float64)  { //gd:CharacterBody2D.set_floor_snap_length
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_floor_snap_length, 0|(gdextension.SizeFloat<<4), &struct{floor_snap_length float64}{floor_snap_length})
}
func (self class) GetWallMinSlideAngle() float64 { //gd:CharacterBody2D.get_wall_min_slide_angle
	var r_ret = noescape.Call[float64]( gd.ObjectChecked(self.AsObject()), methods.get_wall_min_slide_angle, gdextension.SizeFloat, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetWallMinSlideAngle(radians float64)  { //gd:CharacterBody2D.set_wall_min_slide_angle
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_wall_min_slide_angle, 0|(gdextension.SizeFloat<<4), &struct{radians float64}{radians})
}
func (self class) GetUpDirection() Vector2.XY { //gd:CharacterBody2D.get_up_direction
	var r_ret = noescape.Call[Vector2.XY]( gd.ObjectChecked(self.AsObject()), methods.get_up_direction, gdextension.SizeVector2, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetUpDirection(up_direction Vector2.XY)  { //gd:CharacterBody2D.set_up_direction
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_up_direction, 0|(gdextension.SizeVector2<<4), &struct{up_direction Vector2.XY}{up_direction})
}
func (self class) SetMotionMode(mode MotionMode)  { //gd:CharacterBody2D.set_motion_mode
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_motion_mode, 0|(gdextension.SizeInt<<4), &struct{mode MotionMode}{mode})
}
func (self class) GetMotionMode() MotionMode { //gd:CharacterBody2D.get_motion_mode
	var r_ret = noescape.Call[MotionMode]( gd.ObjectChecked(self.AsObject()), methods.get_motion_mode, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetPlatformOnLeave(on_leave_apply_velocity PlatformOnLeave)  { //gd:CharacterBody2D.set_platform_on_leave
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_platform_on_leave, 0|(gdextension.SizeInt<<4), &struct{on_leave_apply_velocity PlatformOnLeave}{on_leave_apply_velocity})
}
func (self class) GetPlatformOnLeave() PlatformOnLeave { //gd:CharacterBody2D.get_platform_on_leave
	var r_ret = noescape.Call[PlatformOnLeave]( gd.ObjectChecked(self.AsObject()), methods.get_platform_on_leave, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) IsOnFloor() bool { //gd:CharacterBody2D.is_on_floor
	var r_ret = noescape.Call[bool]( gd.ObjectChecked(self.AsObject()), methods.is_on_floor, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) IsOnFloorOnly() bool { //gd:CharacterBody2D.is_on_floor_only
	var r_ret = noescape.Call[bool]( gd.ObjectChecked(self.AsObject()), methods.is_on_floor_only, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) IsOnCeiling() bool { //gd:CharacterBody2D.is_on_ceiling
	var r_ret = noescape.Call[bool]( gd.ObjectChecked(self.AsObject()), methods.is_on_ceiling, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) IsOnCeilingOnly() bool { //gd:CharacterBody2D.is_on_ceiling_only
	var r_ret = noescape.Call[bool]( gd.ObjectChecked(self.AsObject()), methods.is_on_ceiling_only, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) IsOnWall() bool { //gd:CharacterBody2D.is_on_wall
	var r_ret = noescape.Call[bool]( gd.ObjectChecked(self.AsObject()), methods.is_on_wall, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) IsOnWallOnly() bool { //gd:CharacterBody2D.is_on_wall_only
	var r_ret = noescape.Call[bool]( gd.ObjectChecked(self.AsObject()), methods.is_on_wall_only, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) GetFloorNormal() Vector2.XY { //gd:CharacterBody2D.get_floor_normal
	var r_ret = noescape.Call[Vector2.XY]( gd.ObjectChecked(self.AsObject()), methods.get_floor_normal, gdextension.SizeVector2, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) GetWallNormal() Vector2.XY { //gd:CharacterBody2D.get_wall_normal
	var r_ret = noescape.Call[Vector2.XY]( gd.ObjectChecked(self.AsObject()), methods.get_wall_normal, gdextension.SizeVector2, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) GetLastMotion() Vector2.XY { //gd:CharacterBody2D.get_last_motion
	var r_ret = noescape.Call[Vector2.XY]( gd.ObjectChecked(self.AsObject()), methods.get_last_motion, gdextension.SizeVector2, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) GetPositionDelta() Vector2.XY { //gd:CharacterBody2D.get_position_delta
	var r_ret = noescape.Call[Vector2.XY]( gd.ObjectChecked(self.AsObject()), methods.get_position_delta, gdextension.SizeVector2, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) GetRealVelocity() Vector2.XY { //gd:CharacterBody2D.get_real_velocity
	var r_ret = noescape.Call[Vector2.XY]( gd.ObjectChecked(self.AsObject()), methods.get_real_velocity, gdextension.SizeVector2, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) GetFloorAngle(up_direction Vector2.XY) float64 { //gd:CharacterBody2D.get_floor_angle
	var r_ret = noescape.Call[float64]( gd.ObjectChecked(self.AsObject()), methods.get_floor_angle, gdextension.SizeFloat|(gdextension.SizeVector2<<4), &struct{up_direction Vector2.XY}{up_direction})
	var ret = r_ret
	return ret
}
func (self class) GetPlatformVelocity() Vector2.XY { //gd:CharacterBody2D.get_platform_velocity
	var r_ret = noescape.Call[Vector2.XY]( gd.ObjectChecked(self.AsObject()), methods.get_platform_velocity, gdextension.SizeVector2, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) GetSlideCollisionCount() int64 { //gd:CharacterBody2D.get_slide_collision_count
	var r_ret = noescape.Call[int64]( gd.ObjectChecked(self.AsObject()), methods.get_slide_collision_count, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) GetSlideCollision(slide_idx int64) [1]gdclass.KinematicCollision2D { //gd:CharacterBody2D.get_slide_collision
	var r_ret = noescape.Call[gdextension.Object]( gd.ObjectChecked(self.AsObject()), methods.get_slide_collision, gdextension.SizeObject|(gdextension.SizeInt<<4), &struct{slide_idx int64}{slide_idx})
	var ret = [1]gdclass.KinematicCollision2D{gdclass.NewKinematicCollision2D(gd.PointerWithOwnershipTransferredToGo(r_ret))}
	return ret
}
func (self class) GetLastSlideCollision() [1]gdclass.KinematicCollision2D { //gd:CharacterBody2D.get_last_slide_collision
	var r_ret = noescape.Call[gdextension.Object]( gd.ObjectChecked(self.AsObject()), methods.get_last_slide_collision, gdextension.SizeObject, &struct{}{})
	var ret = [1]gdclass.KinematicCollision2D{gdclass.NewKinematicCollision2D(gd.PointerWithOwnershipTransferredToGo(r_ret))}
	return ret
}
func (o class) AsCharacterBody2D() Advanced { return Advanced(o) }
func (o Instance) AsCharacterBody2D() Instance { return o }
func (o *Extension[T]) AsCharacterBody2D() Instance { return o.Super() }
func (o class) AsPhysicsBody2D() PhysicsBody2D.Advanced { return *(*PhysicsBody2D.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsPhysicsBody2D() PhysicsBody2D.Instance { return o.Super().AsPhysicsBody2D() }
func (o Instance) AsPhysicsBody2D() PhysicsBody2D.Instance { return *(*PhysicsBody2D.Instance)(ie.As(&o)) }
func (o class) AsCollisionObject2D() CollisionObject2D.Advanced { return *(*CollisionObject2D.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsCollisionObject2D() CollisionObject2D.Instance { return o.Super().AsCollisionObject2D() }
func (o Instance) AsCollisionObject2D() CollisionObject2D.Instance { return *(*CollisionObject2D.Instance)(ie.As(&o)) }
func (o class) AsNode2D() Node2D.Advanced { return *(*Node2D.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsNode2D() Node2D.Instance { return o.Super().AsNode2D() }
func (o Instance) AsNode2D() Node2D.Instance { return *(*Node2D.Instance)(ie.As(&o)) }
func (o class) AsCanvasItem() CanvasItem.Advanced { return *(*CanvasItem.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsCanvasItem() CanvasItem.Instance { return o.Super().AsCanvasItem() }
func (o Instance) AsCanvasItem() CanvasItem.Instance { return *(*CanvasItem.Instance)(ie.As(&o)) }
func (o class) AsNode() Node.Advanced { return *(*Node.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsNode() Node.Instance { return o.Super().AsNode() }
func (o Instance) AsNode() Node.Instance { return *(*Node.Instance)(ie.As(&o)) }

// OnInputEvent is promoted from [CollisionObject2D.Instance.OnInputEvent].
func (self Instance) OnInputEvent(cb func(viewport Node.Instance, event InputEvent.Instance, shape_idx int), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("input_event"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnMouseEntered is promoted from [CollisionObject2D.Instance.OnMouseEntered].
func (self Instance) OnMouseEntered(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("mouse_entered"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnMouseExited is promoted from [CollisionObject2D.Instance.OnMouseExited].
func (self Instance) OnMouseExited(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("mouse_exited"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnMouseShapeEntered is promoted from [CollisionObject2D.Instance.OnMouseShapeEntered].
func (self Instance) OnMouseShapeEntered(cb func(shape_idx int), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("mouse_shape_entered"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnMouseShapeExited is promoted from [CollisionObject2D.Instance.OnMouseShapeExited].
func (self Instance) OnMouseShapeExited(cb func(shape_idx int), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("mouse_shape_exited"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnDraw is promoted from [CanvasItem.Instance.OnDraw].
func (self Instance) OnDraw(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("draw"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnVisibilityChanged is promoted from [CanvasItem.Instance.OnVisibilityChanged].
func (self Instance) OnVisibilityChanged(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("visibility_changed"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnHidden is promoted from [CanvasItem.Instance.OnHidden].
func (self Instance) OnHidden(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("hidden"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnItemRectChanged is promoted from [CanvasItem.Instance.OnItemRectChanged].
func (self Instance) OnItemRectChanged(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("item_rect_changed"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnReady is promoted from [Node.Instance.OnReady].
func (self Instance) OnReady(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("ready"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnRenamed is promoted from [Node.Instance.OnRenamed].
func (self Instance) OnRenamed(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("renamed"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnTreeEntered is promoted from [Node.Instance.OnTreeEntered].
func (self Instance) OnTreeEntered(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("tree_entered"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnTreeExiting is promoted from [Node.Instance.OnTreeExiting].
func (self Instance) OnTreeExiting(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("tree_exiting"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnTreeExited is promoted from [Node.Instance.OnTreeExited].
func (self Instance) OnTreeExited(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("tree_exited"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnChildEnteredTree is promoted from [Node.Instance.OnChildEnteredTree].
func (self Instance) OnChildEnteredTree(cb func(node Node.Instance), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("child_entered_tree"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnChildExitingTree is promoted from [Node.Instance.OnChildExitingTree].
func (self Instance) OnChildExitingTree(cb func(node Node.Instance), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("child_exiting_tree"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnChildOrderChanged is promoted from [Node.Instance.OnChildOrderChanged].
func (self Instance) OnChildOrderChanged(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("child_order_changed"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnReplacingBy is promoted from [Node.Instance.OnReplacingBy].
func (self Instance) OnReplacingBy(cb func(node Node.Instance), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("replacing_by"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnEditorDescriptionChanged is promoted from [Node.Instance.OnEditorDescriptionChanged].
func (self Instance) OnEditorDescriptionChanged(cb func(node Node.Instance), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("editor_description_changed"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnEditorStateChanged is promoted from [Node.Instance.OnEditorStateChanged].
func (self Instance) OnEditorStateChanged(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("editor_state_changed"), gd.NewCallable(cb), int64(flags_together))
	return self
}

func (self class) Virtual(name string) reflect.Value {
	switch name {
	default: return gd.VirtualByName(PhysicsBody2D.Advanced(self.AsPhysicsBody2D()), name)
	}
}

func (self Instance) Virtual(name string) reflect.Value {
	switch name {
	default: return gd.VirtualByName(PhysicsBody2D.Instance(self.AsPhysicsBody2D()), name)
	}
}
func init() {gdclass.Register("CharacterBody2D", func(ptr gdreference.Object) any { return Instance{gdclass.NewCharacterBody2D(ptr)} })}
type MotionMode int64//gd:CharacterBody2D.MotionMode

const (
	MotionModeGrounded MotionMode = 0
	MotionModeFloating MotionMode = 1
)
type PlatformOnLeave int64//gd:CharacterBody2D.PlatformOnLeave

const (
	PlatformOnLeaveAddVelocity PlatformOnLeave = 0
	PlatformOnLeaveAddUpwardVelocity PlatformOnLeave = 1
	PlatformOnLeaveDoNothing PlatformOnLeave = 2
)
