// Code generated by the generate package DO NOT EDIT


package RegExMatch

import "reflect"
import "slices"
import "github.com/AveryLucas/gogogd/internal/pointers"
import "github.com/AveryLucas/gogogd/internal/callframe"
import "github.com/AveryLucas/gogogd/internal/gdextension"
import "github.com/AveryLucas/gogogd/internal/gdreference"
import "github.com/AveryLucas/gogogd/internal/noescape"
import gd "github.com/AveryLucas/gogogd/internal"
import "github.com/AveryLucas/gogogd/internal/gdclass"
import "github.com/AveryLucas/gogogd/internal/ie"
import "github.com/AveryLucas/gogogd/variant"
import "github.com/AveryLucas/gogogd/variant/Angle"
import "github.com/AveryLucas/gogogd/variant/Euler"
import "github.com/AveryLucas/gogogd/variant/Signal"
import "github.com/AveryLucas/gogogd/variant/Array"
import "github.com/AveryLucas/gogogd/variant/Callable"
import "github.com/AveryLucas/gogogd/variant/Dictionary"
import "github.com/AveryLucas/gogogd/variant/Error"
import "github.com/AveryLucas/gogogd/variant/Float"
import "github.com/AveryLucas/gogogd/variant/Object"
import "github.com/AveryLucas/gogogd/variant/Packed"
import "github.com/AveryLucas/gogogd/variant/Path"
import "github.com/AveryLucas/gogogd/variant/RID"
import "github.com/AveryLucas/gogogd/variant/RefCounted"
import "github.com/AveryLucas/gogogd/variant/String"

var _ Object.ID
type _ gdclass.Node
var _ gd.String
var _ RefCounted.Instance
var _ reflect.Type
var _ callframe.Frame
var _ = pointers.Cycle
var _ = Array.Nil
var _ variant.Any
var _ Callable.Function
var _ Dictionary.Any
var _ RID.Any
var _ noescape.Variant
var _ String.Readable
var _ Path.ToNode
var _ Packed.Bytes
var _ Error.Code
var _ Float.X
var _ Signal.Any
var _ Angle.Radians
var _ Euler.Radians
var _ gdextension.Object
var _ = slices.Delete[[]struct{}, struct{}]

/*
ID is a typed object ID (reference) to an instance of this class, use it to store references to objects with
unknown lifetimes, as an ID will not panic on use if the underlying object has been destroyed.
*/
type ID Object.ID
func (id ID) Instance() (Instance, bool) { return Object.As[Instance](Object.ID(id).Instance()) }
/*
Extension can be embedded in a new struct to create a Go extension of this class.

T must be a type that is embedding this [Extension] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Extension[T gdclass.Interface] struct { gdclass.Extension[T, Instance] }
/*
Singleton can be embedded in a new struct to create a Go singleton extension of the class.

It will become available as a global inside scripts and any any other Go Extension types will
have any *T typed fields filled in to point at this singleton once they have been instantiated.

T must be a type that is embedding this [Singleton] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Singleton[T gdclass.Interface] = Extension[T]
// Instance of the class with convieniently typed arguments and results.
type Instance [1]gdclass.RegExMatch
var otype gdextension.ObjectType
var sname gdextension.StringName
var methods struct {
	get_subject gdextension.MethodForClass `hash:"201670096"`
	get_group_count gdextension.MethodForClass `hash:"3905245786"`
	get_names gdextension.MethodForClass `hash:"3102165223"`
	get_strings gdextension.MethodForClass `hash:"1139954409"`
	get_string gdextension.MethodForClass `hash:"687115856"`
	get_start gdextension.MethodForClass `hash:"490464691"`
	get_end gdextension.MethodForClass `hash:"490464691"`
}
func init() {
	gd.Links = append(gd.Links, func() {
		sname = gdextension.Host.Strings.Intern.UTF8("RegExMatch")
		otype = gdextension.Host.Objects.Type(sname)
		gd.LinkMethods(sname, &methods, false)
		})
	gd.RegisterCleanup(func() {
		noescape.Free(gdextension.TypeStringName, &sname)
	})
}
func (self Instance) ID() ID { return ID(Object.Instance(self.AsObject()).ID()) }
// MoreArgs is a container for [Instance] functions with additional 'optional' arguments.
type MoreArgs [1]gdclass.RegExMatch
type Expanded = MoreArgs
// MoreArgs enables certain functions to be called with additional 'optional' arguments.
func (self Instance) MoreArgs() MoreArgs { return MoreArgs(self) }
// Nil is a nil/null instance of the class. Equivalent to the zero value.
var Nil Instance
type Any interface {
	gd.IsClass
	AsRegExMatch() Instance
}
func (self Instance) GetGroupCount() int { //gd:RegExMatch.get_group_count
	return int(int(Advanced(self).GetGroupCount()))
}
func (self Instance) GetString() string { //gd:RegExMatch.get_string
	return string(Advanced(self).GetString(variant.New(0)).String())
}
func (self MoreArgs) GetString(name any) string { //gd:RegExMatch.get_string
	return string(Advanced(self).GetString(variant.New(name)).String())
}
func (self Instance) GetStart() int { //gd:RegExMatch.get_start
	return int(int(Advanced(self).GetStart(variant.New(0))))
}
func (self MoreArgs) GetStart(name any) int { //gd:RegExMatch.get_start
	return int(int(Advanced(self).GetStart(variant.New(name))))
}
func (self Instance) GetEnd() int { //gd:RegExMatch.get_end
	return int(int(Advanced(self).GetEnd(variant.New(0))))
}
func (self MoreArgs) GetEnd(name any) int { //gd:RegExMatch.get_end
	return int(int(Advanced(self).GetEnd(variant.New(name))))
}
// Advanced exposes a 1:1 low-level instance of the class, undocumented, for those who know what they are doing.
type Advanced = class
type class [1]gdclass.RegExMatch
func (o class) AsObject() [1]gdreference.Object { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (self *class) SetObject(obj [1]gdreference.Object) bool {
	if gdextension.Host.Objects.Cast(gdreference.GetObject(obj[0]), otype) != 0 {
		self[0] = gdclass.NewRegExMatch(obj[0])
		return true
	}
	return false
}
func (self *Instance) SetObject(obj [1]gdreference.Object) bool {
	if gdextension.Host.Objects.Cast(gdreference.GetObject(obj[0]), otype) != 0 {
		self[0] = gdclass.NewRegExMatch(obj[0])
		return true
	}
	return false
}
func (o Instance) AsObject() [1]gdreference.Object { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (o *Extension[T]) AsObject() [1]gdreference.Object { return o.Super().AsObject() }
func New() Instance {
if !gd.Linked {
		var placeholder = Instance([1]gdclass.RegExMatch{gdclass.NewRegExMatch(gdreference.NewObject())})
		gd.StartupFunctions = append(gd.StartupFunctions, func() {
			if gd.Linked {
				raw, _ := gdreference.EndObject(New().AsObject()[0])
				gdreference.SetObject(gdclass.GetRegExMatch(placeholder[0])[0], raw)
				gd.RegisterCleanup(func() {
					if raw := gdreference.GetObject(placeholder.AsObject()[0]); raw != 0 {
						gdextension.Host.Objects.Unsafe.Free(raw)
					}
				})
			}
		})
		return placeholder
	}
	casted := Instance([1]gdclass.RegExMatch{gdclass.NewRegExMatch(gdreference.OwnObject(gdextension.Host.Objects.Make(sname), gd.Free))})
	casted.AsRefCounted()[0].InitRef()
	gd.ObjectNotification(casted.AsObject()[0], 0, false)
	return casted
}

func (self Instance) Subject() string { //gd:RegExMatch.subject
		return string(class(self).GetSubject().String())
}

func (o *Extension[T]) Subject() string { return o.Super().Subject() }

func (self Instance) Names() map[string]int { //gd:RegExMatch.names
		return map[string]int(gd.DictionaryAs[map[string]int](class(self).GetNames()))
}

func (o *Extension[T]) Names() map[string]int { return o.Super().Names() }

func (self Instance) Strings() []string { //gd:RegExMatch.strings
		return []string(class(self).GetStrings().Strings())
}

func (o *Extension[T]) Strings() []string { return o.Super().Strings() }

func (self class) GetSubject() String.Readable { //gd:RegExMatch.get_subject
	var r_ret = noescape.Call[gdextension.String]( gd.ObjectChecked(self.AsObject()), methods.get_subject, gdextension.SizeString, &struct{}{})
	var ret = String.Via(gd.StringProxy{}, pointers.Pack(pointers.New[gd.String](r_ret)))
	return ret
}
func (self class) GetGroupCount() int64 { //gd:RegExMatch.get_group_count
	var r_ret = noescape.Call[int64]( gd.ObjectChecked(self.AsObject()), methods.get_group_count, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) GetNames() Dictionary.Any { //gd:RegExMatch.get_names
	var r_ret = noescape.Call[gdextension.Dictionary]( gd.ObjectChecked(self.AsObject()), methods.get_names, gdextension.SizeDictionary, &struct{}{})
	var ret = Dictionary.Through(gd.DictionaryProxy[variant.Any,variant.Any]{}, pointers.Pack(pointers.New[gd.Dictionary](r_ret)))
	return ret
}
func (self class) GetStrings() Packed.Strings { //gd:RegExMatch.get_strings
	var r_ret = noescape.Call[gd.PackedPointers]( gd.ObjectChecked(self.AsObject()), methods.get_strings, gdextension.SizePackedArray, &struct{}{})
	var ret = Packed.Strings(Array.Through(gd.PackedStringArrayProxy{}, pointers.Pack(pointers.Let[gd.PackedStringArray](r_ret))))
	return ret
}
func (self class) GetString(name variant.Any) String.Readable { //gd:RegExMatch.get_string
	var r_ret = noescape.Call[gdextension.String]( gd.ObjectChecked(self.AsObject()), methods.get_string, gdextension.SizeString|(gdextension.SizeVariant<<4), &struct{name gdextension.Variant}{gdextension.Variant(pointers.Get(gd.InternalVariant(name)))})
	var ret = String.Via(gd.StringProxy{}, pointers.Pack(pointers.New[gd.String](r_ret)))
	return ret
}
func (self class) GetStart(name variant.Any) int64 { //gd:RegExMatch.get_start
	var r_ret = noescape.Call[int64]( gd.ObjectChecked(self.AsObject()), methods.get_start, gdextension.SizeInt|(gdextension.SizeVariant<<4), &struct{name gdextension.Variant}{gdextension.Variant(pointers.Get(gd.InternalVariant(name)))})
	var ret = r_ret
	return ret
}
func (self class) GetEnd(name variant.Any) int64 { //gd:RegExMatch.get_end
	var r_ret = noescape.Call[int64]( gd.ObjectChecked(self.AsObject()), methods.get_end, gdextension.SizeInt|(gdextension.SizeVariant<<4), &struct{name gdextension.Variant}{gdextension.Variant(pointers.Get(gd.InternalVariant(name)))})
	var ret = r_ret
	return ret
}
func (o class) AsRegExMatch() Advanced { return Advanced(o) }
func (o Instance) AsRegExMatch() Instance { return o }
func (o *Extension[T]) AsRegExMatch() Instance { return o.Super() }
func (o class) AsRefCounted() ie.RC { return *(*ie.RC)(ie.As(&o)) }
func (o *Extension[T]) AsRefCounted() ie.RC { return o.Super().AsRefCounted() }
func (o Instance) AsRefCounted() ie.RC { return *(*ie.RC)(ie.As(&o)) }
func (o *Extension[T]) GetGroupCount() int {
	return o.Super().GetGroupCount()
}

func (self class) Virtual(name string) reflect.Value {
	switch name {
	default: return gd.VirtualByName(RefCounted.Advanced(self.AsRefCounted()), name)
	}
}

func (self Instance) Virtual(name string) reflect.Value {
	switch name {
	default: return gd.VirtualByName(RefCounted.Instance(self.AsRefCounted()), name)
	}
}
func init() {gdclass.Register("RegExMatch", func(ptr gdreference.Object) any { return Instance{gdclass.NewRegExMatch(ptr)} })}
