// Code generated by the generate package DO NOT EDIT


package GPUParticles3D

import "reflect"
import "slices"
import "graphics.gd/internal/pointers"
import "graphics.gd/internal/callframe"
import "graphics.gd/internal/gdextension"
import "graphics.gd/internal/gdreference"
import "graphics.gd/internal/noescape"
import gd "graphics.gd/internal"
import "graphics.gd/internal/gdclass"
import "graphics.gd/internal/ie"
import "graphics.gd/variant"
import "graphics.gd/variant/Angle"
import "graphics.gd/variant/Euler"
import "graphics.gd/variant/Signal"
import "graphics.gd/classdb/GeometryInstance3D"
import "graphics.gd/classdb/Material"
import "graphics.gd/classdb/Mesh"
import "graphics.gd/classdb/Node"
import "graphics.gd/classdb/Node3D"
import "graphics.gd/classdb/Node3DGizmo"
import "graphics.gd/classdb/Skin"
import "graphics.gd/classdb/Tween"
import "graphics.gd/classdb/VisualInstance3D"
import "graphics.gd/classdb/World3D"
import "graphics.gd/variant/AABB"
import "graphics.gd/variant/Array"
import "graphics.gd/variant/Callable"
import "graphics.gd/variant/Color"
import "graphics.gd/variant/Dictionary"
import "graphics.gd/variant/Error"
import "graphics.gd/variant/Float"
import "graphics.gd/variant/Object"
import "graphics.gd/variant/Packed"
import "graphics.gd/variant/Path"
import "graphics.gd/variant/RID"
import "graphics.gd/variant/RefCounted"
import "graphics.gd/variant/String"
import "graphics.gd/variant/Transform3D"
import "graphics.gd/variant/Vector3"

var _ Object.ID
type _ gdclass.Node
var _ gd.String
var _ RefCounted.Instance
var _ reflect.Type
var _ callframe.Frame
var _ = pointers.Cycle
var _ = Array.Nil
var _ variant.Any
var _ Callable.Function
var _ Dictionary.Any
var _ RID.Any
var _ noescape.Variant
var _ String.Readable
var _ Path.ToNode
var _ Packed.Bytes
var _ Error.Code
var _ Float.X
var _ Signal.Any
var _ Angle.Radians
var _ Euler.Radians
var _ gdextension.Object
var _ = slices.Delete[[]struct{}, struct{}]

/*
ID is a typed object ID (reference) to an instance of this class, use it to store references to objects with
unknown lifetimes, as an ID will not panic on use if the underlying object has been destroyed.
*/
type ID Object.ID
func (id ID) Instance() (Instance, bool) { return Object.As[Instance](Object.ID(id).Instance()) }
/*
Extension can be embedded in a new struct to create a Go extension of this class.

T must be a type that is embedding this [Extension] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Extension[T gdclass.Interface] struct { gdclass.Extension[T, Instance] }
/*
Singleton can be embedded in a new struct to create a Go singleton extension of the class.

It will become available as a global inside scripts and any any other Go Extension types will
have any *T typed fields filled in to point at this singleton once they have been instantiated.

T must be a type that is embedding this [Singleton] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Singleton[T gdclass.Interface] = Extension[T]
// Instance of the class with convieniently typed arguments and results.
type Instance [1]gdclass.GPUParticles3D
var otype gdextension.ObjectType
var sname gdextension.StringName
var methods struct {
	set_emitting gdextension.MethodForClass `hash:"2586408642"`
	set_amount gdextension.MethodForClass `hash:"1286410249"`
	set_lifetime gdextension.MethodForClass `hash:"373806689"`
	set_one_shot gdextension.MethodForClass `hash:"2586408642"`
	set_pre_process_time gdextension.MethodForClass `hash:"373806689"`
	set_explosiveness_ratio gdextension.MethodForClass `hash:"373806689"`
	set_randomness_ratio gdextension.MethodForClass `hash:"373806689"`
	set_visibility_aabb gdextension.MethodForClass `hash:"259215842"`
	set_use_local_coordinates gdextension.MethodForClass `hash:"2586408642"`
	set_fixed_fps gdextension.MethodForClass `hash:"1286410249"`
	set_fractional_delta gdextension.MethodForClass `hash:"2586408642"`
	set_interpolate gdextension.MethodForClass `hash:"2586408642"`
	set_process_material gdextension.MethodForClass `hash:"2757459619"`
	set_speed_scale gdextension.MethodForClass `hash:"373806689"`
	set_collision_base_size gdextension.MethodForClass `hash:"373806689"`
	set_interp_to_end gdextension.MethodForClass `hash:"373806689"`
	is_emitting gdextension.MethodForClass `hash:"36873697"`
	get_amount gdextension.MethodForClass `hash:"3905245786"`
	get_lifetime gdextension.MethodForClass `hash:"1740695150"`
	get_one_shot gdextension.MethodForClass `hash:"36873697"`
	get_pre_process_time gdextension.MethodForClass `hash:"1740695150"`
	get_explosiveness_ratio gdextension.MethodForClass `hash:"1740695150"`
	get_randomness_ratio gdextension.MethodForClass `hash:"1740695150"`
	get_visibility_aabb gdextension.MethodForClass `hash:"1068685055"`
	get_use_local_coordinates gdextension.MethodForClass `hash:"36873697"`
	get_fixed_fps gdextension.MethodForClass `hash:"3905245786"`
	get_fractional_delta gdextension.MethodForClass `hash:"36873697"`
	get_interpolate gdextension.MethodForClass `hash:"36873697"`
	get_process_material gdextension.MethodForClass `hash:"5934680"`
	get_speed_scale gdextension.MethodForClass `hash:"1740695150"`
	get_collision_base_size gdextension.MethodForClass `hash:"1740695150"`
	get_interp_to_end gdextension.MethodForClass `hash:"1740695150"`
	set_use_fixed_seed gdextension.MethodForClass `hash:"2586408642"`
	get_use_fixed_seed gdextension.MethodForClass `hash:"36873697"`
	set_seed gdextension.MethodForClass `hash:"1286410249"`
	get_seed gdextension.MethodForClass `hash:"3905245786"`
	set_draw_order gdextension.MethodForClass `hash:"1208074815"`
	get_draw_order gdextension.MethodForClass `hash:"3770381780"`
	set_draw_passes gdextension.MethodForClass `hash:"1286410249"`
	set_draw_pass_mesh gdextension.MethodForClass `hash:"969122797"`
	get_draw_passes gdextension.MethodForClass `hash:"3905245786"`
	get_draw_pass_mesh gdextension.MethodForClass `hash:"1576363275"`
	set_skin gdextension.MethodForClass `hash:"3971435618"`
	get_skin gdextension.MethodForClass `hash:"2074563878"`
	restart gdextension.MethodForClass `hash:"107499316"`
	capture_aabb gdextension.MethodForClass `hash:"1068685055"`
	set_sub_emitter gdextension.MethodForClass `hash:"1348162250"`
	get_sub_emitter gdextension.MethodForClass `hash:"4075236667"`
	emit_particle gdextension.MethodForClass `hash:"992173727"`
	set_trail_enabled gdextension.MethodForClass `hash:"2586408642"`
	set_trail_lifetime gdextension.MethodForClass `hash:"373806689"`
	is_trail_enabled gdextension.MethodForClass `hash:"36873697"`
	get_trail_lifetime gdextension.MethodForClass `hash:"1740695150"`
	set_transform_align gdextension.MethodForClass `hash:"3892425954"`
	get_transform_align gdextension.MethodForClass `hash:"2100992166"`
	convert_from_particles gdextension.MethodForClass `hash:"1078189570"`
	set_amount_ratio gdextension.MethodForClass `hash:"373806689"`
	get_amount_ratio gdextension.MethodForClass `hash:"1740695150"`
	request_particles_process gdextension.MethodForClass `hash:"373806689"`
}
func init() {
	gd.Links = append(gd.Links, func() {
		sname = gdextension.Host.Strings.Intern.UTF8("GPUParticles3D")
		otype = gdextension.Host.Objects.Type(sname)
		gd.LinkMethods(sname, &methods, false)
		})
	gd.RegisterCleanup(func() {
		noescape.Free(gdextension.TypeStringName, &sname)
	})
}
func (self Instance) ID() ID { return ID(Object.Instance(self.AsObject()).ID()) }
// MoreArgs is a container for [Instance] functions with additional 'optional' arguments.
type MoreArgs [1]gdclass.GPUParticles3D
type Expanded = MoreArgs
// MoreArgs enables certain functions to be called with additional 'optional' arguments.
func (self Instance) MoreArgs() MoreArgs { return MoreArgs(self) }
// Nil is a nil/null instance of the class. Equivalent to the zero value.
var Nil Instance
type Any interface {
	gd.IsClass
	AsGPUParticles3D() Instance
}
func (self Instance) Restart() { //gd:GPUParticles3D.restart
	Advanced(self).Restart(false)
}
func (self MoreArgs) Restart(keep_seed bool) { //gd:GPUParticles3D.restart
	Advanced(self).Restart(keep_seed)
}
func (self Instance) CaptureAabb() AABB.PositionSize { //gd:GPUParticles3D.capture_aabb
	return AABB.PositionSize(Advanced(self).CaptureAabb())
}
func (self Instance) EmitParticle(xform Transform3D.BasisOrigin, velocity Vector3.XYZ, color Color.RGBA, custom Color.RGBA, flags int) { //gd:GPUParticles3D.emit_particle
	Advanced(self).EmitParticle(Transform3D.BasisOrigin(xform), Vector3.XYZ(velocity), Color.RGBA(color), Color.RGBA(custom), int64(flags))
}
func (self Instance) ConvertFromParticles(particles Node.Instance) { //gd:GPUParticles3D.convert_from_particles
	Advanced(self).ConvertFromParticles(particles)
}
func (self Instance) RequestParticlesProcess(process_time Float.X) { //gd:GPUParticles3D.request_particles_process
	Advanced(self).RequestParticlesProcess(float64(process_time))
}
// Advanced exposes a 1:1 low-level instance of the class, undocumented, for those who know what they are doing.
type Advanced = class
type class [1]gdclass.GPUParticles3D
func (o class) AsObject() [1]gdreference.Object { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (self *class) SetObject(obj [1]gdreference.Object) bool {
	if gdextension.Host.Objects.Cast(gdreference.GetObject(obj[0]), otype) != 0 {
		self[0] = gdclass.NewGPUParticles3D(obj[0])
		return true
	}
	return false
}
func (self *Instance) SetObject(obj [1]gdreference.Object) bool {
	if gdextension.Host.Objects.Cast(gdreference.GetObject(obj[0]), otype) != 0 {
		self[0] = gdclass.NewGPUParticles3D(obj[0])
		return true
	}
	return false
}
func (o Instance) AsObject() [1]gdreference.Object { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (o *Extension[T]) AsObject() [1]gdreference.Object { return o.Super().AsObject() }
func New() Instance {
if !gd.Linked {
		var placeholder = Instance([1]gdclass.GPUParticles3D{gdclass.NewGPUParticles3D(gdreference.NewObject())})
		gd.StartupFunctions = append(gd.StartupFunctions, func() {
			if gd.Linked {
				raw, _ := gdreference.EndObject(New().AsObject()[0])
				gdreference.SetObject(gdclass.GetGPUParticles3D(placeholder[0])[0], raw)
				gd.RegisterCleanup(func() {
					if raw := gdreference.GetObject(placeholder.AsObject()[0]); raw != 0 {
						gdextension.Host.Objects.Unsafe.Free(raw)
					}
				})
			}
		})
		return placeholder
	}
	casted := Instance([1]gdclass.GPUParticles3D{gdclass.NewGPUParticles3D(gdreference.OwnObject(gdextension.Host.Objects.Make(sname), gd.Free))})
	gd.ObjectNotification(casted.AsObject()[0], 0, false)
	return casted
}

func (self Instance) Emitting() bool { //gd:GPUParticles3D.emitting
		return bool(class(self).IsEmitting())
}

// SetEmitting sets the property returned by [IsEmitting]. Returns the instance, so that property settings can be chained.
func (self Instance) SetEmitting(value bool) Instance { //gd:GPUParticles3D.emitting
	class(self).SetEmitting(value)
	return self
}

func (self Instance) Amount() int { //gd:GPUParticles3D.amount
		return int(int(class(self).GetAmount()))
}

// SetAmount sets the property returned by [GetAmount]. Returns the instance, so that property settings can be chained.
func (self Instance) SetAmount(value int) Instance { //gd:GPUParticles3D.amount
	class(self).SetAmount(int64(value))
	return self
}

func (self Instance) AmountRatio() Float.X { //gd:GPUParticles3D.amount_ratio
		return Float.X(Float.X(class(self).GetAmountRatio()))
}

// SetAmountRatio sets the property returned by [GetAmountRatio]. Returns the instance, so that property settings can be chained.
func (self Instance) SetAmountRatio(value Float.X) Instance { //gd:GPUParticles3D.amount_ratio
	class(self).SetAmountRatio(float64(value))
	return self
}

func (self Instance) SubEmitter() string { //gd:GPUParticles3D.sub_emitter
		return string(class(self).GetSubEmitter().String())
}

// SetSubEmitter sets the property returned by [GetSubEmitter]. Returns the instance, so that property settings can be chained.
func (self Instance) SetSubEmitter(value string) Instance { //gd:GPUParticles3D.sub_emitter
	class(self).SetSubEmitter(Path.ToNode(String.From(value)))
	return self
}

func (self Instance) Lifetime() Float.X { //gd:GPUParticles3D.lifetime
		return Float.X(Float.X(class(self).GetLifetime()))
}

// SetLifetime sets the property returned by [GetLifetime]. Returns the instance, so that property settings can be chained.
func (self Instance) SetLifetime(value Float.X) Instance { //gd:GPUParticles3D.lifetime
	class(self).SetLifetime(float64(value))
	return self
}

func (self Instance) InterpToEnd() Float.X { //gd:GPUParticles3D.interp_to_end
		return Float.X(Float.X(class(self).GetInterpToEnd()))
}

// SetInterpToEnd sets the property returned by [GetInterpToEnd]. Returns the instance, so that property settings can be chained.
func (self Instance) SetInterpToEnd(value Float.X) Instance { //gd:GPUParticles3D.interp_to_end
	class(self).SetInterpToEnd(float64(value))
	return self
}

func (self Instance) OneShot() bool { //gd:GPUParticles3D.one_shot
		return bool(class(self).GetOneShot())
}

// SetOneShot sets the property returned by [GetOneShot]. Returns the instance, so that property settings can be chained.
func (self Instance) SetOneShot(value bool) Instance { //gd:GPUParticles3D.one_shot
	class(self).SetOneShot(value)
	return self
}

func (self Instance) Preprocess() Float.X { //gd:GPUParticles3D.preprocess
		return Float.X(Float.X(class(self).GetPreProcessTime()))
}

// SetPreprocess sets the property returned by [GetPreProcessTime]. Returns the instance, so that property settings can be chained.
func (self Instance) SetPreprocess(value Float.X) Instance { //gd:GPUParticles3D.preprocess
	class(self).SetPreProcessTime(float64(value))
	return self
}

func (self Instance) SpeedScale() Float.X { //gd:GPUParticles3D.speed_scale
		return Float.X(Float.X(class(self).GetSpeedScale()))
}

// SetSpeedScale sets the property returned by [GetSpeedScale]. Returns the instance, so that property settings can be chained.
func (self Instance) SetSpeedScale(value Float.X) Instance { //gd:GPUParticles3D.speed_scale
	class(self).SetSpeedScale(float64(value))
	return self
}

func (self Instance) Explosiveness() Float.X { //gd:GPUParticles3D.explosiveness
		return Float.X(Float.X(class(self).GetExplosivenessRatio()))
}

// SetExplosiveness sets the property returned by [GetExplosivenessRatio]. Returns the instance, so that property settings can be chained.
func (self Instance) SetExplosiveness(value Float.X) Instance { //gd:GPUParticles3D.explosiveness
	class(self).SetExplosivenessRatio(float64(value))
	return self
}

func (self Instance) Randomness() Float.X { //gd:GPUParticles3D.randomness
		return Float.X(Float.X(class(self).GetRandomnessRatio()))
}

// SetRandomness sets the property returned by [GetRandomnessRatio]. Returns the instance, so that property settings can be chained.
func (self Instance) SetRandomness(value Float.X) Instance { //gd:GPUParticles3D.randomness
	class(self).SetRandomnessRatio(float64(value))
	return self
}

func (self Instance) UseFixedSeed() bool { //gd:GPUParticles3D.use_fixed_seed
		return bool(class(self).GetUseFixedSeed())
}

// SetUseFixedSeed sets the property returned by [GetUseFixedSeed]. Returns the instance, so that property settings can be chained.
func (self Instance) SetUseFixedSeed(value bool) Instance { //gd:GPUParticles3D.use_fixed_seed
	class(self).SetUseFixedSeed(value)
	return self
}

func (self Instance) Seed() int { //gd:GPUParticles3D.seed
		return int(int(class(self).GetSeed()))
}

// SetSeed sets the property returned by [GetSeed]. Returns the instance, so that property settings can be chained.
func (self Instance) SetSeed(value int) Instance { //gd:GPUParticles3D.seed
	class(self).SetSeed(int64(value))
	return self
}

func (self Instance) FixedFps() int { //gd:GPUParticles3D.fixed_fps
		return int(int(class(self).GetFixedFps()))
}

// SetFixedFps sets the property returned by [GetFixedFps]. Returns the instance, so that property settings can be chained.
func (self Instance) SetFixedFps(value int) Instance { //gd:GPUParticles3D.fixed_fps
	class(self).SetFixedFps(int64(value))
	return self
}

func (self Instance) Interpolate() bool { //gd:GPUParticles3D.interpolate
		return bool(class(self).GetInterpolate())
}

// SetInterpolate sets the property returned by [GetInterpolate]. Returns the instance, so that property settings can be chained.
func (self Instance) SetInterpolate(value bool) Instance { //gd:GPUParticles3D.interpolate
	class(self).SetInterpolate(value)
	return self
}

func (self Instance) FractDelta() bool { //gd:GPUParticles3D.fract_delta
		return bool(class(self).GetFractionalDelta())
}

// SetFractDelta sets the property returned by [GetFractionalDelta]. Returns the instance, so that property settings can be chained.
func (self Instance) SetFractDelta(value bool) Instance { //gd:GPUParticles3D.fract_delta
	class(self).SetFractionalDelta(value)
	return self
}

func (self Instance) CollisionBaseSize() Float.X { //gd:GPUParticles3D.collision_base_size
		return Float.X(Float.X(class(self).GetCollisionBaseSize()))
}

// SetCollisionBaseSize sets the property returned by [GetCollisionBaseSize]. Returns the instance, so that property settings can be chained.
func (self Instance) SetCollisionBaseSize(value Float.X) Instance { //gd:GPUParticles3D.collision_base_size
	class(self).SetCollisionBaseSize(float64(value))
	return self
}

func (self Instance) VisibilityAabb() AABB.PositionSize { //gd:GPUParticles3D.visibility_aabb
		return AABB.PositionSize(class(self).GetVisibilityAabb())
}

// SetVisibilityAabb sets the property returned by [GetVisibilityAabb]. Returns the instance, so that property settings can be chained.
func (self Instance) SetVisibilityAabb(value AABB.PositionSize) Instance { //gd:GPUParticles3D.visibility_aabb
	class(self).SetVisibilityAabb(AABB.PositionSize(value))
	return self
}

func (self Instance) LocalCoords() bool { //gd:GPUParticles3D.local_coords
		return bool(class(self).GetUseLocalCoordinates())
}

// SetLocalCoords sets the property returned by [GetUseLocalCoordinates]. Returns the instance, so that property settings can be chained.
func (self Instance) SetLocalCoords(value bool) Instance { //gd:GPUParticles3D.local_coords
	class(self).SetUseLocalCoordinates(value)
	return self
}

func (self Instance) DrawOrder() DrawOrder { //gd:GPUParticles3D.draw_order
		return DrawOrder(class(self).GetDrawOrder())
}

// SetDrawOrder sets the property returned by [GetDrawOrder]. Returns the instance, so that property settings can be chained.
func (self Instance) SetDrawOrder(value DrawOrder) Instance { //gd:GPUParticles3D.draw_order
	class(self).SetDrawOrder(value)
	return self
}

func (self Instance) TransformAlign() TransformAlign { //gd:GPUParticles3D.transform_align
		return TransformAlign(class(self).GetTransformAlign())
}

// SetTransformAlign sets the property returned by [GetTransformAlign]. Returns the instance, so that property settings can be chained.
func (self Instance) SetTransformAlign(value TransformAlign) Instance { //gd:GPUParticles3D.transform_align
	class(self).SetTransformAlign(value)
	return self
}

func (self Instance) TrailEnabled() bool { //gd:GPUParticles3D.trail_enabled
		return bool(class(self).IsTrailEnabled())
}

// SetTrailEnabled sets the property returned by [IsTrailEnabled]. Returns the instance, so that property settings can be chained.
func (self Instance) SetTrailEnabled(value bool) Instance { //gd:GPUParticles3D.trail_enabled
	class(self).SetTrailEnabled(value)
	return self
}

func (self Instance) TrailLifetime() Float.X { //gd:GPUParticles3D.trail_lifetime
		return Float.X(Float.X(class(self).GetTrailLifetime()))
}

// SetTrailLifetime sets the property returned by [GetTrailLifetime]. Returns the instance, so that property settings can be chained.
func (self Instance) SetTrailLifetime(value Float.X) Instance { //gd:GPUParticles3D.trail_lifetime
	class(self).SetTrailLifetime(float64(value))
	return self
}

func (self Instance) ProcessMaterial() Material.Instance { //gd:GPUParticles3D.process_material
		return Material.Instance(class(self).GetProcessMaterial())
}

// SetProcessMaterial sets the property returned by [GetProcessMaterial]. Returns the instance, so that property settings can be chained.
func (self Instance) SetProcessMaterial(value Material.Instance) Instance { //gd:GPUParticles3D.process_material
	class(self).SetProcessMaterial(value)
	return self
}

func (self Instance) DrawPasses() int { //gd:GPUParticles3D.draw_passes
		return int(int(class(self).GetDrawPasses()))
}

// SetDrawPasses sets the property returned by [GetDrawPasses]. Returns the instance, so that property settings can be chained.
func (self Instance) SetDrawPasses(value int) Instance { //gd:GPUParticles3D.draw_passes
	class(self).SetDrawPasses(int64(value))
	return self
}

func (self Instance) DrawPass1() Mesh.Instance { //gd:GPUParticles3D.draw_pass_1
		return Mesh.Instance(class(self).GetDrawPassMesh(0))
}

// SetDrawPass1 sets the property returned by [GetDrawPassMesh]. Returns the instance, so that property settings can be chained.
func (self Instance) SetDrawPass1(value Mesh.Instance) Instance { //gd:GPUParticles3D.draw_pass_1
	class(self).SetDrawPassMesh(0, value)
	return self
}

func (self Instance) DrawPass2() Mesh.Instance { //gd:GPUParticles3D.draw_pass_2
		return Mesh.Instance(class(self).GetDrawPassMesh(1))
}

// SetDrawPass2 sets the property returned by [GetDrawPassMesh]. Returns the instance, so that property settings can be chained.
func (self Instance) SetDrawPass2(value Mesh.Instance) Instance { //gd:GPUParticles3D.draw_pass_2
	class(self).SetDrawPassMesh(1, value)
	return self
}

func (self Instance) DrawPass3() Mesh.Instance { //gd:GPUParticles3D.draw_pass_3
		return Mesh.Instance(class(self).GetDrawPassMesh(2))
}

// SetDrawPass3 sets the property returned by [GetDrawPassMesh]. Returns the instance, so that property settings can be chained.
func (self Instance) SetDrawPass3(value Mesh.Instance) Instance { //gd:GPUParticles3D.draw_pass_3
	class(self).SetDrawPassMesh(2, value)
	return self
}

func (self Instance) DrawPass4() Mesh.Instance { //gd:GPUParticles3D.draw_pass_4
		return Mesh.Instance(class(self).GetDrawPassMesh(3))
}

// SetDrawPass4 sets the property returned by [GetDrawPassMesh]. Returns the instance, so that property settings can be chained.
func (self Instance) SetDrawPass4(value Mesh.Instance) Instance { //gd:GPUParticles3D.draw_pass_4
	class(self).SetDrawPassMesh(3, value)
	return self
}

func (self Instance) DrawSkin() Skin.Instance { //gd:GPUParticles3D.draw_skin
		return Skin.Instance(class(self).GetSkin())
}

// SetDrawSkin sets the property returned by [GetSkin]. Returns the instance, so that property settings can be chained.
func (self Instance) SetDrawSkin(value Skin.Instance) Instance { //gd:GPUParticles3D.draw_skin
	class(self).SetSkin(value)
	return self
}

func (self class) SetEmitting(emitting bool)  { //gd:GPUParticles3D.set_emitting
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_emitting, 0|(gdextension.SizeBool<<4), &struct{emitting bool}{emitting})
}
func (self class) SetAmount(amount int64)  { //gd:GPUParticles3D.set_amount
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_amount, 0|(gdextension.SizeInt<<4), &struct{amount int64}{amount})
}
func (self class) SetLifetime(secs float64)  { //gd:GPUParticles3D.set_lifetime
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_lifetime, 0|(gdextension.SizeFloat<<4), &struct{secs float64}{secs})
}
func (self class) SetOneShot(enable bool)  { //gd:GPUParticles3D.set_one_shot
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_one_shot, 0|(gdextension.SizeBool<<4), &struct{enable bool}{enable})
}
func (self class) SetPreProcessTime(secs float64)  { //gd:GPUParticles3D.set_pre_process_time
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_pre_process_time, 0|(gdextension.SizeFloat<<4), &struct{secs float64}{secs})
}
func (self class) SetExplosivenessRatio(ratio float64)  { //gd:GPUParticles3D.set_explosiveness_ratio
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_explosiveness_ratio, 0|(gdextension.SizeFloat<<4), &struct{ratio float64}{ratio})
}
func (self class) SetRandomnessRatio(ratio float64)  { //gd:GPUParticles3D.set_randomness_ratio
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_randomness_ratio, 0|(gdextension.SizeFloat<<4), &struct{ratio float64}{ratio})
}
func (self class) SetVisibilityAabb(aabb AABB.PositionSize)  { //gd:GPUParticles3D.set_visibility_aabb
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_visibility_aabb, 0|(gdextension.SizeAABB<<4), &struct{aabb AABB.PositionSize}{aabb})
}
func (self class) SetUseLocalCoordinates(enable bool)  { //gd:GPUParticles3D.set_use_local_coordinates
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_use_local_coordinates, 0|(gdextension.SizeBool<<4), &struct{enable bool}{enable})
}
func (self class) SetFixedFps(fps int64)  { //gd:GPUParticles3D.set_fixed_fps
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_fixed_fps, 0|(gdextension.SizeInt<<4), &struct{fps int64}{fps})
}
func (self class) SetFractionalDelta(enable bool)  { //gd:GPUParticles3D.set_fractional_delta
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_fractional_delta, 0|(gdextension.SizeBool<<4), &struct{enable bool}{enable})
}
func (self class) SetInterpolate(enable bool)  { //gd:GPUParticles3D.set_interpolate
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_interpolate, 0|(gdextension.SizeBool<<4), &struct{enable bool}{enable})
}
func (self class) SetProcessMaterial(material [1]gdclass.Material)  { //gd:GPUParticles3D.set_process_material
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_process_material, 0|(gdextension.SizeObject<<4), &struct{material gdextension.Object}{	gdextension.Object(gdreference.GetObject(gdclass.GetMaterial(material[0])[0]))})
}
func (self class) SetSpeedScale(scale float64)  { //gd:GPUParticles3D.set_speed_scale
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_speed_scale, 0|(gdextension.SizeFloat<<4), &struct{scale float64}{scale})
}
func (self class) SetCollisionBaseSize(size float64)  { //gd:GPUParticles3D.set_collision_base_size
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_collision_base_size, 0|(gdextension.SizeFloat<<4), &struct{size float64}{size})
}
func (self class) SetInterpToEnd(interp float64)  { //gd:GPUParticles3D.set_interp_to_end
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_interp_to_end, 0|(gdextension.SizeFloat<<4), &struct{interp float64}{interp})
}
func (self class) IsEmitting() bool { //gd:GPUParticles3D.is_emitting
	var r_ret = noescape.Call[bool]( gd.ObjectChecked(self.AsObject()), methods.is_emitting, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) GetAmount() int64 { //gd:GPUParticles3D.get_amount
	var r_ret = noescape.Call[int64]( gd.ObjectChecked(self.AsObject()), methods.get_amount, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) GetLifetime() float64 { //gd:GPUParticles3D.get_lifetime
	var r_ret = noescape.Call[float64]( gd.ObjectChecked(self.AsObject()), methods.get_lifetime, gdextension.SizeFloat, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) GetOneShot() bool { //gd:GPUParticles3D.get_one_shot
	var r_ret = noescape.Call[bool]( gd.ObjectChecked(self.AsObject()), methods.get_one_shot, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) GetPreProcessTime() float64 { //gd:GPUParticles3D.get_pre_process_time
	var r_ret = noescape.Call[float64]( gd.ObjectChecked(self.AsObject()), methods.get_pre_process_time, gdextension.SizeFloat, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) GetExplosivenessRatio() float64 { //gd:GPUParticles3D.get_explosiveness_ratio
	var r_ret = noescape.Call[float64]( gd.ObjectChecked(self.AsObject()), methods.get_explosiveness_ratio, gdextension.SizeFloat, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) GetRandomnessRatio() float64 { //gd:GPUParticles3D.get_randomness_ratio
	var r_ret = noescape.Call[float64]( gd.ObjectChecked(self.AsObject()), methods.get_randomness_ratio, gdextension.SizeFloat, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) GetVisibilityAabb() AABB.PositionSize { //gd:GPUParticles3D.get_visibility_aabb
	var r_ret = noescape.Call[AABB.PositionSize]( gd.ObjectChecked(self.AsObject()), methods.get_visibility_aabb, gdextension.SizeAABB, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) GetUseLocalCoordinates() bool { //gd:GPUParticles3D.get_use_local_coordinates
	var r_ret = noescape.Call[bool]( gd.ObjectChecked(self.AsObject()), methods.get_use_local_coordinates, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) GetFixedFps() int64 { //gd:GPUParticles3D.get_fixed_fps
	var r_ret = noescape.Call[int64]( gd.ObjectChecked(self.AsObject()), methods.get_fixed_fps, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) GetFractionalDelta() bool { //gd:GPUParticles3D.get_fractional_delta
	var r_ret = noescape.Call[bool]( gd.ObjectChecked(self.AsObject()), methods.get_fractional_delta, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) GetInterpolate() bool { //gd:GPUParticles3D.get_interpolate
	var r_ret = noescape.Call[bool]( gd.ObjectChecked(self.AsObject()), methods.get_interpolate, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) GetProcessMaterial() [1]gdclass.Material { //gd:GPUParticles3D.get_process_material
	var r_ret = noescape.Call[gdextension.Object]( gd.ObjectChecked(self.AsObject()), methods.get_process_material, gdextension.SizeObject, &struct{}{})
	var ret = [1]gdclass.Material{gdclass.NewMaterial(gd.PointerWithOwnershipTransferredToGo(r_ret))}
	return ret
}
func (self class) GetSpeedScale() float64 { //gd:GPUParticles3D.get_speed_scale
	var r_ret = noescape.Call[float64]( gd.ObjectChecked(self.AsObject()), methods.get_speed_scale, gdextension.SizeFloat, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) GetCollisionBaseSize() float64 { //gd:GPUParticles3D.get_collision_base_size
	var r_ret = noescape.Call[float64]( gd.ObjectChecked(self.AsObject()), methods.get_collision_base_size, gdextension.SizeFloat, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) GetInterpToEnd() float64 { //gd:GPUParticles3D.get_interp_to_end
	var r_ret = noescape.Call[float64]( gd.ObjectChecked(self.AsObject()), methods.get_interp_to_end, gdextension.SizeFloat, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetUseFixedSeed(use_fixed_seed bool)  { //gd:GPUParticles3D.set_use_fixed_seed
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_use_fixed_seed, 0|(gdextension.SizeBool<<4), &struct{use_fixed_seed bool}{use_fixed_seed})
}
func (self class) GetUseFixedSeed() bool { //gd:GPUParticles3D.get_use_fixed_seed
	var r_ret = noescape.Call[bool]( gd.ObjectChecked(self.AsObject()), methods.get_use_fixed_seed, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetSeed(seed int64)  { //gd:GPUParticles3D.set_seed
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_seed, 0|(gdextension.SizeInt<<4), &struct{seed int64}{seed})
}
func (self class) GetSeed() int64 { //gd:GPUParticles3D.get_seed
	var r_ret = noescape.Call[int64]( gd.ObjectChecked(self.AsObject()), methods.get_seed, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetDrawOrder(order DrawOrder)  { //gd:GPUParticles3D.set_draw_order
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_draw_order, 0|(gdextension.SizeInt<<4), &struct{order DrawOrder}{order})
}
func (self class) GetDrawOrder() DrawOrder { //gd:GPUParticles3D.get_draw_order
	var r_ret = noescape.Call[DrawOrder]( gd.ObjectChecked(self.AsObject()), methods.get_draw_order, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetDrawPasses(passes int64)  { //gd:GPUParticles3D.set_draw_passes
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_draw_passes, 0|(gdextension.SizeInt<<4), &struct{passes int64}{passes})
}
func (self class) SetDrawPassMesh(pass int64, mesh [1]gdclass.Mesh)  { //gd:GPUParticles3D.set_draw_pass_mesh
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_draw_pass_mesh, 0|(gdextension.SizeInt<<4)|(gdextension.SizeObject<<8), &struct{pass int64; mesh gdextension.Object}{pass, 	gdextension.Object(gdreference.GetObject(gdclass.GetMesh(mesh[0])[0]))})
}
func (self class) GetDrawPasses() int64 { //gd:GPUParticles3D.get_draw_passes
	var r_ret = noescape.Call[int64]( gd.ObjectChecked(self.AsObject()), methods.get_draw_passes, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) GetDrawPassMesh(pass int64) [1]gdclass.Mesh { //gd:GPUParticles3D.get_draw_pass_mesh
	var r_ret = noescape.Call[gdextension.Object]( gd.ObjectChecked(self.AsObject()), methods.get_draw_pass_mesh, gdextension.SizeObject|(gdextension.SizeInt<<4), &struct{pass int64}{pass})
	var ret = [1]gdclass.Mesh{gdclass.NewMesh(gd.PointerWithOwnershipTransferredToGo(r_ret))}
	return ret
}
func (self class) SetSkin(skin [1]gdclass.Skin)  { //gd:GPUParticles3D.set_skin
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_skin, 0|(gdextension.SizeObject<<4), &struct{skin gdextension.Object}{	gdextension.Object(gdreference.GetObject(gdclass.GetSkin(skin[0])[0]))})
}
func (self class) GetSkin() [1]gdclass.Skin { //gd:GPUParticles3D.get_skin
	var r_ret = noescape.Call[gdextension.Object]( gd.ObjectChecked(self.AsObject()), methods.get_skin, gdextension.SizeObject, &struct{}{})
	var ret = [1]gdclass.Skin{gdclass.NewSkin(gd.PointerWithOwnershipTransferredToGo(r_ret))}
	return ret
}
func (self class) Restart(keep_seed bool)  { //gd:GPUParticles3D.restart
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.restart, 0|(gdextension.SizeBool<<4), &struct{keep_seed bool}{keep_seed})
}
func (self class) CaptureAabb() AABB.PositionSize { //gd:GPUParticles3D.capture_aabb
	var r_ret = noescape.Call[AABB.PositionSize]( gd.ObjectChecked(self.AsObject()), methods.capture_aabb, gdextension.SizeAABB, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetSubEmitter(path Path.ToNode)  { //gd:GPUParticles3D.set_sub_emitter
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_sub_emitter, 0|(gdextension.SizeNodePath<<4), &struct{path gdextension.NodePath}{pointers.Get(gd.InternalNodePath(path))})
}
func (self class) GetSubEmitter() Path.ToNode { //gd:GPUParticles3D.get_sub_emitter
	var r_ret = noescape.Call[gdextension.NodePath]( gd.ObjectChecked(self.AsObject()), methods.get_sub_emitter, gdextension.SizeNodePath, &struct{}{})
	var ret = Path.ToNode(String.Via(gd.NodePathProxy{}, pointers.Pack(pointers.New[gd.NodePath](r_ret))))
	return ret
}
func (self class) EmitParticle(xform Transform3D.BasisOrigin, velocity Vector3.XYZ, color Color.RGBA, custom Color.RGBA, flags int64)  { //gd:GPUParticles3D.emit_particle
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.emit_particle, 0|(gdextension.SizeTransform3D<<4)|(gdextension.SizeVector3<<8)|(gdextension.SizeColor<<12)|(gdextension.SizeColor<<16)|(gdextension.SizeInt<<20), &struct{xform Transform3D.BasisOrigin; velocity Vector3.XYZ; color Color.RGBA; custom Color.RGBA; flags int64}{gd.Transposed(xform), velocity, color, custom, flags})
}
func (self class) SetTrailEnabled(enabled bool)  { //gd:GPUParticles3D.set_trail_enabled
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_trail_enabled, 0|(gdextension.SizeBool<<4), &struct{enabled bool}{enabled})
}
func (self class) SetTrailLifetime(secs float64)  { //gd:GPUParticles3D.set_trail_lifetime
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_trail_lifetime, 0|(gdextension.SizeFloat<<4), &struct{secs float64}{secs})
}
func (self class) IsTrailEnabled() bool { //gd:GPUParticles3D.is_trail_enabled
	var r_ret = noescape.Call[bool]( gd.ObjectChecked(self.AsObject()), methods.is_trail_enabled, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) GetTrailLifetime() float64 { //gd:GPUParticles3D.get_trail_lifetime
	var r_ret = noescape.Call[float64]( gd.ObjectChecked(self.AsObject()), methods.get_trail_lifetime, gdextension.SizeFloat, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetTransformAlign(align TransformAlign)  { //gd:GPUParticles3D.set_transform_align
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_transform_align, 0|(gdextension.SizeInt<<4), &struct{align TransformAlign}{align})
}
func (self class) GetTransformAlign() TransformAlign { //gd:GPUParticles3D.get_transform_align
	var r_ret = noescape.Call[TransformAlign]( gd.ObjectChecked(self.AsObject()), methods.get_transform_align, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) ConvertFromParticles(particles [1]gdclass.Node)  { //gd:GPUParticles3D.convert_from_particles
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.convert_from_particles, 0|(gdextension.SizeObject<<4), &struct{particles gdextension.Object}{	gdextension.Object(gdreference.GetObject(gdclass.GetNode(particles[0])[0]))})
}
func (self class) SetAmountRatio(ratio float64)  { //gd:GPUParticles3D.set_amount_ratio
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_amount_ratio, 0|(gdextension.SizeFloat<<4), &struct{ratio float64}{ratio})
}
func (self class) GetAmountRatio() float64 { //gd:GPUParticles3D.get_amount_ratio
	var r_ret = noescape.Call[float64]( gd.ObjectChecked(self.AsObject()), methods.get_amount_ratio, gdextension.SizeFloat, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) RequestParticlesProcess(process_time float64)  { //gd:GPUParticles3D.request_particles_process
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.request_particles_process, 0|(gdextension.SizeFloat<<4), &struct{process_time float64}{process_time})
}
func (self Instance) OnFinished(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("finished"), gd.NewCallable(cb), int64(flags_together))
	return self
}



func (self class) Finished() Signal.Any {
return Signal.Via(gd.SignalProxy{}, pointers.Pack(gd.NewSignalOf(self.AsObject(), gd.NewStringName(`finished`))))}

func (o class) AsGPUParticles3D() Advanced { return Advanced(o) }
func (o Instance) AsGPUParticles3D() Instance { return o }
func (o *Extension[T]) AsGPUParticles3D() Instance { return o.Super() }
func (o class) AsGeometryInstance3D() GeometryInstance3D.Advanced { return *(*GeometryInstance3D.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsGeometryInstance3D() GeometryInstance3D.Instance { return o.Super().AsGeometryInstance3D() }
func (o Instance) AsGeometryInstance3D() GeometryInstance3D.Instance { return *(*GeometryInstance3D.Instance)(ie.As(&o)) }
func (o class) AsVisualInstance3D() VisualInstance3D.Advanced { return *(*VisualInstance3D.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsVisualInstance3D() VisualInstance3D.Instance { return o.Super().AsVisualInstance3D() }
func (o Instance) AsVisualInstance3D() VisualInstance3D.Instance { return *(*VisualInstance3D.Instance)(ie.As(&o)) }
func (o class) AsNode3D() Node3D.Advanced { return *(*Node3D.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsNode3D() Node3D.Instance { return o.Super().AsNode3D() }
func (o Instance) AsNode3D() Node3D.Instance { return *(*Node3D.Instance)(ie.As(&o)) }
func (o class) AsNode() Node.Advanced { return *(*Node.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsNode() Node.Instance { return o.Super().AsNode() }
func (o Instance) AsNode() Node.Instance { return *(*Node.Instance)(ie.As(&o)) }

// OnVisibilityChanged is promoted from [Node3D.Instance.OnVisibilityChanged].
func (self Instance) OnVisibilityChanged(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("visibility_changed"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnReady is promoted from [Node.Instance.OnReady].
func (self Instance) OnReady(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("ready"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnRenamed is promoted from [Node.Instance.OnRenamed].
func (self Instance) OnRenamed(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("renamed"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnTreeEntered is promoted from [Node.Instance.OnTreeEntered].
func (self Instance) OnTreeEntered(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("tree_entered"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnTreeExiting is promoted from [Node.Instance.OnTreeExiting].
func (self Instance) OnTreeExiting(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("tree_exiting"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnTreeExited is promoted from [Node.Instance.OnTreeExited].
func (self Instance) OnTreeExited(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("tree_exited"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnChildEnteredTree is promoted from [Node.Instance.OnChildEnteredTree].
func (self Instance) OnChildEnteredTree(cb func(node Node.Instance), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("child_entered_tree"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnChildExitingTree is promoted from [Node.Instance.OnChildExitingTree].
func (self Instance) OnChildExitingTree(cb func(node Node.Instance), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("child_exiting_tree"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnChildOrderChanged is promoted from [Node.Instance.OnChildOrderChanged].
func (self Instance) OnChildOrderChanged(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("child_order_changed"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnReplacingBy is promoted from [Node.Instance.OnReplacingBy].
func (self Instance) OnReplacingBy(cb func(node Node.Instance), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("replacing_by"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnEditorDescriptionChanged is promoted from [Node.Instance.OnEditorDescriptionChanged].
func (self Instance) OnEditorDescriptionChanged(cb func(node Node.Instance), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("editor_description_changed"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnEditorStateChanged is promoted from [Node.Instance.OnEditorStateChanged].
func (self Instance) OnEditorStateChanged(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("editor_state_changed"), gd.NewCallable(cb), int64(flags_together))
	return self
}
func (o *Extension[T]) CaptureAabb() AABB.PositionSize {
	return o.Super().CaptureAabb()
}
func (o *Extension[T]) EmitParticle(xform Transform3D.BasisOrigin, velocity Vector3.XYZ, color Color.RGBA, custom Color.RGBA, flags int) {
	o.Super().EmitParticle(xform, velocity, color, custom, flags)
}
func (o *Extension[T]) ConvertFromParticles(particles Node.Instance) {
	o.Super().ConvertFromParticles(particles)
}
func (o *Extension[T]) RequestParticlesProcess(process_time Float.X) {
	o.Super().RequestParticlesProcess(process_time)
}

// SetInstanceShaderParameter is promoted from [GeometryInstance3D.Instance.SetInstanceShaderParameter].
func (self Instance) SetInstanceShaderParameter(name string, value any) Instance {
	self.AsGeometryInstance3D().SetInstanceShaderParameter(name, value)
	return self
}

// SetInstanceShaderParameter is promoted from [GeometryInstance3D.Instance.SetInstanceShaderParameter].
func (o *Extension[T]) SetInstanceShaderParameter(name string, value any) *Extension[T] {
	o.Super().AsGeometryInstance3D().SetInstanceShaderParameter(name, value)
	return o
}

// GetInstanceShaderParameter is promoted from [GeometryInstance3D.Instance.GetInstanceShaderParameter].
func (self Instance) GetInstanceShaderParameter(name string) any {
	return self.AsGeometryInstance3D().GetInstanceShaderParameter(name)
}

// GetInstanceShaderParameter is promoted from [GeometryInstance3D.Instance.GetInstanceShaderParameter].
func (o *Extension[T]) GetInstanceShaderParameter(name string) any {
	return o.Super().AsGeometryInstance3D().GetInstanceShaderParameter(name)
}

// SetBase is promoted from [VisualInstance3D.Instance.SetBase].
func (self Instance) SetBase(base RID.VisualInstance) Instance {
	self.AsVisualInstance3D().SetBase(base)
	return self
}

// SetBase is promoted from [VisualInstance3D.Instance.SetBase].
func (o *Extension[T]) SetBase(base RID.VisualInstance) *Extension[T] {
	o.Super().AsVisualInstance3D().SetBase(base)
	return o
}

// GetBase is promoted from [VisualInstance3D.Instance.GetBase].
func (self Instance) GetBase() RID.VisualInstance {
	return self.AsVisualInstance3D().GetBase()
}

// GetBase is promoted from [VisualInstance3D.Instance.GetBase].
func (o *Extension[T]) GetBase() RID.VisualInstance {
	return o.Super().AsVisualInstance3D().GetBase()
}

// GetInstance is promoted from [VisualInstance3D.Instance.GetInstance].
func (self Instance) GetInstance() RID.VisualInstance {
	return self.AsVisualInstance3D().GetInstance()
}

// GetInstance is promoted from [VisualInstance3D.Instance.GetInstance].
func (o *Extension[T]) GetInstance() RID.VisualInstance {
	return o.Super().AsVisualInstance3D().GetInstance()
}

// SetLayerMaskValue is promoted from [VisualInstance3D.Instance.SetLayerMaskValue].
func (self Instance) SetLayerMaskValue(layer_number int, value bool) Instance {
	self.AsVisualInstance3D().SetLayerMaskValue(layer_number, value)
	return self
}

// SetLayerMaskValue is promoted from [VisualInstance3D.Instance.SetLayerMaskValue].
func (o *Extension[T]) SetLayerMaskValue(layer_number int, value bool) *Extension[T] {
	o.Super().AsVisualInstance3D().SetLayerMaskValue(layer_number, value)
	return o
}

// GetLayerMaskValue is promoted from [VisualInstance3D.Instance.GetLayerMaskValue].
func (self Instance) GetLayerMaskValue(layer_number int) bool {
	return self.AsVisualInstance3D().GetLayerMaskValue(layer_number)
}

// GetLayerMaskValue is promoted from [VisualInstance3D.Instance.GetLayerMaskValue].
func (o *Extension[T]) GetLayerMaskValue(layer_number int) bool {
	return o.Super().AsVisualInstance3D().GetLayerMaskValue(layer_number)
}

// GetAabb is promoted from [VisualInstance3D.Instance.GetAabb].
func (self Instance) GetAabb() AABB.PositionSize {
	return self.AsVisualInstance3D().GetAabb()
}

// GetAabb is promoted from [VisualInstance3D.Instance.GetAabb].
func (o *Extension[T]) GetAabb() AABB.PositionSize {
	return o.Super().AsVisualInstance3D().GetAabb()
}

// GetGlobalTransformInterpolated is promoted from [Node3D.Instance.GetGlobalTransformInterpolated].
func (self Instance) GetGlobalTransformInterpolated() Transform3D.BasisOrigin {
	return self.AsNode3D().GetGlobalTransformInterpolated()
}

// GetGlobalTransformInterpolated is promoted from [Node3D.Instance.GetGlobalTransformInterpolated].
func (o *Extension[T]) GetGlobalTransformInterpolated() Transform3D.BasisOrigin {
	return o.Super().AsNode3D().GetGlobalTransformInterpolated()
}

// GetParentNode3d is promoted from [Node3D.Instance.GetParentNode3d].
func (self Instance) GetParentNode3d() Node3D.Instance {
	return self.AsNode3D().GetParentNode3d()
}

// GetParentNode3d is promoted from [Node3D.Instance.GetParentNode3d].
func (o *Extension[T]) GetParentNode3d() Node3D.Instance {
	return o.Super().AsNode3D().GetParentNode3d()
}

// SetIgnoreTransformNotification is promoted from [Node3D.Instance.SetIgnoreTransformNotification].
func (self Instance) SetIgnoreTransformNotification(enabled bool) Instance {
	self.AsNode3D().SetIgnoreTransformNotification(enabled)
	return self
}

// SetIgnoreTransformNotification is promoted from [Node3D.Instance.SetIgnoreTransformNotification].
func (o *Extension[T]) SetIgnoreTransformNotification(enabled bool) *Extension[T] {
	o.Super().AsNode3D().SetIgnoreTransformNotification(enabled)
	return o
}

// SetDisableScale is promoted from [Node3D.Instance.SetDisableScale].
func (self Instance) SetDisableScale(disable bool) Instance {
	self.AsNode3D().SetDisableScale(disable)
	return self
}

// SetDisableScale is promoted from [Node3D.Instance.SetDisableScale].
func (o *Extension[T]) SetDisableScale(disable bool) *Extension[T] {
	o.Super().AsNode3D().SetDisableScale(disable)
	return o
}

// IsScaleDisabled is promoted from [Node3D.Instance.IsScaleDisabled].
func (self Instance) IsScaleDisabled() bool {
	return self.AsNode3D().IsScaleDisabled()
}

// IsScaleDisabled is promoted from [Node3D.Instance.IsScaleDisabled].
func (o *Extension[T]) IsScaleDisabled() bool {
	return o.Super().AsNode3D().IsScaleDisabled()
}

// GetWorld3d is promoted from [Node3D.Instance.GetWorld3d].
func (self Instance) GetWorld3d() World3D.Instance {
	return self.AsNode3D().GetWorld3d()
}

// GetWorld3d is promoted from [Node3D.Instance.GetWorld3d].
func (o *Extension[T]) GetWorld3d() World3D.Instance {
	return o.Super().AsNode3D().GetWorld3d()
}

// ForceUpdateTransform is promoted from [Node3D.Instance.ForceUpdateTransform].
func (self Instance) ForceUpdateTransform() {
	self.AsNode3D().ForceUpdateTransform()
}

// ForceUpdateTransform is promoted from [Node3D.Instance.ForceUpdateTransform].
func (o *Extension[T]) ForceUpdateTransform() {
	o.Super().AsNode3D().ForceUpdateTransform()
}

// UpdateGizmos is promoted from [Node3D.Instance.UpdateGizmos].
func (self Instance) UpdateGizmos() {
	self.AsNode3D().UpdateGizmos()
}

// UpdateGizmos is promoted from [Node3D.Instance.UpdateGizmos].
func (o *Extension[T]) UpdateGizmos() {
	o.Super().AsNode3D().UpdateGizmos()
}

// AddGizmo is promoted from [Node3D.Instance.AddGizmo].
func (self Instance) AddGizmo(gizmo Node3DGizmo.Instance) {
	self.AsNode3D().AddGizmo(gizmo)
}

// AddGizmo is promoted from [Node3D.Instance.AddGizmo].
func (o *Extension[T]) AddGizmo(gizmo Node3DGizmo.Instance) {
	o.Super().AsNode3D().AddGizmo(gizmo)
}

// GetGizmos is promoted from [Node3D.Instance.GetGizmos].
func (self Instance) GetGizmos() []Node3DGizmo.Instance {
	return self.AsNode3D().GetGizmos()
}

// GetGizmos is promoted from [Node3D.Instance.GetGizmos].
func (o *Extension[T]) GetGizmos() []Node3DGizmo.Instance {
	return o.Super().AsNode3D().GetGizmos()
}

// ClearGizmos is promoted from [Node3D.Instance.ClearGizmos].
func (self Instance) ClearGizmos() {
	self.AsNode3D().ClearGizmos()
}

// ClearGizmos is promoted from [Node3D.Instance.ClearGizmos].
func (o *Extension[T]) ClearGizmos() {
	o.Super().AsNode3D().ClearGizmos()
}

// SetSubgizmoSelection is promoted from [Node3D.Instance.SetSubgizmoSelection].
func (self Instance) SetSubgizmoSelection(gizmo Node3DGizmo.Instance, id int, transform Transform3D.BasisOrigin) Instance {
	self.AsNode3D().SetSubgizmoSelection(gizmo, id, transform)
	return self
}

// SetSubgizmoSelection is promoted from [Node3D.Instance.SetSubgizmoSelection].
func (o *Extension[T]) SetSubgizmoSelection(gizmo Node3DGizmo.Instance, id int, transform Transform3D.BasisOrigin) *Extension[T] {
	o.Super().AsNode3D().SetSubgizmoSelection(gizmo, id, transform)
	return o
}

// ClearSubgizmoSelection is promoted from [Node3D.Instance.ClearSubgizmoSelection].
func (self Instance) ClearSubgizmoSelection() {
	self.AsNode3D().ClearSubgizmoSelection()
}

// ClearSubgizmoSelection is promoted from [Node3D.Instance.ClearSubgizmoSelection].
func (o *Extension[T]) ClearSubgizmoSelection() {
	o.Super().AsNode3D().ClearSubgizmoSelection()
}

// IsVisibleInTree is promoted from [Node3D.Instance.IsVisibleInTree].
func (self Instance) IsVisibleInTree() bool {
	return self.AsNode3D().IsVisibleInTree()
}

// IsVisibleInTree is promoted from [Node3D.Instance.IsVisibleInTree].
func (o *Extension[T]) IsVisibleInTree() bool {
	return o.Super().AsNode3D().IsVisibleInTree()
}

// Show is promoted from [Node3D.Instance.Show].
func (self Instance) Show() {
	self.AsNode3D().Show()
}

// Show is promoted from [Node3D.Instance.Show].
func (o *Extension[T]) Show() {
	o.Super().AsNode3D().Show()
}

// Hide is promoted from [Node3D.Instance.Hide].
func (self Instance) Hide() {
	self.AsNode3D().Hide()
}

// Hide is promoted from [Node3D.Instance.Hide].
func (o *Extension[T]) Hide() {
	o.Super().AsNode3D().Hide()
}

// SetNotifyLocalTransform is promoted from [Node3D.Instance.SetNotifyLocalTransform].
func (self Instance) SetNotifyLocalTransform(enable bool) Instance {
	self.AsNode3D().SetNotifyLocalTransform(enable)
	return self
}

// SetNotifyLocalTransform is promoted from [Node3D.Instance.SetNotifyLocalTransform].
func (o *Extension[T]) SetNotifyLocalTransform(enable bool) *Extension[T] {
	o.Super().AsNode3D().SetNotifyLocalTransform(enable)
	return o
}

// IsLocalTransformNotificationEnabled is promoted from [Node3D.Instance.IsLocalTransformNotificationEnabled].
func (self Instance) IsLocalTransformNotificationEnabled() bool {
	return self.AsNode3D().IsLocalTransformNotificationEnabled()
}

// IsLocalTransformNotificationEnabled is promoted from [Node3D.Instance.IsLocalTransformNotificationEnabled].
func (o *Extension[T]) IsLocalTransformNotificationEnabled() bool {
	return o.Super().AsNode3D().IsLocalTransformNotificationEnabled()
}

// SetNotifyTransform is promoted from [Node3D.Instance.SetNotifyTransform].
func (self Instance) SetNotifyTransform(enable bool) Instance {
	self.AsNode3D().SetNotifyTransform(enable)
	return self
}

// SetNotifyTransform is promoted from [Node3D.Instance.SetNotifyTransform].
func (o *Extension[T]) SetNotifyTransform(enable bool) *Extension[T] {
	o.Super().AsNode3D().SetNotifyTransform(enable)
	return o
}

// IsTransformNotificationEnabled is promoted from [Node3D.Instance.IsTransformNotificationEnabled].
func (self Instance) IsTransformNotificationEnabled() bool {
	return self.AsNode3D().IsTransformNotificationEnabled()
}

// IsTransformNotificationEnabled is promoted from [Node3D.Instance.IsTransformNotificationEnabled].
func (o *Extension[T]) IsTransformNotificationEnabled() bool {
	return o.Super().AsNode3D().IsTransformNotificationEnabled()
}

// Rotate is promoted from [Node3D.Instance.Rotate].
func (self Instance) Rotate(axis Vector3.XYZ, angle Angle.Radians) {
	self.AsNode3D().Rotate(axis, angle)
}

// Rotate is promoted from [Node3D.Instance.Rotate].
func (o *Extension[T]) Rotate(axis Vector3.XYZ, angle Angle.Radians) {
	o.Super().AsNode3D().Rotate(axis, angle)
}

// GlobalRotate is promoted from [Node3D.Instance.GlobalRotate].
func (self Instance) GlobalRotate(axis Vector3.XYZ, angle Angle.Radians) {
	self.AsNode3D().GlobalRotate(axis, angle)
}

// GlobalRotate is promoted from [Node3D.Instance.GlobalRotate].
func (o *Extension[T]) GlobalRotate(axis Vector3.XYZ, angle Angle.Radians) {
	o.Super().AsNode3D().GlobalRotate(axis, angle)
}

// GlobalScale is promoted from [Node3D.Instance.GlobalScale].
func (self Instance) GlobalScale(scale Vector3.XYZ) {
	self.AsNode3D().GlobalScale(scale)
}

// GlobalScale is promoted from [Node3D.Instance.GlobalScale].
func (o *Extension[T]) GlobalScale(scale Vector3.XYZ) {
	o.Super().AsNode3D().GlobalScale(scale)
}

// GlobalTranslate is promoted from [Node3D.Instance.GlobalTranslate].
func (self Instance) GlobalTranslate(offset Vector3.XYZ) {
	self.AsNode3D().GlobalTranslate(offset)
}

// GlobalTranslate is promoted from [Node3D.Instance.GlobalTranslate].
func (o *Extension[T]) GlobalTranslate(offset Vector3.XYZ) {
	o.Super().AsNode3D().GlobalTranslate(offset)
}

// RotateObjectLocal is promoted from [Node3D.Instance.RotateObjectLocal].
func (self Instance) RotateObjectLocal(axis Vector3.XYZ, angle Angle.Radians) {
	self.AsNode3D().RotateObjectLocal(axis, angle)
}

// RotateObjectLocal is promoted from [Node3D.Instance.RotateObjectLocal].
func (o *Extension[T]) RotateObjectLocal(axis Vector3.XYZ, angle Angle.Radians) {
	o.Super().AsNode3D().RotateObjectLocal(axis, angle)
}

// ScaleObjectLocal is promoted from [Node3D.Instance.ScaleObjectLocal].
func (self Instance) ScaleObjectLocal(scale Vector3.XYZ) {
	self.AsNode3D().ScaleObjectLocal(scale)
}

// ScaleObjectLocal is promoted from [Node3D.Instance.ScaleObjectLocal].
func (o *Extension[T]) ScaleObjectLocal(scale Vector3.XYZ) {
	o.Super().AsNode3D().ScaleObjectLocal(scale)
}

// TranslateObjectLocal is promoted from [Node3D.Instance.TranslateObjectLocal].
func (self Instance) TranslateObjectLocal(offset Vector3.XYZ) {
	self.AsNode3D().TranslateObjectLocal(offset)
}

// TranslateObjectLocal is promoted from [Node3D.Instance.TranslateObjectLocal].
func (o *Extension[T]) TranslateObjectLocal(offset Vector3.XYZ) {
	o.Super().AsNode3D().TranslateObjectLocal(offset)
}

// RotateX is promoted from [Node3D.Instance.RotateX].
func (self Instance) RotateX(angle Angle.Radians) {
	self.AsNode3D().RotateX(angle)
}

// RotateX is promoted from [Node3D.Instance.RotateX].
func (o *Extension[T]) RotateX(angle Angle.Radians) {
	o.Super().AsNode3D().RotateX(angle)
}

// RotateY is promoted from [Node3D.Instance.RotateY].
func (self Instance) RotateY(angle Angle.Radians) {
	self.AsNode3D().RotateY(angle)
}

// RotateY is promoted from [Node3D.Instance.RotateY].
func (o *Extension[T]) RotateY(angle Angle.Radians) {
	o.Super().AsNode3D().RotateY(angle)
}

// RotateZ is promoted from [Node3D.Instance.RotateZ].
func (self Instance) RotateZ(angle Angle.Radians) {
	self.AsNode3D().RotateZ(angle)
}

// RotateZ is promoted from [Node3D.Instance.RotateZ].
func (o *Extension[T]) RotateZ(angle Angle.Radians) {
	o.Super().AsNode3D().RotateZ(angle)
}

// Translate is promoted from [Node3D.Instance.Translate].
func (self Instance) Translate(offset Vector3.XYZ) {
	self.AsNode3D().Translate(offset)
}

// Translate is promoted from [Node3D.Instance.Translate].
func (o *Extension[T]) Translate(offset Vector3.XYZ) {
	o.Super().AsNode3D().Translate(offset)
}

// Orthonormalize is promoted from [Node3D.Instance.Orthonormalize].
func (self Instance) Orthonormalize() {
	self.AsNode3D().Orthonormalize()
}

// Orthonormalize is promoted from [Node3D.Instance.Orthonormalize].
func (o *Extension[T]) Orthonormalize() {
	o.Super().AsNode3D().Orthonormalize()
}

// SetIdentity is promoted from [Node3D.Instance.SetIdentity].
func (self Instance) SetIdentity() Instance {
	self.AsNode3D().SetIdentity()
	return self
}

// SetIdentity is promoted from [Node3D.Instance.SetIdentity].
func (o *Extension[T]) SetIdentity() *Extension[T] {
	o.Super().AsNode3D().SetIdentity()
	return o
}

// ToLocal is promoted from [Node3D.Instance.ToLocal].
func (self Instance) ToLocal(global_point Vector3.XYZ) Vector3.XYZ {
	return self.AsNode3D().ToLocal(global_point)
}

// ToLocal is promoted from [Node3D.Instance.ToLocal].
func (o *Extension[T]) ToLocal(global_point Vector3.XYZ) Vector3.XYZ {
	return o.Super().AsNode3D().ToLocal(global_point)
}

// ToGlobal is promoted from [Node3D.Instance.ToGlobal].
func (self Instance) ToGlobal(local_point Vector3.XYZ) Vector3.XYZ {
	return self.AsNode3D().ToGlobal(local_point)
}

// ToGlobal is promoted from [Node3D.Instance.ToGlobal].
func (o *Extension[T]) ToGlobal(local_point Vector3.XYZ) Vector3.XYZ {
	return o.Super().AsNode3D().ToGlobal(local_point)
}

// RemoveChild is promoted from [Node.Instance.RemoveChild].
func (self Instance) RemoveChild(node Node.Instance) {
	self.AsNode().RemoveChild(node)
}

// RemoveChild is promoted from [Node.Instance.RemoveChild].
func (o *Extension[T]) RemoveChild(node Node.Instance) {
	o.Super().AsNode().RemoveChild(node)
}

// HasNode is promoted from [Node.Instance.HasNode].
func (self Instance) HasNode(path string) bool {
	return self.AsNode().HasNode(path)
}

// HasNode is promoted from [Node.Instance.HasNode].
func (o *Extension[T]) HasNode(path string) bool {
	return o.Super().AsNode().HasNode(path)
}

// GetNode is promoted from [Node.Instance.GetNode].
func (self Instance) GetNode(path string) Node.Instance {
	return self.AsNode().GetNode(path)
}

// GetNode is promoted from [Node.Instance.GetNode].
func (o *Extension[T]) GetNode(path string) Node.Instance {
	return o.Super().AsNode().GetNode(path)
}

// GetNodeOrNull is promoted from [Node.Instance.GetNodeOrNull].
func (self Instance) GetNodeOrNull(path string) Node.Instance {
	return self.AsNode().GetNodeOrNull(path)
}

// GetNodeOrNull is promoted from [Node.Instance.GetNodeOrNull].
func (o *Extension[T]) GetNodeOrNull(path string) Node.Instance {
	return o.Super().AsNode().GetNodeOrNull(path)
}

// GetParent is promoted from [Node.Instance.GetParent].
func (self Instance) GetParent() Node.Instance {
	return self.AsNode().GetParent()
}

// GetParent is promoted from [Node.Instance.GetParent].
func (o *Extension[T]) GetParent() Node.Instance {
	return o.Super().AsNode().GetParent()
}

// FindParent is promoted from [Node.Instance.FindParent].
func (self Instance) FindParent(pattern string) Node.Instance {
	return self.AsNode().FindParent(pattern)
}

// FindParent is promoted from [Node.Instance.FindParent].
func (o *Extension[T]) FindParent(pattern string) Node.Instance {
	return o.Super().AsNode().FindParent(pattern)
}

// HasNodeAndResource is promoted from [Node.Instance.HasNodeAndResource].
func (self Instance) HasNodeAndResource(path string) bool {
	return self.AsNode().HasNodeAndResource(path)
}

// HasNodeAndResource is promoted from [Node.Instance.HasNodeAndResource].
func (o *Extension[T]) HasNodeAndResource(path string) bool {
	return o.Super().AsNode().HasNodeAndResource(path)
}

// IsInsideTree is promoted from [Node.Instance.IsInsideTree].
func (self Instance) IsInsideTree() bool {
	return self.AsNode().IsInsideTree()
}

// IsInsideTree is promoted from [Node.Instance.IsInsideTree].
func (o *Extension[T]) IsInsideTree() bool {
	return o.Super().AsNode().IsInsideTree()
}

// IsPartOfEditedScene is promoted from [Node.Instance.IsPartOfEditedScene].
func (self Instance) IsPartOfEditedScene() bool {
	return self.AsNode().IsPartOfEditedScene()
}

// IsPartOfEditedScene is promoted from [Node.Instance.IsPartOfEditedScene].
func (o *Extension[T]) IsPartOfEditedScene() bool {
	return o.Super().AsNode().IsPartOfEditedScene()
}

// IsAncestorOf is promoted from [Node.Instance.IsAncestorOf].
func (self Instance) IsAncestorOf(node Node.Instance) bool {
	return self.AsNode().IsAncestorOf(node)
}

// IsAncestorOf is promoted from [Node.Instance.IsAncestorOf].
func (o *Extension[T]) IsAncestorOf(node Node.Instance) bool {
	return o.Super().AsNode().IsAncestorOf(node)
}

// IsGreaterThan is promoted from [Node.Instance.IsGreaterThan].
func (self Instance) IsGreaterThan(node Node.Instance) bool {
	return self.AsNode().IsGreaterThan(node)
}

// IsGreaterThan is promoted from [Node.Instance.IsGreaterThan].
func (o *Extension[T]) IsGreaterThan(node Node.Instance) bool {
	return o.Super().AsNode().IsGreaterThan(node)
}

// GetPath is promoted from [Node.Instance.GetPath].
func (self Instance) GetPath() string {
	return self.AsNode().GetPath()
}

// GetPath is promoted from [Node.Instance.GetPath].
func (o *Extension[T]) GetPath() string {
	return o.Super().AsNode().GetPath()
}

// RemoveFromGroup is promoted from [Node.Instance.RemoveFromGroup].
func (self Instance) RemoveFromGroup(group string) {
	self.AsNode().RemoveFromGroup(group)
}

// RemoveFromGroup is promoted from [Node.Instance.RemoveFromGroup].
func (o *Extension[T]) RemoveFromGroup(group string) {
	o.Super().AsNode().RemoveFromGroup(group)
}

// IsInGroup is promoted from [Node.Instance.IsInGroup].
func (self Instance) IsInGroup(group string) bool {
	return self.AsNode().IsInGroup(group)
}

// IsInGroup is promoted from [Node.Instance.IsInGroup].
func (o *Extension[T]) IsInGroup(group string) bool {
	return o.Super().AsNode().IsInGroup(group)
}

// MoveChild is promoted from [Node.Instance.MoveChild].
func (self Instance) MoveChild(child_node Node.Instance, to_index int) {
	self.AsNode().MoveChild(child_node, to_index)
}

// MoveChild is promoted from [Node.Instance.MoveChild].
func (o *Extension[T]) MoveChild(child_node Node.Instance, to_index int) {
	o.Super().AsNode().MoveChild(child_node, to_index)
}

// GetGroups is promoted from [Node.Instance.GetGroups].
func (self Instance) GetGroups() []string {
	return self.AsNode().GetGroups()
}

// GetGroups is promoted from [Node.Instance.GetGroups].
func (o *Extension[T]) GetGroups() []string {
	return o.Super().AsNode().GetGroups()
}

// PrintTree is promoted from [Node.Instance.PrintTree].
func (self Instance) PrintTree() {
	self.AsNode().PrintTree()
}

// PrintTree is promoted from [Node.Instance.PrintTree].
func (o *Extension[T]) PrintTree() {
	o.Super().AsNode().PrintTree()
}

// PrintTreePretty is promoted from [Node.Instance.PrintTreePretty].
func (self Instance) PrintTreePretty() {
	self.AsNode().PrintTreePretty()
}

// PrintTreePretty is promoted from [Node.Instance.PrintTreePretty].
func (o *Extension[T]) PrintTreePretty() {
	o.Super().AsNode().PrintTreePretty()
}

// GetTreeString is promoted from [Node.Instance.GetTreeString].
func (self Instance) GetTreeString() string {
	return self.AsNode().GetTreeString()
}

// GetTreeString is promoted from [Node.Instance.GetTreeString].
func (o *Extension[T]) GetTreeString() string {
	return o.Super().AsNode().GetTreeString()
}

// GetTreeStringPretty is promoted from [Node.Instance.GetTreeStringPretty].
func (self Instance) GetTreeStringPretty() string {
	return self.AsNode().GetTreeStringPretty()
}

// GetTreeStringPretty is promoted from [Node.Instance.GetTreeStringPretty].
func (o *Extension[T]) GetTreeStringPretty() string {
	return o.Super().AsNode().GetTreeStringPretty()
}

// PropagateNotification is promoted from [Node.Instance.PropagateNotification].
func (self Instance) PropagateNotification(what int) {
	self.AsNode().PropagateNotification(what)
}

// PropagateNotification is promoted from [Node.Instance.PropagateNotification].
func (o *Extension[T]) PropagateNotification(what int) {
	o.Super().AsNode().PropagateNotification(what)
}

// SetPhysicsProcess is promoted from [Node.Instance.SetPhysicsProcess].
func (self Instance) SetPhysicsProcess(enable bool) Instance {
	self.AsNode().SetPhysicsProcess(enable)
	return self
}

// SetPhysicsProcess is promoted from [Node.Instance.SetPhysicsProcess].
func (o *Extension[T]) SetPhysicsProcess(enable bool) *Extension[T] {
	o.Super().AsNode().SetPhysicsProcess(enable)
	return o
}

// GetPhysicsProcessDeltaTime is promoted from [Node.Instance.GetPhysicsProcessDeltaTime].
func (self Instance) GetPhysicsProcessDeltaTime() Float.X {
	return self.AsNode().GetPhysicsProcessDeltaTime()
}

// GetPhysicsProcessDeltaTime is promoted from [Node.Instance.GetPhysicsProcessDeltaTime].
func (o *Extension[T]) GetPhysicsProcessDeltaTime() Float.X {
	return o.Super().AsNode().GetPhysicsProcessDeltaTime()
}

// IsPhysicsProcessing is promoted from [Node.Instance.IsPhysicsProcessing].
func (self Instance) IsPhysicsProcessing() bool {
	return self.AsNode().IsPhysicsProcessing()
}

// IsPhysicsProcessing is promoted from [Node.Instance.IsPhysicsProcessing].
func (o *Extension[T]) IsPhysicsProcessing() bool {
	return o.Super().AsNode().IsPhysicsProcessing()
}

// GetProcessDeltaTime is promoted from [Node.Instance.GetProcessDeltaTime].
func (self Instance) GetProcessDeltaTime() Float.X {
	return self.AsNode().GetProcessDeltaTime()
}

// GetProcessDeltaTime is promoted from [Node.Instance.GetProcessDeltaTime].
func (o *Extension[T]) GetProcessDeltaTime() Float.X {
	return o.Super().AsNode().GetProcessDeltaTime()
}

// SetProcess is promoted from [Node.Instance.SetProcess].
func (self Instance) SetProcess(enable bool) Instance {
	self.AsNode().SetProcess(enable)
	return self
}

// SetProcess is promoted from [Node.Instance.SetProcess].
func (o *Extension[T]) SetProcess(enable bool) *Extension[T] {
	o.Super().AsNode().SetProcess(enable)
	return o
}

// IsProcessing is promoted from [Node.Instance.IsProcessing].
func (self Instance) IsProcessing() bool {
	return self.AsNode().IsProcessing()
}

// IsProcessing is promoted from [Node.Instance.IsProcessing].
func (o *Extension[T]) IsProcessing() bool {
	return o.Super().AsNode().IsProcessing()
}

// SetProcessInput is promoted from [Node.Instance.SetProcessInput].
func (self Instance) SetProcessInput(enable bool) Instance {
	self.AsNode().SetProcessInput(enable)
	return self
}

// SetProcessInput is promoted from [Node.Instance.SetProcessInput].
func (o *Extension[T]) SetProcessInput(enable bool) *Extension[T] {
	o.Super().AsNode().SetProcessInput(enable)
	return o
}

// IsProcessingInput is promoted from [Node.Instance.IsProcessingInput].
func (self Instance) IsProcessingInput() bool {
	return self.AsNode().IsProcessingInput()
}

// IsProcessingInput is promoted from [Node.Instance.IsProcessingInput].
func (o *Extension[T]) IsProcessingInput() bool {
	return o.Super().AsNode().IsProcessingInput()
}

// SetProcessShortcutInput is promoted from [Node.Instance.SetProcessShortcutInput].
func (self Instance) SetProcessShortcutInput(enable bool) Instance {
	self.AsNode().SetProcessShortcutInput(enable)
	return self
}

// SetProcessShortcutInput is promoted from [Node.Instance.SetProcessShortcutInput].
func (o *Extension[T]) SetProcessShortcutInput(enable bool) *Extension[T] {
	o.Super().AsNode().SetProcessShortcutInput(enable)
	return o
}

// IsProcessingShortcutInput is promoted from [Node.Instance.IsProcessingShortcutInput].
func (self Instance) IsProcessingShortcutInput() bool {
	return self.AsNode().IsProcessingShortcutInput()
}

// IsProcessingShortcutInput is promoted from [Node.Instance.IsProcessingShortcutInput].
func (o *Extension[T]) IsProcessingShortcutInput() bool {
	return o.Super().AsNode().IsProcessingShortcutInput()
}

// SetProcessUnhandledInput is promoted from [Node.Instance.SetProcessUnhandledInput].
func (self Instance) SetProcessUnhandledInput(enable bool) Instance {
	self.AsNode().SetProcessUnhandledInput(enable)
	return self
}

// SetProcessUnhandledInput is promoted from [Node.Instance.SetProcessUnhandledInput].
func (o *Extension[T]) SetProcessUnhandledInput(enable bool) *Extension[T] {
	o.Super().AsNode().SetProcessUnhandledInput(enable)
	return o
}

// IsProcessingUnhandledInput is promoted from [Node.Instance.IsProcessingUnhandledInput].
func (self Instance) IsProcessingUnhandledInput() bool {
	return self.AsNode().IsProcessingUnhandledInput()
}

// IsProcessingUnhandledInput is promoted from [Node.Instance.IsProcessingUnhandledInput].
func (o *Extension[T]) IsProcessingUnhandledInput() bool {
	return o.Super().AsNode().IsProcessingUnhandledInput()
}

// SetProcessUnhandledKeyInput is promoted from [Node.Instance.SetProcessUnhandledKeyInput].
func (self Instance) SetProcessUnhandledKeyInput(enable bool) Instance {
	self.AsNode().SetProcessUnhandledKeyInput(enable)
	return self
}

// SetProcessUnhandledKeyInput is promoted from [Node.Instance.SetProcessUnhandledKeyInput].
func (o *Extension[T]) SetProcessUnhandledKeyInput(enable bool) *Extension[T] {
	o.Super().AsNode().SetProcessUnhandledKeyInput(enable)
	return o
}

// IsProcessingUnhandledKeyInput is promoted from [Node.Instance.IsProcessingUnhandledKeyInput].
func (self Instance) IsProcessingUnhandledKeyInput() bool {
	return self.AsNode().IsProcessingUnhandledKeyInput()
}

// IsProcessingUnhandledKeyInput is promoted from [Node.Instance.IsProcessingUnhandledKeyInput].
func (o *Extension[T]) IsProcessingUnhandledKeyInput() bool {
	return o.Super().AsNode().IsProcessingUnhandledKeyInput()
}

// CanProcess is promoted from [Node.Instance.CanProcess].
func (self Instance) CanProcess() bool {
	return self.AsNode().CanProcess()
}

// CanProcess is promoted from [Node.Instance.CanProcess].
func (o *Extension[T]) CanProcess() bool {
	return o.Super().AsNode().CanProcess()
}

// QueueAccessibilityUpdate is promoted from [Node.Instance.QueueAccessibilityUpdate].
func (self Instance) QueueAccessibilityUpdate() {
	self.AsNode().QueueAccessibilityUpdate()
}

// QueueAccessibilityUpdate is promoted from [Node.Instance.QueueAccessibilityUpdate].
func (o *Extension[T]) QueueAccessibilityUpdate() {
	o.Super().AsNode().QueueAccessibilityUpdate()
}

// GetAccessibilityElement is promoted from [Node.Instance.GetAccessibilityElement].
func (self Instance) GetAccessibilityElement() RID.AccessibilityElement {
	return self.AsNode().GetAccessibilityElement()
}

// GetAccessibilityElement is promoted from [Node.Instance.GetAccessibilityElement].
func (o *Extension[T]) GetAccessibilityElement() RID.AccessibilityElement {
	return o.Super().AsNode().GetAccessibilityElement()
}

// SetDisplayFolded is promoted from [Node.Instance.SetDisplayFolded].
func (self Instance) SetDisplayFolded(fold bool) Instance {
	self.AsNode().SetDisplayFolded(fold)
	return self
}

// SetDisplayFolded is promoted from [Node.Instance.SetDisplayFolded].
func (o *Extension[T]) SetDisplayFolded(fold bool) *Extension[T] {
	o.Super().AsNode().SetDisplayFolded(fold)
	return o
}

// IsDisplayedFolded is promoted from [Node.Instance.IsDisplayedFolded].
func (self Instance) IsDisplayedFolded() bool {
	return self.AsNode().IsDisplayedFolded()
}

// IsDisplayedFolded is promoted from [Node.Instance.IsDisplayedFolded].
func (o *Extension[T]) IsDisplayedFolded() bool {
	return o.Super().AsNode().IsDisplayedFolded()
}

// SetProcessInternal is promoted from [Node.Instance.SetProcessInternal].
func (self Instance) SetProcessInternal(enable bool) Instance {
	self.AsNode().SetProcessInternal(enable)
	return self
}

// SetProcessInternal is promoted from [Node.Instance.SetProcessInternal].
func (o *Extension[T]) SetProcessInternal(enable bool) *Extension[T] {
	o.Super().AsNode().SetProcessInternal(enable)
	return o
}

// IsProcessingInternal is promoted from [Node.Instance.IsProcessingInternal].
func (self Instance) IsProcessingInternal() bool {
	return self.AsNode().IsProcessingInternal()
}

// IsProcessingInternal is promoted from [Node.Instance.IsProcessingInternal].
func (o *Extension[T]) IsProcessingInternal() bool {
	return o.Super().AsNode().IsProcessingInternal()
}

// SetPhysicsProcessInternal is promoted from [Node.Instance.SetPhysicsProcessInternal].
func (self Instance) SetPhysicsProcessInternal(enable bool) Instance {
	self.AsNode().SetPhysicsProcessInternal(enable)
	return self
}

// SetPhysicsProcessInternal is promoted from [Node.Instance.SetPhysicsProcessInternal].
func (o *Extension[T]) SetPhysicsProcessInternal(enable bool) *Extension[T] {
	o.Super().AsNode().SetPhysicsProcessInternal(enable)
	return o
}

// IsPhysicsProcessingInternal is promoted from [Node.Instance.IsPhysicsProcessingInternal].
func (self Instance) IsPhysicsProcessingInternal() bool {
	return self.AsNode().IsPhysicsProcessingInternal()
}

// IsPhysicsProcessingInternal is promoted from [Node.Instance.IsPhysicsProcessingInternal].
func (o *Extension[T]) IsPhysicsProcessingInternal() bool {
	return o.Super().AsNode().IsPhysicsProcessingInternal()
}

// IsPhysicsInterpolated is promoted from [Node.Instance.IsPhysicsInterpolated].
func (self Instance) IsPhysicsInterpolated() bool {
	return self.AsNode().IsPhysicsInterpolated()
}

// IsPhysicsInterpolated is promoted from [Node.Instance.IsPhysicsInterpolated].
func (o *Extension[T]) IsPhysicsInterpolated() bool {
	return o.Super().AsNode().IsPhysicsInterpolated()
}

// IsPhysicsInterpolatedAndEnabled is promoted from [Node.Instance.IsPhysicsInterpolatedAndEnabled].
func (self Instance) IsPhysicsInterpolatedAndEnabled() bool {
	return self.AsNode().IsPhysicsInterpolatedAndEnabled()
}

// IsPhysicsInterpolatedAndEnabled is promoted from [Node.Instance.IsPhysicsInterpolatedAndEnabled].
func (o *Extension[T]) IsPhysicsInterpolatedAndEnabled() bool {
	return o.Super().AsNode().IsPhysicsInterpolatedAndEnabled()
}

// ResetPhysicsInterpolation is promoted from [Node.Instance.ResetPhysicsInterpolation].
func (self Instance) ResetPhysicsInterpolation() {
	self.AsNode().ResetPhysicsInterpolation()
}

// ResetPhysicsInterpolation is promoted from [Node.Instance.ResetPhysicsInterpolation].
func (o *Extension[T]) ResetPhysicsInterpolation() {
	o.Super().AsNode().ResetPhysicsInterpolation()
}

// CanAutoTranslate is promoted from [Node.Instance.CanAutoTranslate].
func (self Instance) CanAutoTranslate() bool {
	return self.AsNode().CanAutoTranslate()
}

// CanAutoTranslate is promoted from [Node.Instance.CanAutoTranslate].
func (o *Extension[T]) CanAutoTranslate() bool {
	return o.Super().AsNode().CanAutoTranslate()
}

// SetTranslationDomainInherited is promoted from [Node.Instance.SetTranslationDomainInherited].
func (self Instance) SetTranslationDomainInherited() Instance {
	self.AsNode().SetTranslationDomainInherited()
	return self
}

// SetTranslationDomainInherited is promoted from [Node.Instance.SetTranslationDomainInherited].
func (o *Extension[T]) SetTranslationDomainInherited() *Extension[T] {
	o.Super().AsNode().SetTranslationDomainInherited()
	return o
}

// CreateTween is promoted from [Node.Instance.CreateTween].
func (self Instance) CreateTween() Tween.Instance {
	return self.AsNode().CreateTween()
}

// CreateTween is promoted from [Node.Instance.CreateTween].
func (o *Extension[T]) CreateTween() Tween.Instance {
	return o.Super().AsNode().CreateTween()
}

// SetSceneInstanceLoadPlaceholder is promoted from [Node.Instance.SetSceneInstanceLoadPlaceholder].
func (self Instance) SetSceneInstanceLoadPlaceholder(load_placeholder bool) Instance {
	self.AsNode().SetSceneInstanceLoadPlaceholder(load_placeholder)
	return self
}

// SetSceneInstanceLoadPlaceholder is promoted from [Node.Instance.SetSceneInstanceLoadPlaceholder].
func (o *Extension[T]) SetSceneInstanceLoadPlaceholder(load_placeholder bool) *Extension[T] {
	o.Super().AsNode().SetSceneInstanceLoadPlaceholder(load_placeholder)
	return o
}

// GetSceneInstanceLoadPlaceholder is promoted from [Node.Instance.GetSceneInstanceLoadPlaceholder].
func (self Instance) GetSceneInstanceLoadPlaceholder() bool {
	return self.AsNode().GetSceneInstanceLoadPlaceholder()
}

// GetSceneInstanceLoadPlaceholder is promoted from [Node.Instance.GetSceneInstanceLoadPlaceholder].
func (o *Extension[T]) GetSceneInstanceLoadPlaceholder() bool {
	return o.Super().AsNode().GetSceneInstanceLoadPlaceholder()
}

// SetEditableInstance is promoted from [Node.Instance.SetEditableInstance].
func (self Instance) SetEditableInstance(node Node.Instance, is_editable bool) Instance {
	self.AsNode().SetEditableInstance(node, is_editable)
	return self
}

// SetEditableInstance is promoted from [Node.Instance.SetEditableInstance].
func (o *Extension[T]) SetEditableInstance(node Node.Instance, is_editable bool) *Extension[T] {
	o.Super().AsNode().SetEditableInstance(node, is_editable)
	return o
}

// IsEditableInstance is promoted from [Node.Instance.IsEditableInstance].
func (self Instance) IsEditableInstance(node Node.Instance) bool {
	return self.AsNode().IsEditableInstance(node)
}

// IsEditableInstance is promoted from [Node.Instance.IsEditableInstance].
func (o *Extension[T]) IsEditableInstance(node Node.Instance) bool {
	return o.Super().AsNode().IsEditableInstance(node)
}

// QueueFree is promoted from [Node.Instance.QueueFree].
func (self Instance) QueueFree() {
	self.AsNode().QueueFree()
}

// QueueFree is promoted from [Node.Instance.QueueFree].
func (o *Extension[T]) QueueFree() {
	o.Super().AsNode().QueueFree()
}

// RequestReady is promoted from [Node.Instance.RequestReady].
func (self Instance) RequestReady() {
	self.AsNode().RequestReady()
}

// RequestReady is promoted from [Node.Instance.RequestReady].
func (o *Extension[T]) RequestReady() {
	o.Super().AsNode().RequestReady()
}

// IsNodeReady is promoted from [Node.Instance.IsNodeReady].
func (self Instance) IsNodeReady() bool {
	return self.AsNode().IsNodeReady()
}

// IsNodeReady is promoted from [Node.Instance.IsNodeReady].
func (o *Extension[T]) IsNodeReady() bool {
	return o.Super().AsNode().IsNodeReady()
}

// GetMultiplayerAuthority is promoted from [Node.Instance.GetMultiplayerAuthority].
func (self Instance) GetMultiplayerAuthority() int {
	return self.AsNode().GetMultiplayerAuthority()
}

// GetMultiplayerAuthority is promoted from [Node.Instance.GetMultiplayerAuthority].
func (o *Extension[T]) GetMultiplayerAuthority() int {
	return o.Super().AsNode().GetMultiplayerAuthority()
}

// IsMultiplayerAuthority is promoted from [Node.Instance.IsMultiplayerAuthority].
func (self Instance) IsMultiplayerAuthority() bool {
	return self.AsNode().IsMultiplayerAuthority()
}

// IsMultiplayerAuthority is promoted from [Node.Instance.IsMultiplayerAuthority].
func (o *Extension[T]) IsMultiplayerAuthority() bool {
	return o.Super().AsNode().IsMultiplayerAuthority()
}

// RpcConfig is promoted from [Node.Instance.RpcConfig].
func (self Instance) RpcConfig(method string, config any) {
	self.AsNode().RpcConfig(method, config)
}

// RpcConfig is promoted from [Node.Instance.RpcConfig].
func (o *Extension[T]) RpcConfig(method string, config any) {
	o.Super().AsNode().RpcConfig(method, config)
}

// GetNodeRpcConfig is promoted from [Node.Instance.GetNodeRpcConfig].
func (self Instance) GetNodeRpcConfig() any {
	return self.AsNode().GetNodeRpcConfig()
}

// GetNodeRpcConfig is promoted from [Node.Instance.GetNodeRpcConfig].
func (o *Extension[T]) GetNodeRpcConfig() any {
	return o.Super().AsNode().GetNodeRpcConfig()
}

// UpdateConfigurationWarnings is promoted from [Node.Instance.UpdateConfigurationWarnings].
func (self Instance) UpdateConfigurationWarnings() {
	self.AsNode().UpdateConfigurationWarnings()
}

// UpdateConfigurationWarnings is promoted from [Node.Instance.UpdateConfigurationWarnings].
func (o *Extension[T]) UpdateConfigurationWarnings() {
	o.Super().AsNode().UpdateConfigurationWarnings()
}

// SetDeferredThreadGroup is promoted from [Node.Instance.SetDeferredThreadGroup].
func (self Instance) SetDeferredThreadGroup(property string, value any) Instance {
	self.AsNode().SetDeferredThreadGroup(property, value)
	return self
}

// SetDeferredThreadGroup is promoted from [Node.Instance.SetDeferredThreadGroup].
func (o *Extension[T]) SetDeferredThreadGroup(property string, value any) *Extension[T] {
	o.Super().AsNode().SetDeferredThreadGroup(property, value)
	return o
}

// NotifyDeferredThreadGroup is promoted from [Node.Instance.NotifyDeferredThreadGroup].
func (self Instance) NotifyDeferredThreadGroup(what int) {
	self.AsNode().NotifyDeferredThreadGroup(what)
}

// NotifyDeferredThreadGroup is promoted from [Node.Instance.NotifyDeferredThreadGroup].
func (o *Extension[T]) NotifyDeferredThreadGroup(what int) {
	o.Super().AsNode().NotifyDeferredThreadGroup(what)
}

// SetThreadSafe is promoted from [Node.Instance.SetThreadSafe].
func (self Instance) SetThreadSafe(property string, value any) Instance {
	self.AsNode().SetThreadSafe(property, value)
	return self
}

// SetThreadSafe is promoted from [Node.Instance.SetThreadSafe].
func (o *Extension[T]) SetThreadSafe(property string, value any) *Extension[T] {
	o.Super().AsNode().SetThreadSafe(property, value)
	return o
}

// NotifyThreadSafe is promoted from [Node.Instance.NotifyThreadSafe].
func (self Instance) NotifyThreadSafe(what int) {
	self.AsNode().NotifyThreadSafe(what)
}

// NotifyThreadSafe is promoted from [Node.Instance.NotifyThreadSafe].
func (o *Extension[T]) NotifyThreadSafe(what int) {
	o.Super().AsNode().NotifyThreadSafe(what)
}

func (self class) Virtual(name string) reflect.Value {
	switch name {
	default: return gd.VirtualByName(GeometryInstance3D.Advanced(self.AsGeometryInstance3D()), name)
	}
}

func (self Instance) Virtual(name string) reflect.Value {
	switch name {
	default: return gd.VirtualByName(GeometryInstance3D.Instance(self.AsGeometryInstance3D()), name)
	}
}
func init() {gdclass.Register("GPUParticles3D", func(ptr gdreference.Object) any { return Instance{gdclass.NewGPUParticles3D(ptr)} })}
type DrawOrder int64//gd:GPUParticles3D.DrawOrder

const (
	DrawOrderIndex DrawOrder = 0
	DrawOrderLifetime DrawOrder = 1
	DrawOrderReverseLifetime DrawOrder = 2
	DrawOrderViewDepth DrawOrder = 3
)
type EmitFlags int64//gd:GPUParticles3D.EmitFlags

const (
	EmitFlagPosition EmitFlags = 1
	EmitFlagRotationScale EmitFlags = 2
	EmitFlagVelocity EmitFlags = 4
	EmitFlagColor EmitFlags = 8
	EmitFlagCustom EmitFlags = 16
)
type TransformAlign int64//gd:GPUParticles3D.TransformAlign

const (
	TransformAlignDisabled TransformAlign = 0
	TransformAlignZBillboard TransformAlign = 1
	TransformAlignYToVelocity TransformAlign = 2
	TransformAlignZBillboardYToVelocity TransformAlign = 3
)
const MaxDrawPasses int = 4 //gd:GPUParticles3D.MAX_DRAW_PASSES
