// Code generated by the generate package DO NOT EDIT


package OpenXRActionMap

import "reflect"
import "slices"
import "graphics.gd/internal/pointers"
import "graphics.gd/internal/callframe"
import "graphics.gd/internal/gdextension"
import "graphics.gd/internal/gdreference"
import "graphics.gd/internal/noescape"
import gd "graphics.gd/internal"
import "graphics.gd/internal/gdclass"
import "graphics.gd/internal/ie"
import "graphics.gd/variant"
import "graphics.gd/variant/Angle"
import "graphics.gd/variant/Euler"
import "graphics.gd/variant/Signal"
import "graphics.gd/classdb/OpenXRActionSet"
import "graphics.gd/classdb/OpenXRInteractionProfile"
import "graphics.gd/classdb/Resource"
import "graphics.gd/variant/Array"
import "graphics.gd/variant/Callable"
import "graphics.gd/variant/Dictionary"
import "graphics.gd/variant/Error"
import "graphics.gd/variant/Float"
import "graphics.gd/variant/Object"
import "graphics.gd/variant/Packed"
import "graphics.gd/variant/Path"
import "graphics.gd/variant/RID"
import "graphics.gd/variant/RefCounted"
import "graphics.gd/variant/String"

var _ Object.ID
type _ gdclass.Node
var _ gd.String
var _ RefCounted.Instance
var _ reflect.Type
var _ callframe.Frame
var _ = pointers.Cycle
var _ = Array.Nil
var _ variant.Any
var _ Callable.Function
var _ Dictionary.Any
var _ RID.Any
var _ noescape.Variant
var _ String.Readable
var _ Path.ToNode
var _ Packed.Bytes
var _ Error.Code
var _ Float.X
var _ Signal.Any
var _ Angle.Radians
var _ Euler.Radians
var _ gdextension.Object
var _ = slices.Delete[[]struct{}, struct{}]

/*
ID is a typed object ID (reference) to an instance of this class, use it to store references to objects with
unknown lifetimes, as an ID will not panic on use if the underlying object has been destroyed.
*/
type ID Object.ID
func (id ID) Instance() (Instance, bool) { return Object.As[Instance](Object.ID(id).Instance()) }
/*
Extension can be embedded in a new struct to create a Go extension of this class.

T must be a type that is embedding this [Extension] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Extension[T gdclass.Interface] struct { gdclass.Extension[T, Instance] }
/*
Singleton can be embedded in a new struct to create a Go singleton extension of the class.

It will become available as a global inside scripts and any any other Go Extension types will
have any *T typed fields filled in to point at this singleton once they have been instantiated.

T must be a type that is embedding this [Singleton] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Singleton[T gdclass.Interface] = Extension[T]
// Instance of the class with convieniently typed arguments and results.
type Instance [1]gdclass.OpenXRActionMap
var otype gdextension.ObjectType
var sname gdextension.StringName
var methods struct {
	set_action_sets gdextension.MethodForClass `hash:"381264803"`
	get_action_sets gdextension.MethodForClass `hash:"3995934104"`
	get_action_set_count gdextension.MethodForClass `hash:"3905245786"`
	find_action_set gdextension.MethodForClass `hash:"1888809267"`
	get_action_set gdextension.MethodForClass `hash:"1789580336"`
	add_action_set gdextension.MethodForClass `hash:"2093310581"`
	remove_action_set gdextension.MethodForClass `hash:"2093310581"`
	set_interaction_profiles gdextension.MethodForClass `hash:"381264803"`
	get_interaction_profiles gdextension.MethodForClass `hash:"3995934104"`
	get_interaction_profile_count gdextension.MethodForClass `hash:"3905245786"`
	find_interaction_profile gdextension.MethodForClass `hash:"3095875538"`
	get_interaction_profile gdextension.MethodForClass `hash:"2546151210"`
	add_interaction_profile gdextension.MethodForClass `hash:"2697953512"`
	remove_interaction_profile gdextension.MethodForClass `hash:"2697953512"`
	create_default_action_sets gdextension.MethodForClass `hash:"3218959716"`
}
func init() {
	gd.Links = append(gd.Links, func() {
		sname = gdextension.Host.Strings.Intern.UTF8("OpenXRActionMap")
		otype = gdextension.Host.Objects.Type(sname)
		gd.LinkMethods(sname, &methods, false)
		})
	gd.RegisterCleanup(func() {
		noescape.Free(gdextension.TypeStringName, &sname)
	})
}
func (self Instance) ID() ID { return ID(Object.Instance(self.AsObject()).ID()) }
// Nil is a nil/null instance of the class. Equivalent to the zero value.
var Nil Instance
type Any interface {
	gd.IsClass
	AsOpenXRActionMap() Instance
}
func (self Instance) GetActionSetCount() int { //gd:OpenXRActionMap.get_action_set_count
	return int(int(Advanced(self).GetActionSetCount()))
}
func (self Instance) FindActionSet(name string) OpenXRActionSet.Instance { //gd:OpenXRActionMap.find_action_set
	return OpenXRActionSet.Instance(Advanced(self).FindActionSet(String.From(name)))
}
func (self Instance) GetActionSet(idx int) OpenXRActionSet.Instance { //gd:OpenXRActionMap.get_action_set
	return OpenXRActionSet.Instance(Advanced(self).GetActionSet(int64(idx)))
}
func (self Instance) AddActionSet(action_set OpenXRActionSet.Instance) { //gd:OpenXRActionMap.add_action_set
	Advanced(self).AddActionSet(action_set)
}
func (self Instance) RemoveActionSet(action_set OpenXRActionSet.Instance) { //gd:OpenXRActionMap.remove_action_set
	Advanced(self).RemoveActionSet(action_set)
}
func (self Instance) GetInteractionProfileCount() int { //gd:OpenXRActionMap.get_interaction_profile_count
	return int(int(Advanced(self).GetInteractionProfileCount()))
}
func (self Instance) FindInteractionProfile(name string) OpenXRInteractionProfile.Instance { //gd:OpenXRActionMap.find_interaction_profile
	return OpenXRInteractionProfile.Instance(Advanced(self).FindInteractionProfile(String.From(name)))
}
func (self Instance) GetInteractionProfile(idx int) OpenXRInteractionProfile.Instance { //gd:OpenXRActionMap.get_interaction_profile
	return OpenXRInteractionProfile.Instance(Advanced(self).GetInteractionProfile(int64(idx)))
}
func (self Instance) AddInteractionProfile(interaction_profile OpenXRInteractionProfile.Instance) { //gd:OpenXRActionMap.add_interaction_profile
	Advanced(self).AddInteractionProfile(interaction_profile)
}
func (self Instance) RemoveInteractionProfile(interaction_profile OpenXRInteractionProfile.Instance) { //gd:OpenXRActionMap.remove_interaction_profile
	Advanced(self).RemoveInteractionProfile(interaction_profile)
}
func (self Instance) CreateDefaultActionSets() { //gd:OpenXRActionMap.create_default_action_sets
	Advanced(self).CreateDefaultActionSets()
}
// Advanced exposes a 1:1 low-level instance of the class, undocumented, for those who know what they are doing.
type Advanced = class
type class [1]gdclass.OpenXRActionMap
func (o class) AsObject() [1]gdreference.Object { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (self *class) SetObject(obj [1]gdreference.Object) bool {
	if gdextension.Host.Objects.Cast(gdreference.GetObject(obj[0]), otype) != 0 {
		self[0] = gdclass.NewOpenXRActionMap(obj[0])
		return true
	}
	return false
}
func (self *Instance) SetObject(obj [1]gdreference.Object) bool {
	if gdextension.Host.Objects.Cast(gdreference.GetObject(obj[0]), otype) != 0 {
		self[0] = gdclass.NewOpenXRActionMap(obj[0])
		return true
	}
	return false
}
func (o Instance) AsObject() [1]gdreference.Object { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (o *Extension[T]) AsObject() [1]gdreference.Object { return o.Super().AsObject() }
func New() Instance {
if !gd.Linked {
		var placeholder = Instance([1]gdclass.OpenXRActionMap{gdclass.NewOpenXRActionMap(gdreference.NewObject())})
		gd.StartupFunctions = append(gd.StartupFunctions, func() {
			if gd.Linked {
				raw, _ := gdreference.EndObject(New().AsObject()[0])
				gdreference.SetObject(gdclass.GetOpenXRActionMap(placeholder[0])[0], raw)
				gd.RegisterCleanup(func() {
					if raw := gdreference.GetObject(placeholder.AsObject()[0]); raw != 0 {
						gdextension.Host.Objects.Unsafe.Free(raw)
					}
				})
			}
		})
		return placeholder
	}
	casted := Instance([1]gdclass.OpenXRActionMap{gdclass.NewOpenXRActionMap(gdreference.OwnObject(gdextension.Host.Objects.Make(sname), gd.Free))})
	casted.AsRefCounted()[0].InitRef()
	gd.ObjectNotification(casted.AsObject()[0], 0, false)
	return casted
}

func (self Instance) ActionSets() []OpenXRActionSet.Instance { //gd:OpenXRActionMap.action_sets
		return []OpenXRActionSet.Instance(gd.ArrayAs[[]OpenXRActionSet.Instance](gd.InternalArray(class(self).GetActionSets())))
}

// SetActionSets sets the property returned by [GetActionSets]. Returns the instance, so that property settings can be chained.
func (self Instance) SetActionSets(value []OpenXRActionSet.Instance) Instance { //gd:OpenXRActionMap.action_sets
	class(self).SetActionSets(gd.EngineArrayFromSlice(value))
	return self
}

func (self Instance) InteractionProfiles() []OpenXRInteractionProfile.Instance { //gd:OpenXRActionMap.interaction_profiles
		return []OpenXRInteractionProfile.Instance(gd.ArrayAs[[]OpenXRInteractionProfile.Instance](gd.InternalArray(class(self).GetInteractionProfiles())))
}

// SetInteractionProfiles sets the property returned by [GetInteractionProfiles]. Returns the instance, so that property settings can be chained.
func (self Instance) SetInteractionProfiles(value []OpenXRInteractionProfile.Instance) Instance { //gd:OpenXRActionMap.interaction_profiles
	class(self).SetInteractionProfiles(gd.EngineArrayFromSlice(value))
	return self
}

func (self class) SetActionSets(action_sets Array.Any)  { //gd:OpenXRActionMap.set_action_sets
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_action_sets, 0|(gdextension.SizeArray<<4), &struct{action_sets gdextension.Array}{pointers.Get(gd.InternalArray(action_sets))})
}
func (self class) GetActionSets() Array.Any { //gd:OpenXRActionMap.get_action_sets
	var r_ret = noescape.Call[gdextension.Array]( gd.ObjectChecked(self.AsObject()), methods.get_action_sets, gdextension.SizeArray, &struct{}{})
	var ret = Array.Through(gd.ArrayProxy[variant.Any]{}, pointers.Pack(pointers.New[gd.Array](r_ret)))
	return ret
}
func (self class) GetActionSetCount() int64 { //gd:OpenXRActionMap.get_action_set_count
	var r_ret = noescape.Call[int64]( gd.ObjectChecked(self.AsObject()), methods.get_action_set_count, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) FindActionSet(name String.Readable) [1]gdclass.OpenXRActionSet { //gd:OpenXRActionMap.find_action_set
	var r_ret = noescape.Call[gdextension.Object]( gd.ObjectChecked(self.AsObject()), methods.find_action_set, gdextension.SizeObject|(gdextension.SizeString<<4), &struct{name gdextension.String}{pointers.Get(gd.InternalString(name))})
	var ret = [1]gdclass.OpenXRActionSet{gdclass.NewOpenXRActionSet(gd.PointerWithOwnershipTransferredToGo(r_ret))}
	return ret
}
func (self class) GetActionSet(idx int64) [1]gdclass.OpenXRActionSet { //gd:OpenXRActionMap.get_action_set
	var r_ret = noescape.Call[gdextension.Object]( gd.ObjectChecked(self.AsObject()), methods.get_action_set, gdextension.SizeObject|(gdextension.SizeInt<<4), &struct{idx int64}{idx})
	var ret = [1]gdclass.OpenXRActionSet{gdclass.NewOpenXRActionSet(gd.PointerWithOwnershipTransferredToGo(r_ret))}
	return ret
}
func (self class) AddActionSet(action_set [1]gdclass.OpenXRActionSet)  { //gd:OpenXRActionMap.add_action_set
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.add_action_set, 0|(gdextension.SizeObject<<4), &struct{action_set gdextension.Object}{	gdextension.Object(gdreference.GetObject(gdclass.GetOpenXRActionSet(action_set[0])[0]))})
}
func (self class) RemoveActionSet(action_set [1]gdclass.OpenXRActionSet)  { //gd:OpenXRActionMap.remove_action_set
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.remove_action_set, 0|(gdextension.SizeObject<<4), &struct{action_set gdextension.Object}{	gdextension.Object(gdreference.GetObject(gdclass.GetOpenXRActionSet(action_set[0])[0]))})
}
func (self class) SetInteractionProfiles(interaction_profiles Array.Any)  { //gd:OpenXRActionMap.set_interaction_profiles
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_interaction_profiles, 0|(gdextension.SizeArray<<4), &struct{interaction_profiles gdextension.Array}{pointers.Get(gd.InternalArray(interaction_profiles))})
}
func (self class) GetInteractionProfiles() Array.Any { //gd:OpenXRActionMap.get_interaction_profiles
	var r_ret = noescape.Call[gdextension.Array]( gd.ObjectChecked(self.AsObject()), methods.get_interaction_profiles, gdextension.SizeArray, &struct{}{})
	var ret = Array.Through(gd.ArrayProxy[variant.Any]{}, pointers.Pack(pointers.New[gd.Array](r_ret)))
	return ret
}
func (self class) GetInteractionProfileCount() int64 { //gd:OpenXRActionMap.get_interaction_profile_count
	var r_ret = noescape.Call[int64]( gd.ObjectChecked(self.AsObject()), methods.get_interaction_profile_count, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) FindInteractionProfile(name String.Readable) [1]gdclass.OpenXRInteractionProfile { //gd:OpenXRActionMap.find_interaction_profile
	var r_ret = noescape.Call[gdextension.Object]( gd.ObjectChecked(self.AsObject()), methods.find_interaction_profile, gdextension.SizeObject|(gdextension.SizeString<<4), &struct{name gdextension.String}{pointers.Get(gd.InternalString(name))})
	var ret = [1]gdclass.OpenXRInteractionProfile{gdclass.NewOpenXRInteractionProfile(gd.PointerWithOwnershipTransferredToGo(r_ret))}
	return ret
}
func (self class) GetInteractionProfile(idx int64) [1]gdclass.OpenXRInteractionProfile { //gd:OpenXRActionMap.get_interaction_profile
	var r_ret = noescape.Call[gdextension.Object]( gd.ObjectChecked(self.AsObject()), methods.get_interaction_profile, gdextension.SizeObject|(gdextension.SizeInt<<4), &struct{idx int64}{idx})
	var ret = [1]gdclass.OpenXRInteractionProfile{gdclass.NewOpenXRInteractionProfile(gd.PointerWithOwnershipTransferredToGo(r_ret))}
	return ret
}
func (self class) AddInteractionProfile(interaction_profile [1]gdclass.OpenXRInteractionProfile)  { //gd:OpenXRActionMap.add_interaction_profile
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.add_interaction_profile, 0|(gdextension.SizeObject<<4), &struct{interaction_profile gdextension.Object}{	gdextension.Object(gdreference.GetObject(gdclass.GetOpenXRInteractionProfile(interaction_profile[0])[0]))})
}
func (self class) RemoveInteractionProfile(interaction_profile [1]gdclass.OpenXRInteractionProfile)  { //gd:OpenXRActionMap.remove_interaction_profile
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.remove_interaction_profile, 0|(gdextension.SizeObject<<4), &struct{interaction_profile gdextension.Object}{	gdextension.Object(gdreference.GetObject(gdclass.GetOpenXRInteractionProfile(interaction_profile[0])[0]))})
}
func (self class) CreateDefaultActionSets()  { //gd:OpenXRActionMap.create_default_action_sets
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.create_default_action_sets, 0, &struct{}{})
}
func (o class) AsOpenXRActionMap() Advanced { return Advanced(o) }
func (o Instance) AsOpenXRActionMap() Instance { return o }
func (o *Extension[T]) AsOpenXRActionMap() Instance { return o.Super() }
func (o class) AsResource() Resource.Advanced { return *(*Resource.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsResource() Resource.Instance { return o.Super().AsResource() }
func (o Instance) AsResource() Resource.Instance { return *(*Resource.Instance)(ie.As(&o)) }
func (o class) AsRefCounted() ie.RC { return *(*ie.RC)(ie.As(&o)) }
func (o *Extension[T]) AsRefCounted() ie.RC { return o.Super().AsRefCounted() }
func (o Instance) AsRefCounted() ie.RC { return *(*ie.RC)(ie.As(&o)) }

// OnChanged is promoted from [Resource.Instance.OnChanged].
func (self Instance) OnChanged(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("changed"), gd.NewCallable(cb), int64(flags_together))
	return self
}

// OnSetupLocalToSceneRequested is promoted from [Resource.Instance.OnSetupLocalToSceneRequested].
func (self Instance) OnSetupLocalToSceneRequested(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("setup_local_to_scene_requested"), gd.NewCallable(cb), int64(flags_together))
	return self
}
func (o *Extension[T]) GetActionSetCount() int {
	return o.Super().GetActionSetCount()
}
func (o *Extension[T]) FindActionSet(name string) OpenXRActionSet.Instance {
	return o.Super().FindActionSet(name)
}
func (o *Extension[T]) GetActionSet(idx int) OpenXRActionSet.Instance {
	return o.Super().GetActionSet(idx)
}
func (o *Extension[T]) AddActionSet(action_set OpenXRActionSet.Instance) {
	o.Super().AddActionSet(action_set)
}
func (o *Extension[T]) RemoveActionSet(action_set OpenXRActionSet.Instance) {
	o.Super().RemoveActionSet(action_set)
}
func (o *Extension[T]) GetInteractionProfileCount() int {
	return o.Super().GetInteractionProfileCount()
}
func (o *Extension[T]) FindInteractionProfile(name string) OpenXRInteractionProfile.Instance {
	return o.Super().FindInteractionProfile(name)
}
func (o *Extension[T]) GetInteractionProfile(idx int) OpenXRInteractionProfile.Instance {
	return o.Super().GetInteractionProfile(idx)
}
func (o *Extension[T]) AddInteractionProfile(interaction_profile OpenXRInteractionProfile.Instance) {
	o.Super().AddInteractionProfile(interaction_profile)
}
func (o *Extension[T]) RemoveInteractionProfile(interaction_profile OpenXRInteractionProfile.Instance) {
	o.Super().RemoveInteractionProfile(interaction_profile)
}
func (o *Extension[T]) CreateDefaultActionSets() {
	o.Super().CreateDefaultActionSets()
}

// TakeOverPath is promoted from [Resource.Instance.TakeOverPath].
func (self Instance) TakeOverPath(path string) {
	self.AsResource().TakeOverPath(path)
}

// TakeOverPath is promoted from [Resource.Instance.TakeOverPath].
func (o *Extension[T]) TakeOverPath(path string) {
	o.Super().AsResource().TakeOverPath(path)
}

// SetPathCache is promoted from [Resource.Instance.SetPathCache].
func (self Instance) SetPathCache(path string) Instance {
	self.AsResource().SetPathCache(path)
	return self
}

// SetPathCache is promoted from [Resource.Instance.SetPathCache].
func (o *Extension[T]) SetPathCache(path string) *Extension[T] {
	o.Super().AsResource().SetPathCache(path)
	return o
}

// GetRid is promoted from [Resource.Instance.GetRid].
func (self Instance) GetRid() Resource.ID {
	return self.AsResource().GetRid()
}

// GetRid is promoted from [Resource.Instance.GetRid].
func (o *Extension[T]) GetRid() Resource.ID {
	return o.Super().AsResource().GetRid()
}

// SetupLocalToScene is promoted from [Resource.Instance.SetupLocalToScene].
func (self Instance) SetupLocalToScene() {
	self.AsResource().SetupLocalToScene()
}

// SetupLocalToScene is promoted from [Resource.Instance.SetupLocalToScene].
func (o *Extension[T]) SetupLocalToScene() {
	o.Super().AsResource().SetupLocalToScene()
}

// ResetState is promoted from [Resource.Instance.ResetState].
func (self Instance) ResetState() {
	self.AsResource().ResetState()
}

// ResetState is promoted from [Resource.Instance.ResetState].
func (o *Extension[T]) ResetState() {
	o.Super().AsResource().ResetState()
}

// SetIdForPath is promoted from [Resource.Instance.SetIdForPath].
func (self Instance) SetIdForPath(path string, id string) Instance {
	self.AsResource().SetIdForPath(path, id)
	return self
}

// SetIdForPath is promoted from [Resource.Instance.SetIdForPath].
func (o *Extension[T]) SetIdForPath(path string, id string) *Extension[T] {
	o.Super().AsResource().SetIdForPath(path, id)
	return o
}

// GetIdForPath is promoted from [Resource.Instance.GetIdForPath].
func (self Instance) GetIdForPath(path string) string {
	return self.AsResource().GetIdForPath(path)
}

// GetIdForPath is promoted from [Resource.Instance.GetIdForPath].
func (o *Extension[T]) GetIdForPath(path string) string {
	return o.Super().AsResource().GetIdForPath(path)
}

// IsBuiltIn is promoted from [Resource.Instance.IsBuiltIn].
func (self Instance) IsBuiltIn() bool {
	return self.AsResource().IsBuiltIn()
}

// IsBuiltIn is promoted from [Resource.Instance.IsBuiltIn].
func (o *Extension[T]) IsBuiltIn() bool {
	return o.Super().AsResource().IsBuiltIn()
}

// EmitChanged is promoted from [Resource.Instance.EmitChanged].
func (self Instance) EmitChanged() {
	self.AsResource().EmitChanged()
}

// EmitChanged is promoted from [Resource.Instance.EmitChanged].
func (o *Extension[T]) EmitChanged() {
	o.Super().AsResource().EmitChanged()
}

func (self class) Virtual(name string) reflect.Value {
	switch name {
	default: return gd.VirtualByName(Resource.Advanced(self.AsResource()), name)
	}
}

func (self Instance) Virtual(name string) reflect.Value {
	switch name {
	default: return gd.VirtualByName(Resource.Instance(self.AsResource()), name)
	}
}
func init() {gdclass.Register("OpenXRActionMap", func(ptr gdreference.Object) any { return Instance{gdclass.NewOpenXRActionMap(ptr)} })}
