// Code generated by the generate package DO NOT EDIT


package ProjectSettings

import "sync"
import "reflect"
import "slices"
import "graphics.gd/internal/pointers"
import "graphics.gd/internal/callframe"
import "graphics.gd/internal/gdextension"
import "graphics.gd/internal/gdreference"
import "graphics.gd/internal/noescape"
import gd "graphics.gd/internal"
import "graphics.gd/internal/gdclass"
import "graphics.gd/internal/ie"
import "graphics.gd/variant"
import "graphics.gd/variant/Angle"
import "graphics.gd/variant/Euler"
import "graphics.gd/variant/Signal"
import "graphics.gd/variant/Array"
import "graphics.gd/variant/Callable"
import "graphics.gd/variant/Dictionary"
import "graphics.gd/variant/Error"
import "graphics.gd/variant/Float"
import "graphics.gd/variant/Object"
import "graphics.gd/variant/Packed"
import "graphics.gd/variant/Path"
import "graphics.gd/variant/RID"
import "graphics.gd/variant/RefCounted"
import "graphics.gd/variant/String"

var _ Object.ID
type _ gdclass.Node
var _ gd.String
var _ RefCounted.Instance
var _ reflect.Type
var _ callframe.Frame
var _ = pointers.Cycle
var _ = Array.Nil
var _ variant.Any
var _ Callable.Function
var _ Dictionary.Any
var _ RID.Any
var _ noescape.Variant
var _ String.Readable
var _ Path.ToNode
var _ Packed.Bytes
var _ Error.Code
var _ Float.X
var _ Signal.Any
var _ Angle.Radians
var _ Euler.Radians
var _ gdextension.Object
var _ = slices.Delete[[]struct{}, struct{}]

/*
ID is a typed object ID (reference) to an instance of this class, use it to store references to objects with
unknown lifetimes, as an ID will not panic on use if the underlying object has been destroyed.
*/
type ID Object.ID
func (id ID) Instance() (Instance, bool) { return Object.As[Instance](Object.ID(id).Instance()) }
/*
Extension can be embedded in a new struct to create a Go extension of this class.

T must be a type that is embedding this [Extension] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Extension[T gdclass.Interface] struct { gdclass.Extension[T, Instance] }
/*
Singleton can be embedded in a new struct to create a Go singleton extension of the class.

It will become available as a global inside scripts and any any other Go Extension types will
have any *T typed fields filled in to point at this singleton once they have been instantiated.

T must be a type that is embedding this [Singleton] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Singleton[T gdclass.Interface] = Extension[T]
// Instance of the class with convieniently typed arguments and results.
type Instance [1]gdclass.ProjectSettings
var otype gdextension.ObjectType
var sname gdextension.StringName
var methods struct {
	has_setting gdextension.MethodForClass `hash:"3927539163"`
	set_setting gdextension.MethodForClass `hash:"402577236"`
	get_setting gdextension.MethodForClass `hash:"223050753"`
	get_setting_with_override gdextension.MethodForClass `hash:"2760726917"`
	get_global_class_list gdextension.MethodForClass `hash:"2915620761"`
	get_setting_with_override_and_custom_features gdextension.MethodForClass `hash:"2434817427"`
	set_order gdextension.MethodForClass `hash:"2956805083"`
	get_order gdextension.MethodForClass `hash:"1321353865"`
	set_initial_value gdextension.MethodForClass `hash:"402577236"`
	set_as_basic gdextension.MethodForClass `hash:"2678287736"`
	set_as_internal gdextension.MethodForClass `hash:"2678287736"`
	add_property_info gdextension.MethodForClass `hash:"4155329257"`
	set_restart_if_changed gdextension.MethodForClass `hash:"2678287736"`
	clear gdextension.MethodForClass `hash:"83702148"`
	localize_path gdextension.MethodForClass `hash:"3135753539"`
	globalize_path gdextension.MethodForClass `hash:"3135753539"`
	save gdextension.MethodForClass `hash:"166280745"`
	load_resource_pack gdextension.MethodForClass `hash:"708980503"`
	save_custom gdextension.MethodForClass `hash:"166001499"`
	get_changed_settings gdextension.MethodForClass `hash:"1139954409"`
	check_changed_settings_in_group gdextension.MethodForClass `hash:"3927539163"`
}
func init() {
	gd.Links = append(gd.Links, func() {
		sname = gdextension.Host.Strings.Intern.UTF8("ProjectSettings")
		otype = gdextension.Host.Objects.Type(sname)
		gd.LinkMethods(sname, &methods, false)
		})
	gd.RegisterCleanup(func() {
		noescape.Free(gdextension.TypeStringName, &sname)
	})
}
func (self Instance) ID() ID { return ID(Object.Instance(self.AsObject()).ID()) }
var self [1]gdclass.ProjectSettings
var once sync.Once
func singleton() {
	self[0] = gdclass.NewProjectSettings(gdreference.RawObject(gdextension.Host.Objects.Global(sname)))
}
func HasSetting(name string) bool { //gd:ProjectSettings.has_setting
	return bool(Advanced().HasSetting(String.From(name)))
}
func SetSetting(name string, value any) { //gd:ProjectSettings.set_setting
	Advanced().SetSetting(String.From(name), variant.New(value))
}
func GetSetting(name string, default_value any) any { //gd:ProjectSettings.get_setting
	return any(Advanced().GetSetting(String.From(name), variant.New(default_value)).Interface())
}
func GetSettingWithOverride(name string) any { //gd:ProjectSettings.get_setting_with_override
	return any(Advanced().GetSettingWithOverride(String.Name(String.From(name))).Interface())
}
func GetGlobalClassList() []GlobalClass { //gd:ProjectSettings.get_global_class_list
	return []GlobalClass(gd.ArrayAs[[]GlobalClass](gd.InternalArray(Advanced().GetGlobalClassList())))
}
func GetSettingWithOverrideAndCustomFeatures(name string, features []string) any { //gd:ProjectSettings.get_setting_with_override_and_custom_features
	return any(Advanced().GetSettingWithOverrideAndCustomFeatures(String.Name(String.From(name)), Packed.MakeStrings(features...)).Interface())
}
func SetOrder(name string, position int) { //gd:ProjectSettings.set_order
	Advanced().SetOrder(String.From(name), int64(position))
}
func GetOrder(name string) int { //gd:ProjectSettings.get_order
	return int(int(Advanced().GetOrder(String.From(name))))
}
func SetInitialValue(name string, value any) { //gd:ProjectSettings.set_initial_value
	Advanced().SetInitialValue(String.From(name), variant.New(value))
}
func SetAsBasic(name string, basic bool) { //gd:ProjectSettings.set_as_basic
	Advanced().SetAsBasic(String.From(name), basic)
}
func SetAsInternal(name string, internal_ bool) { //gd:ProjectSettings.set_as_internal
	Advanced().SetAsInternal(String.From(name), internal_)
}
func AddPropertyInfo(hint Object.PropertyInfo) { //gd:ProjectSettings.add_property_info
	Advanced().AddPropertyInfo(gd.DictionaryFromMap(hint))
}
func SetRestartIfChanged(name string, restart bool) { //gd:ProjectSettings.set_restart_if_changed
	Advanced().SetRestartIfChanged(String.From(name), restart)
}
func Clear(name string) { //gd:ProjectSettings.clear
	Advanced().Clear(String.From(name))
}
func LocalizePath(path string) string { //gd:ProjectSettings.localize_path
	return string(Advanced().LocalizePath(String.From(path)).String())
}
func GlobalizePath(path string) string { //gd:ProjectSettings.globalize_path
	return string(Advanced().GlobalizePath(String.From(path)).String())
}
func Save() error { //gd:ProjectSettings.save
	return error(gd.ToError(Advanced().Save()))
}
func LoadResourcePack(pack string, offset int) bool { //gd:ProjectSettings.load_resource_pack
	return bool(Advanced().LoadResourcePack(String.From(pack), true, int64(offset)))
}
func LoadResourcePackOptions(pack string, replace_files bool, offset int) bool { //gd:ProjectSettings.load_resource_pack
	return bool(Advanced().LoadResourcePack(String.From(pack), replace_files, int64(offset)))
}
func SaveCustom(file string) error { //gd:ProjectSettings.save_custom
	return error(gd.ToError(Advanced().SaveCustom(String.From(file))))
}
func GetChangedSettings() []string { //gd:ProjectSettings.get_changed_settings
	return []string(Advanced().GetChangedSettings().Strings())
}
func CheckChangedSettingsInGroup(setting_prefix string) bool { //gd:ProjectSettings.check_changed_settings_in_group
	return bool(Advanced().CheckChangedSettingsInGroup(String.From(setting_prefix)))
}
// Advanced exposes a 1:1 low-level instance of the class, undocumented, for those who know what they are doing.
func Advanced() class { once.Do(singleton); return self }
type class [1]gdclass.ProjectSettings
func (o class) AsObject() [1]gdreference.Object { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (self *class) SetObject(obj [1]gdreference.Object) bool {
	if gdextension.Host.Objects.Cast(gdreference.GetObject(obj[0]), otype) != 0 {
		self[0] = gdclass.NewProjectSettings(obj[0])
		return true
	}
	return false
}
func (self *Instance) SetObject(obj [1]gdreference.Object) bool {
	if gdextension.Host.Objects.Cast(gdreference.GetObject(obj[0]), otype) != 0 {
		self[0] = gdclass.NewProjectSettings(obj[0])
		return true
	}
	return false
}
func (o Instance) AsObject() [1]gdreference.Object { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (o *Extension[T]) AsObject() [1]gdreference.Object { return o.Super().AsObject() }

func (self class) HasSetting(name String.Readable) bool { //gd:ProjectSettings.has_setting
once.Do(singleton)
		var r_ret = noescape.Call[bool]( gdreference.GetObject(self.AsObject()[0]), methods.has_setting, gdextension.SizeBool|(gdextension.SizeString<<4), &struct{name gdextension.String}{pointers.Get(gd.InternalString(name))})
	var ret = r_ret
	return ret
}
func (self class) SetSetting(name String.Readable, value variant.Any)  { //gd:ProjectSettings.set_setting
once.Do(singleton)
	noescape.Call[struct{}]( gdreference.GetObject(self.AsObject()[0]), methods.set_setting, 0|(gdextension.SizeString<<4)|(gdextension.SizeVariant<<8), &struct{name gdextension.String; value gdextension.Variant}{pointers.Get(gd.InternalString(name)), gdextension.Variant(pointers.Get(gd.InternalVariant(value)))})
}
func (self class) GetSetting(name String.Readable, default_value variant.Any) variant.Any { //gd:ProjectSettings.get_setting
once.Do(singleton)
		var r_ret = noescape.Call[gdextension.Variant]( gdreference.GetObject(self.AsObject()[0]), methods.get_setting, gdextension.SizeVariant|(gdextension.SizeString<<4)|(gdextension.SizeVariant<<8), &struct{name gdextension.String; default_value gdextension.Variant}{pointers.Get(gd.InternalString(name)), gdextension.Variant(pointers.Get(gd.InternalVariant(default_value)))})
	var ret = variant.Implementation(gd.VariantProxy{}, pointers.Pack(pointers.New[gd.Variant](r_ret)))
	return ret
}
func (self class) GetSettingWithOverride(name String.Name) variant.Any { //gd:ProjectSettings.get_setting_with_override
once.Do(singleton)
		var r_ret = noescape.Call[gdextension.Variant]( gdreference.GetObject(self.AsObject()[0]), methods.get_setting_with_override, gdextension.SizeVariant|(gdextension.SizeStringName<<4), &struct{name gdextension.StringName}{pointers.Get(gd.InternalStringName(name))})
	var ret = variant.Implementation(gd.VariantProxy{}, pointers.Pack(pointers.New[gd.Variant](r_ret)))
	return ret
}
func (self class) GetGlobalClassList() Array.Contains[Dictionary.Any] { //gd:ProjectSettings.get_global_class_list
once.Do(singleton)
		var r_ret = noescape.Call[gdextension.Array]( gdreference.GetObject(self.AsObject()[0]), methods.get_global_class_list, gdextension.SizeArray, &struct{}{})
	var ret = Array.Through(gd.ArrayProxy[Dictionary.Any]{}, pointers.Pack(pointers.New[gd.Array](r_ret)))
	return ret
}
func (self class) GetSettingWithOverrideAndCustomFeatures(name String.Name, features Packed.Strings) variant.Any { //gd:ProjectSettings.get_setting_with_override_and_custom_features
once.Do(singleton)
		var r_ret = noescape.Call[gdextension.Variant]( gdreference.GetObject(self.AsObject()[0]), methods.get_setting_with_override_and_custom_features, gdextension.SizeVariant|(gdextension.SizeStringName<<4)|(gdextension.SizePackedArray<<8), &struct{name gdextension.StringName; features gdextension.PackedArray[gdextension.String]}{pointers.Get(gd.InternalStringName(name)), pointers.Get(gd.InternalPackedStrings(features))})
	var ret = variant.Implementation(gd.VariantProxy{}, pointers.Pack(pointers.New[gd.Variant](r_ret)))
	return ret
}
func (self class) SetOrder(name String.Readable, position int64)  { //gd:ProjectSettings.set_order
once.Do(singleton)
	noescape.Call[struct{}]( gdreference.GetObject(self.AsObject()[0]), methods.set_order, 0|(gdextension.SizeString<<4)|(gdextension.SizeInt<<8), &struct{name gdextension.String; position int64}{pointers.Get(gd.InternalString(name)), position})
}
func (self class) GetOrder(name String.Readable) int64 { //gd:ProjectSettings.get_order
once.Do(singleton)
		var r_ret = noescape.Call[int64]( gdreference.GetObject(self.AsObject()[0]), methods.get_order, gdextension.SizeInt|(gdextension.SizeString<<4), &struct{name gdextension.String}{pointers.Get(gd.InternalString(name))})
	var ret = r_ret
	return ret
}
func (self class) SetInitialValue(name String.Readable, value variant.Any)  { //gd:ProjectSettings.set_initial_value
once.Do(singleton)
	noescape.Call[struct{}]( gdreference.GetObject(self.AsObject()[0]), methods.set_initial_value, 0|(gdextension.SizeString<<4)|(gdextension.SizeVariant<<8), &struct{name gdextension.String; value gdextension.Variant}{pointers.Get(gd.InternalString(name)), gdextension.Variant(pointers.Get(gd.InternalVariant(value)))})
}
func (self class) SetAsBasic(name String.Readable, basic bool)  { //gd:ProjectSettings.set_as_basic
once.Do(singleton)
	noescape.Call[struct{}]( gdreference.GetObject(self.AsObject()[0]), methods.set_as_basic, 0|(gdextension.SizeString<<4)|(gdextension.SizeBool<<8), &struct{name gdextension.String; basic bool}{pointers.Get(gd.InternalString(name)), basic})
}
func (self class) SetAsInternal(name String.Readable, internal_ bool)  { //gd:ProjectSettings.set_as_internal
once.Do(singleton)
	noescape.Call[struct{}]( gdreference.GetObject(self.AsObject()[0]), methods.set_as_internal, 0|(gdextension.SizeString<<4)|(gdextension.SizeBool<<8), &struct{name gdextension.String; internal_ bool}{pointers.Get(gd.InternalString(name)), internal_})
}
func (self class) AddPropertyInfo(hint Dictionary.Any)  { //gd:ProjectSettings.add_property_info
once.Do(singleton)
	noescape.Call[struct{}]( gdreference.GetObject(self.AsObject()[0]), methods.add_property_info, 0|(gdextension.SizeDictionary<<4), &struct{hint gdextension.Dictionary}{pointers.Get(gd.InternalDictionary(hint))})
}
func (self class) SetRestartIfChanged(name String.Readable, restart bool)  { //gd:ProjectSettings.set_restart_if_changed
once.Do(singleton)
	noescape.Call[struct{}]( gdreference.GetObject(self.AsObject()[0]), methods.set_restart_if_changed, 0|(gdextension.SizeString<<4)|(gdextension.SizeBool<<8), &struct{name gdextension.String; restart bool}{pointers.Get(gd.InternalString(name)), restart})
}
func (self class) Clear(name String.Readable)  { //gd:ProjectSettings.clear
once.Do(singleton)
	noescape.Call[struct{}]( gdreference.GetObject(self.AsObject()[0]), methods.clear, 0|(gdextension.SizeString<<4), &struct{name gdextension.String}{pointers.Get(gd.InternalString(name))})
}
func (self class) LocalizePath(path String.Readable) String.Readable { //gd:ProjectSettings.localize_path
once.Do(singleton)
		var r_ret = noescape.Call[gdextension.String]( gdreference.GetObject(self.AsObject()[0]), methods.localize_path, gdextension.SizeString|(gdextension.SizeString<<4), &struct{path gdextension.String}{pointers.Get(gd.InternalString(path))})
	var ret = String.Via(gd.StringProxy{}, pointers.Pack(pointers.New[gd.String](r_ret)))
	return ret
}
func (self class) GlobalizePath(path String.Readable) String.Readable { //gd:ProjectSettings.globalize_path
once.Do(singleton)
		var r_ret = noescape.Call[gdextension.String]( gdreference.GetObject(self.AsObject()[0]), methods.globalize_path, gdextension.SizeString|(gdextension.SizeString<<4), &struct{path gdextension.String}{pointers.Get(gd.InternalString(path))})
	var ret = String.Via(gd.StringProxy{}, pointers.Pack(pointers.New[gd.String](r_ret)))
	return ret
}
func (self class) Save() Error.Code { //gd:ProjectSettings.save
once.Do(singleton)
		var r_ret = noescape.Call[int64]( gdreference.GetObject(self.AsObject()[0]), methods.save, gdextension.SizeInt, &struct{}{})
	var ret = Error.Code(r_ret)
	return ret
}
func (self class) LoadResourcePack(pack String.Readable, replace_files bool, offset int64) bool { //gd:ProjectSettings.load_resource_pack
once.Do(singleton)
		var r_ret = noescape.Call[bool]( gdreference.GetObject(self.AsObject()[0]), methods.load_resource_pack, gdextension.SizeBool|(gdextension.SizeString<<4)|(gdextension.SizeBool<<8)|(gdextension.SizeInt<<12), &struct{pack gdextension.String; replace_files bool; offset int64}{pointers.Get(gd.InternalString(pack)), replace_files, offset})
	var ret = r_ret
	return ret
}
func (self class) SaveCustom(file String.Readable) Error.Code { //gd:ProjectSettings.save_custom
once.Do(singleton)
		var r_ret = noescape.Call[int64]( gdreference.GetObject(self.AsObject()[0]), methods.save_custom, gdextension.SizeInt|(gdextension.SizeString<<4), &struct{file gdextension.String}{pointers.Get(gd.InternalString(file))})
	var ret = Error.Code(r_ret)
	return ret
}
func (self class) GetChangedSettings() Packed.Strings { //gd:ProjectSettings.get_changed_settings
once.Do(singleton)
		var r_ret = noescape.Call[gd.PackedPointers]( gdreference.GetObject(self.AsObject()[0]), methods.get_changed_settings, gdextension.SizePackedArray, &struct{}{})
	var ret = Packed.Strings(Array.Through(gd.PackedStringArrayProxy{}, pointers.Pack(pointers.Let[gd.PackedStringArray](r_ret))))
	return ret
}
func (self class) CheckChangedSettingsInGroup(setting_prefix String.Readable) bool { //gd:ProjectSettings.check_changed_settings_in_group
once.Do(singleton)
		var r_ret = noescape.Call[bool]( gdreference.GetObject(self.AsObject()[0]), methods.check_changed_settings_in_group, gdextension.SizeBool|(gdextension.SizeString<<4), &struct{setting_prefix gdextension.String}{pointers.Get(gd.InternalString(setting_prefix))})
	var ret = r_ret
	return ret
}
func OnSettingsChanged(cb func(), flags ...Signal.Flags) {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	once.Do(singleton)
	gd.ObjectConnect(gdclass.GetProjectSettings(self[0])[0], gd.NewStringName("settings_changed"), gd.NewCallable(cb), int64(flags_together))
}



func (self class) SettingsChanged() Signal.Any {
once.Do(singleton)
	return Signal.Via(gd.SignalProxy{}, pointers.Pack(gd.NewSignalOf(self.AsObject(), gd.NewStringName(`settings_changed`))))}

func (self class) Virtual(name string) reflect.Value {
	switch name {
	default: return gd.VirtualByName(Object.Advanced(self.AsObject()), name)
	}
}

func (self Instance) Virtual(name string) reflect.Value {
	switch name {
	default: return gd.VirtualByName(Object.Instance(self.AsObject()), name)
	}
}
func init() {gdclass.Register("ProjectSettings", func(ptr gdreference.Object) any { return Instance{gdclass.NewProjectSettings(ptr)} })}
type GlobalClass struct {
Base string `gd:"base"`
Class string `gd:"class"`
Icon string `gd:"icon"`
Language string `gd:"language"`
Path string `gd:"path"`
}
