// Code generated by the generate package DO NOT EDIT


package PhysicsTestMotionParameters2D

import "reflect"
import "slices"
import "github.com/AveryLucas/gogogd/internal/pointers"
import "github.com/AveryLucas/gogogd/internal/callframe"
import "github.com/AveryLucas/gogogd/internal/gdextension"
import "github.com/AveryLucas/gogogd/internal/gdreference"
import "github.com/AveryLucas/gogogd/internal/noescape"
import gd "github.com/AveryLucas/gogogd/internal"
import "github.com/AveryLucas/gogogd/internal/gdclass"
import "github.com/AveryLucas/gogogd/internal/ie"
import "github.com/AveryLucas/gogogd/variant"
import "github.com/AveryLucas/gogogd/variant/Angle"
import "github.com/AveryLucas/gogogd/variant/Euler"
import "github.com/AveryLucas/gogogd/variant/Signal"
import "github.com/AveryLucas/gogogd/variant/Array"
import "github.com/AveryLucas/gogogd/variant/Callable"
import "github.com/AveryLucas/gogogd/variant/Dictionary"
import "github.com/AveryLucas/gogogd/variant/Error"
import "github.com/AveryLucas/gogogd/variant/Float"
import "github.com/AveryLucas/gogogd/variant/Object"
import "github.com/AveryLucas/gogogd/variant/Packed"
import "github.com/AveryLucas/gogogd/variant/Path"
import "github.com/AveryLucas/gogogd/variant/RID"
import "github.com/AveryLucas/gogogd/variant/RefCounted"
import "github.com/AveryLucas/gogogd/variant/String"
import "github.com/AveryLucas/gogogd/variant/Transform2D"
import "github.com/AveryLucas/gogogd/variant/Vector2"

var _ Object.ID
type _ gdclass.Node
var _ gd.String
var _ RefCounted.Instance
var _ reflect.Type
var _ callframe.Frame
var _ = pointers.Cycle
var _ = Array.Nil
var _ variant.Any
var _ Callable.Function
var _ Dictionary.Any
var _ RID.Any
var _ noescape.Variant
var _ String.Readable
var _ Path.ToNode
var _ Packed.Bytes
var _ Error.Code
var _ Float.X
var _ Signal.Any
var _ Angle.Radians
var _ Euler.Radians
var _ gdextension.Object
var _ = slices.Delete[[]struct{}, struct{}]

/*
ID is a typed object ID (reference) to an instance of this class, use it to store references to objects with
unknown lifetimes, as an ID will not panic on use if the underlying object has been destroyed.
*/
type ID Object.ID
func (id ID) Instance() (Instance, bool) { return Object.As[Instance](Object.ID(id).Instance()) }
/*
Extension can be embedded in a new struct to create a Go extension of this class.

T must be a type that is embedding this [Extension] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Extension[T gdclass.Interface] struct { gdclass.Extension[T, Instance] }
/*
Singleton can be embedded in a new struct to create a Go singleton extension of the class.

It will become available as a global inside scripts and any any other Go Extension types will
have any *T typed fields filled in to point at this singleton once they have been instantiated.

T must be a type that is embedding this [Singleton] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Singleton[T gdclass.Interface] = Extension[T]
// Instance of the class with convieniently typed arguments and results.
type Instance [1]gdclass.PhysicsTestMotionParameters2D
var otype gdextension.ObjectType
var sname gdextension.StringName
var methods struct {
	get_from gdextension.MethodForClass `hash:"3814499831"`
	set_from gdextension.MethodForClass `hash:"2761652528"`
	get_motion gdextension.MethodForClass `hash:"3341600327"`
	set_motion gdextension.MethodForClass `hash:"743155724"`
	get_margin gdextension.MethodForClass `hash:"1740695150"`
	set_margin gdextension.MethodForClass `hash:"373806689"`
	is_collide_separation_ray_enabled gdextension.MethodForClass `hash:"36873697"`
	set_collide_separation_ray_enabled gdextension.MethodForClass `hash:"2586408642"`
	get_exclude_bodies gdextension.MethodForClass `hash:"3995934104"`
	set_exclude_bodies gdextension.MethodForClass `hash:"381264803"`
	get_exclude_objects gdextension.MethodForClass `hash:"3995934104"`
	set_exclude_objects gdextension.MethodForClass `hash:"381264803"`
	is_recovery_as_collision_enabled gdextension.MethodForClass `hash:"36873697"`
	set_recovery_as_collision_enabled gdextension.MethodForClass `hash:"2586408642"`
}
func init() {
	gd.Links = append(gd.Links, func() {
		sname = gdextension.Host.Strings.Intern.UTF8("PhysicsTestMotionParameters2D")
		otype = gdextension.Host.Objects.Type(sname)
		gd.LinkMethods(sname, &methods, false)
		})
	gd.RegisterCleanup(func() {
		noescape.Free(gdextension.TypeStringName, &sname)
	})
}
func (self Instance) ID() ID { return ID(Object.Instance(self.AsObject()).ID()) }
// Nil is a nil/null instance of the class. Equivalent to the zero value.
var Nil Instance
type Any interface {
	gd.IsClass
	AsPhysicsTestMotionParameters2D() Instance
}
// Advanced exposes a 1:1 low-level instance of the class, undocumented, for those who know what they are doing.
type Advanced = class
type class [1]gdclass.PhysicsTestMotionParameters2D
func (o class) AsObject() [1]gdreference.Object { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (self *class) SetObject(obj [1]gdreference.Object) bool {
	if gdextension.Host.Objects.Cast(gdreference.GetObject(obj[0]), otype) != 0 {
		self[0] = gdclass.NewPhysicsTestMotionParameters2D(obj[0])
		return true
	}
	return false
}
func (self *Instance) SetObject(obj [1]gdreference.Object) bool {
	if gdextension.Host.Objects.Cast(gdreference.GetObject(obj[0]), otype) != 0 {
		self[0] = gdclass.NewPhysicsTestMotionParameters2D(obj[0])
		return true
	}
	return false
}
func (o Instance) AsObject() [1]gdreference.Object { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (o *Extension[T]) AsObject() [1]gdreference.Object { return o.Super().AsObject() }
func New() Instance {
if !gd.Linked {
		var placeholder = Instance([1]gdclass.PhysicsTestMotionParameters2D{gdclass.NewPhysicsTestMotionParameters2D(gdreference.NewObject())})
		gd.StartupFunctions = append(gd.StartupFunctions, func() {
			if gd.Linked {
				raw, _ := gdreference.EndObject(New().AsObject()[0])
				gdreference.SetObject(gdclass.GetPhysicsTestMotionParameters2D(placeholder[0])[0], raw)
				gd.RegisterCleanup(func() {
					if raw := gdreference.GetObject(placeholder.AsObject()[0]); raw != 0 {
						gdextension.Host.Objects.Unsafe.Free(raw)
					}
				})
			}
		})
		return placeholder
	}
	casted := Instance([1]gdclass.PhysicsTestMotionParameters2D{gdclass.NewPhysicsTestMotionParameters2D(gdreference.OwnObject(gdextension.Host.Objects.Make(sname), gd.Free))})
	casted.AsRefCounted()[0].InitRef()
	gd.ObjectNotification(casted.AsObject()[0], 0, false)
	return casted
}

func (self Instance) From() Transform2D.OriginXY { //gd:PhysicsTestMotionParameters2D.from
		return Transform2D.OriginXY(class(self).GetFrom())
}

func (o *Extension[T]) From() Transform2D.OriginXY { return o.Super().From() }

// SetFrom sets the property returned by [GetFrom]. Returns the instance, so that property settings can be chained.
func (self Instance) SetFrom(value Transform2D.OriginXY) Instance { //gd:PhysicsTestMotionParameters2D.from
	class(self).SetFrom(Transform2D.OriginXY(value))
	return self
}

func (o *Extension[T]) SetFrom(value Transform2D.OriginXY) *Extension[T] {
	o.Super().SetFrom(value)
	return o
}

func (self Instance) Motion() Vector2.XY { //gd:PhysicsTestMotionParameters2D.motion
		return Vector2.XY(class(self).GetMotion())
}

func (o *Extension[T]) Motion() Vector2.XY { return o.Super().Motion() }

// SetMotion sets the property returned by [GetMotion]. Returns the instance, so that property settings can be chained.
func (self Instance) SetMotion(value Vector2.XY) Instance { //gd:PhysicsTestMotionParameters2D.motion
	class(self).SetMotion(Vector2.XY(value))
	return self
}

func (o *Extension[T]) SetMotion(value Vector2.XY) *Extension[T] {
	o.Super().SetMotion(value)
	return o
}

func (self Instance) Margin() Float.X { //gd:PhysicsTestMotionParameters2D.margin
		return Float.X(Float.X(class(self).GetMargin()))
}

func (o *Extension[T]) Margin() Float.X { return o.Super().Margin() }

// SetMargin sets the property returned by [GetMargin]. Returns the instance, so that property settings can be chained.
func (self Instance) SetMargin(value Float.X) Instance { //gd:PhysicsTestMotionParameters2D.margin
	class(self).SetMargin(float64(value))
	return self
}

func (o *Extension[T]) SetMargin(value Float.X) *Extension[T] {
	o.Super().SetMargin(value)
	return o
}

func (self Instance) CollideSeparationRay() bool { //gd:PhysicsTestMotionParameters2D.collide_separation_ray
		return bool(class(self).IsCollideSeparationRayEnabled())
}

func (o *Extension[T]) CollideSeparationRay() bool { return o.Super().CollideSeparationRay() }

// SetCollideSeparationRay sets the property returned by [IsCollideSeparationRayEnabled]. Returns the instance, so that property settings can be chained.
func (self Instance) SetCollideSeparationRay(value bool) Instance { //gd:PhysicsTestMotionParameters2D.collide_separation_ray
	class(self).SetCollideSeparationRayEnabled(value)
	return self
}

func (o *Extension[T]) SetCollideSeparationRay(value bool) *Extension[T] {
	o.Super().SetCollideSeparationRay(value)
	return o
}

func (self Instance) ExcludeBodies() []RID.Any { //gd:PhysicsTestMotionParameters2D.exclude_bodies
		return []RID.Any(gd.ArrayAs[[]RID.Any](gd.InternalArray(class(self).GetExcludeBodies())))
}

func (o *Extension[T]) ExcludeBodies() []RID.Any { return o.Super().ExcludeBodies() }

// SetExcludeBodies sets the property returned by [GetExcludeBodies]. Returns the instance, so that property settings can be chained.
func (self Instance) SetExcludeBodies(value []RID.Any) Instance { //gd:PhysicsTestMotionParameters2D.exclude_bodies
	class(self).SetExcludeBodies(gd.ArrayFromSlice[Array.Contains[RID.Any]](value))
	return self
}

func (o *Extension[T]) SetExcludeBodies(value []RID.Any) *Extension[T] {
	o.Super().SetExcludeBodies(value)
	return o
}

func (self Instance) ExcludeObjects() []int { //gd:PhysicsTestMotionParameters2D.exclude_objects
		return []int(gd.ArrayAs[[]int](gd.InternalArray(class(self).GetExcludeObjects())))
}

func (o *Extension[T]) ExcludeObjects() []int { return o.Super().ExcludeObjects() }

// SetExcludeObjects sets the property returned by [GetExcludeObjects]. Returns the instance, so that property settings can be chained.
func (self Instance) SetExcludeObjects(value []int) Instance { //gd:PhysicsTestMotionParameters2D.exclude_objects
	class(self).SetExcludeObjects(gd.ArrayFromSlice[Array.Contains[int64]](value))
	return self
}

func (o *Extension[T]) SetExcludeObjects(value []int) *Extension[T] {
	o.Super().SetExcludeObjects(value)
	return o
}

func (self Instance) RecoveryAsCollision() bool { //gd:PhysicsTestMotionParameters2D.recovery_as_collision
		return bool(class(self).IsRecoveryAsCollisionEnabled())
}

func (o *Extension[T]) RecoveryAsCollision() bool { return o.Super().RecoveryAsCollision() }

// SetRecoveryAsCollision sets the property returned by [IsRecoveryAsCollisionEnabled]. Returns the instance, so that property settings can be chained.
func (self Instance) SetRecoveryAsCollision(value bool) Instance { //gd:PhysicsTestMotionParameters2D.recovery_as_collision
	class(self).SetRecoveryAsCollisionEnabled(value)
	return self
}

func (o *Extension[T]) SetRecoveryAsCollision(value bool) *Extension[T] {
	o.Super().SetRecoveryAsCollision(value)
	return o
}

func (self class) GetFrom() Transform2D.OriginXY { //gd:PhysicsTestMotionParameters2D.get_from
	var r_ret = noescape.Call[Transform2D.OriginXY]( gd.ObjectChecked(self.AsObject()), methods.get_from, gdextension.SizeTransform2D, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetFrom(from Transform2D.OriginXY)  { //gd:PhysicsTestMotionParameters2D.set_from
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_from, 0|(gdextension.SizeTransform2D<<4), &struct{from Transform2D.OriginXY}{from})
}
func (self class) GetMotion() Vector2.XY { //gd:PhysicsTestMotionParameters2D.get_motion
	var r_ret = noescape.Call[Vector2.XY]( gd.ObjectChecked(self.AsObject()), methods.get_motion, gdextension.SizeVector2, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetMotion(motion Vector2.XY)  { //gd:PhysicsTestMotionParameters2D.set_motion
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_motion, 0|(gdextension.SizeVector2<<4), &struct{motion Vector2.XY}{motion})
}
func (self class) GetMargin() float64 { //gd:PhysicsTestMotionParameters2D.get_margin
	var r_ret = noescape.Call[float64]( gd.ObjectChecked(self.AsObject()), methods.get_margin, gdextension.SizeFloat, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetMargin(margin float64)  { //gd:PhysicsTestMotionParameters2D.set_margin
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_margin, 0|(gdextension.SizeFloat<<4), &struct{margin float64}{margin})
}
func (self class) IsCollideSeparationRayEnabled() bool { //gd:PhysicsTestMotionParameters2D.is_collide_separation_ray_enabled
	var r_ret = noescape.Call[bool]( gd.ObjectChecked(self.AsObject()), methods.is_collide_separation_ray_enabled, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetCollideSeparationRayEnabled(enabled bool)  { //gd:PhysicsTestMotionParameters2D.set_collide_separation_ray_enabled
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_collide_separation_ray_enabled, 0|(gdextension.SizeBool<<4), &struct{enabled bool}{enabled})
}
func (self class) GetExcludeBodies() Array.Contains[RID.Any] { //gd:PhysicsTestMotionParameters2D.get_exclude_bodies
	var r_ret = noescape.Call[gdextension.Array]( gd.ObjectChecked(self.AsObject()), methods.get_exclude_bodies, gdextension.SizeArray, &struct{}{})
	var ret = Array.Through(gd.ArrayProxy[RID.Any]{}, pointers.Pack(pointers.New[gd.Array](r_ret)))
	return ret
}
func (self class) SetExcludeBodies(exclude_list Array.Contains[RID.Any])  { //gd:PhysicsTestMotionParameters2D.set_exclude_bodies
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_exclude_bodies, 0|(gdextension.SizeArray<<4), &struct{exclude_list gdextension.Array}{pointers.Get(gd.InternalArray(exclude_list))})
}
func (self class) GetExcludeObjects() Array.Contains[int64] { //gd:PhysicsTestMotionParameters2D.get_exclude_objects
	var r_ret = noescape.Call[gdextension.Array]( gd.ObjectChecked(self.AsObject()), methods.get_exclude_objects, gdextension.SizeArray, &struct{}{})
	var ret = Array.Through(gd.ArrayProxy[int64]{}, pointers.Pack(pointers.New[gd.Array](r_ret)))
	return ret
}
func (self class) SetExcludeObjects(exclude_list Array.Contains[int64])  { //gd:PhysicsTestMotionParameters2D.set_exclude_objects
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_exclude_objects, 0|(gdextension.SizeArray<<4), &struct{exclude_list gdextension.Array}{pointers.Get(gd.InternalArray(exclude_list))})
}
func (self class) IsRecoveryAsCollisionEnabled() bool { //gd:PhysicsTestMotionParameters2D.is_recovery_as_collision_enabled
	var r_ret = noescape.Call[bool]( gd.ObjectChecked(self.AsObject()), methods.is_recovery_as_collision_enabled, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetRecoveryAsCollisionEnabled(enabled bool)  { //gd:PhysicsTestMotionParameters2D.set_recovery_as_collision_enabled
noescape.Call[struct{}]( gd.ObjectChecked(self.AsObject()), methods.set_recovery_as_collision_enabled, 0|(gdextension.SizeBool<<4), &struct{enabled bool}{enabled})
}
func (o class) AsPhysicsTestMotionParameters2D() Advanced { return Advanced(o) }
func (o Instance) AsPhysicsTestMotionParameters2D() Instance { return o }
func (o *Extension[T]) AsPhysicsTestMotionParameters2D() Instance { return o.Super() }
func (o class) AsRefCounted() ie.RC { return *(*ie.RC)(ie.As(&o)) }
func (o *Extension[T]) AsRefCounted() ie.RC { return o.Super().AsRefCounted() }
func (o Instance) AsRefCounted() ie.RC { return *(*ie.RC)(ie.As(&o)) }

func (self class) Virtual(name string) reflect.Value {
	switch name {
	default: return gd.VirtualByName(RefCounted.Advanced(self.AsRefCounted()), name)
	}
}

func (self Instance) Virtual(name string) reflect.Value {
	switch name {
	default: return gd.VirtualByName(RefCounted.Instance(self.AsRefCounted()), name)
	}
}
func init() {gdclass.Register("PhysicsTestMotionParameters2D", func(ptr gdreference.Object) any { return Instance{gdclass.NewPhysicsTestMotionParameters2D(ptr)} })}
